smb: add smb.version keyword 5075 v9
OISF/suricata pull request #10012
Opened 2023-12-08 13:31 UTC by jmtaylor90

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5075

Describe changes:
- removed unnecessary smb::SMBTransaction include
- updated documentation example rule formatting
- updated keyword description to include where version is determined
- fixed dod pointer leak
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=pr/1380
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-12-08 19:48 UTC, jufajardini requested changes
I see that stuff from previous reviews seems to have been incorporated, thanks!

Sorry for catching some new stuff in this one >__<'

2023-12-11 16:38 UTC, jmtaylor90 commented on doc/userguide/rules/smb-keywords.rst
> +- 0xfcSMB is SMB2 `transform compression header <https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/d6ce2327-a4c9-4793-be66-7b5bad2175fa>`_ (can be `chained <https://docs.microsoft.
Updated in the next PR

2023-12-11 16:40 UTC, jmtaylor90 commented on doc/userguide/rules/smb-keywords.rst
> +The Protocol ID in the header distinguishes only SMB1 and SMB2 since they are totally different protocols with total different message formats, types and implementation.
Updated in the next PR

2023-12-11 16:43 UTC, jmtaylor90 commented on doc/userguide/rules/smb-keywords.rst
> +
Updated to include that information in the next PR

2023-12-11 16:48 UTC, jmtaylor90 commented on src/detect-engine-register.c
> +
Updated in next PR

2023-12-11 17:02 UTC, closed without merging