Misc improvements/v1
OISF/suricata pull request #10016
Opened 2023-12-08 16:23 UTC by victorjulien

Misc fixes and improvments.

Main: https://redmine.openinfosecfoundation.org/issues/6615

2023-12-08 18:55 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16960

2023-12-11 11:08 UTC, inashivb reviewed
No opinion on https://github.com/OISF/suricata/pull/10016/commits/a3aea61554258e354e51a7c256c43a675eb7347f
Not sure about content inspection and bytejump analysis.
One nit ques inline.

2023-12-11 12:08 UTC, victorjulien commented on rust/src/jsonbuilder.rs
> +
Don't know. I just copied `set_uint`.

2023-12-11 14:50 UTC, jufajardini reviewed
Not confident to approve 2d51cfcba61f2, but looks good to me.
One nit on a function comment.
Overall, looks good to me.

2023-12-11 14:50 UTC, jufajardini commented on rust/src/jsonbuilder.rs
> +    /// Set a key and an signed integer type on an object.
nit: a signed integer

2023-12-11 16:23 UTC, jasonish requested changes
The typo.

Also, anymore context for bytejump flag other than the "future" :)

2023-12-11 17:33 UTC, victorjulien commented
> The typo.
> 
> Also, anymore context for bytejump flag other than the "future" :)

Right now using the wrong flag doesn't cause issues, as the flag's value is not used by bytejump flags. So there is no conflict. If in the future bytejump would add a new flag with the same value, it would cause unknown issues.

2023-12-12 06:36 UTC, inashivb commented on rust/src/jsonbuilder.rs
> +
ah. I see. Thanks!

2023-12-13 07:44 UTC, victorjulien commented
Comments addressed in #10042

2023-12-13 07:44 UTC, closed without merging