detect-flowbits: add details for flowbits v8
OISF/suricata pull request #10026
Opened 2023-12-11 14:46 UTC by hadiqaalamdar

Task #6309

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6309) ticket: https://redmine.openinfosecfoundation.org/issues/6309
Previous PR: https://github.com/OISF/suricata/pull/10018

Describe changes:
- added the recommended changes from the last PR. 
- Changed the is_or flag to bool. The operator string is working correctly for or operator.
- rebased with Shivani's PR: https://github.com/OISF/suricata/pull/10021

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1532

2023-12-11 17:26 UTC, jufajardini requested changes
Looking good to me, but the intermediary commit that still contains the `NOALERT` cmd type isn't necessary - as leads to the CI check. Could you please squash the commits?
I'll leave to Shivani the part about how to handle the `and` cases, as she'll probably be able to give insight on that much faster.

2023-12-12 06:29 UTC, inashivb requested changes
Nice work, Hadiqa! :)
Some minor comments inline. looking good from first sight.
1. Please squash commits as asked by Juliana.
2. Leave `and` for now. It is ok. It's not a separate command like `or` anyway.
3. Handle nits.

Make sure to submit clean PRs for both s-v and suricata. It'll make easier for us to review. Thanks!

2023-12-12 06:29 UTC, inashivb commented on src/detect-engine-analyzer.c
> +                    /* noalert has been removed and never gets to DumpMatches */
we haven't like removed anything. It just wasn't supposed to be here so we can remove this comment, I think.

2023-12-12 06:29 UTC, inashivb commented on src/detect-engine-analyzer.c
> +                if (is_or == true) {
nit: this could just be `if (is_or)`

2023-12-13 11:30 UTC, hadiqaalamdar commented
New PR: https://github.com/OISF/suricata/pull/10044

2023-12-13 11:30 UTC, closed without merging