rust/sip: register parser for tcp v12
OISF/suricata pull request #10037
Opened 2023-12-12 17:34 UTC by glongo

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3351

Describe changes:
- Rebase

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=pr/1510
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-12-12 19:36 UTC, glongo commented
I've just set the correct `SV_BRANCH`, please restart the checks if possible.

2023-12-12 20:40 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 181 | 195 | 107.73% | 

Pipeline 17018

2023-12-12 21:50 UTC, ct0br0 commented
Re-ran TLPW2, uptime sometimes matches baseline and other times is a bit up.

2023-12-13 21:03 UTC, catenacyber commented on rust/src/sip/sip.rs
> +            SIPFrameType::Pdu as u8,
This frame does not look right :
A TCP sent here may have 0 or multiple SIP PDUs

This should be done after `sip_parse_request` returned `Ok`

Cf https://github.com/OISF/suricata/pull/10048 (MQTT current implementation is wrong)

2023-12-14 08:31 UTC, catenacyber requested changes
Frames on tcp should support multiple PDUs in one call to `parse_request_tcp` (same for response)

2023-12-14 20:28 UTC, glongo commented
New PR: https://github.com/OISF/suricata/pull/10058

2023-12-14 20:28 UTC, closed without merging