pgsq: add cancel request msg - v4
OISF/suricata pull request #10039
Opened 2023-12-12 21:17 UTC by jufajardini

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6577

Previous PR: https://github.com/OISF/suricata/pull/10036

Describe changes:
- indicate in the documentation how to correlate the data seen in the `CancelRequest` message with the correct flow
- add `AuthenticationOk` example to the documentation, as that's where `secret_key` and `process_id` are seen - for correlation
- add references to PostgreSQL documentation about canceling and `BackendKeyData` message format
- logger: change eve fields to be the same seen in `AuthenticationOk` message

Provide values to any of the below to override the defaults.
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1539

2023-12-13 06:25 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 17025

2023-12-13 18:03 UTC, victorjulien approved these changes

2023-12-14 08:07 UTC, victorjulien requested changes
needs a rebase

2023-12-14 12:50 UTC, jufajardini commented
Rebased: https://github.com/OISF/suricata/pull/10054

2023-12-14 12:50 UTC, closed without merging