ssl: detect duplicate client handshake
OISF/suricata pull request #10059
Opened 2023-12-14 21:15 UTC by regit

Some invalid implementation of TLS have been seen where the client is sending two handshake messages at start. The result was a problem of JA3 generation.

As it is invalid if we follow the RFC, let's ignore the second message.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6634

Describe changes:
- handle the case where 2 hello message are sent by client

2023-12-14 21:52 UTC, catenacyber commented
Is there a SV test ?

2023-12-15 05:50 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 17098

2023-12-15 06:13 UTC, victorjulien commented on src/app-layer-ssl.c
> +                if (ssl_state->client_connp.ja3_str) {
why is the ja3 stuff freed here?

2024-01-19 11:51 UTC, victorjulien requested changes
see inline comments/requests

Please also add the ticket number to the commit.

2024-04-21 23:25 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 17098

2024-05-07 20:33 UTC, victorjulien commented
Is the PCAP in https://redmine.openinfosecfoundation.org/issues/7016 useful for a test @regit ?

2024-06-20 07:11 UTC, victorjulien commented
@regit are you planning to revisit this soon?

2024-09-03 13:36 UTC, catenacyber commented
My analysis on this :

the PCAP in https://redmine.openinfosecfoundation.org/issues/7016 may be useful because it has indeed 2 client hellos (cf `tls.handshake.type == 1`) but in this case, this is not a faulty SSL implementation : the server sends a Hello Retry Request, and the client sends again its client hello... So, not so sure we should have an event for such legit usages

> As it is invalid if we follow the RFC, let's ignore the second message.

I did not find any mentions of this ja3 RFC for multiple hellos...

The ja3 hash should be safe already thanks to the check `ssl_state->curr_connp->ja3_hash == NULL` : we generate the hash only once after the first TLS hello extensions

2024-09-03 14:08 UTC, catenacyber commented
New solution in https://github.com/OISF/suricata/pull/11710

2024-09-03 14:08 UTC, closed without merging