Backport: endace: Fix source-dag timestamps
OISF/suricata pull request #10092
Opened 2023-12-22 15:45 UTC by jlucovsky

Bug: #6618.

Fix Endace ERF to SCTime_t timestamp conversion

Fix typo preventing compilation with --enable-dag

(cherry picked from commit 879db3dbc3e93912c784375c85d88404a9371f31)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6620](https://redmine.openinfosecfoundation.org/issues/6620)

Describe changes:
-
-
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-12-22 19:15 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 17181

2024-01-02 07:52 UTC, victorjulien commented
@sfd can you review and test this?

2024-01-08 03:57 UTC, sfd commented
> @sfd can you review and test this?

Code looks good.

Build succeeds with --enable-dag, but generates the following warnings:

```
  CC       source-erf-dag.o
source-erf-dag.c: In function ‘TmModuleReceiveErfDagRegister’:
source-erf-dag.c:136:47: warning: assignment to ‘TmEcode (*)(ThreadVars *, const void *, void **)’ {aka ‘TmEcode (*)(struct ThreadVars_ *, const void *, void **)’} from incompatible pointer type ‘TmEcode (*)(ThreadVars *, void *, void **)’ {aka ‘TmEcode (*)(struct ThreadVars_ *, void *, void **)’} [-Wincompatible-pointer-types]
  136 |     tmm_modules[TMM_RECEIVEERFDAG].ThreadInit = ReceiveErfDagThreadInit;
      |                                               ^
source-erf-dag.c: In function ‘TmModuleDecodeErfDagRegister’:
source-erf-dag.c:154:46: warning: assignment to ‘TmEcode (*)(ThreadVars *, const void *, void **)’ {aka ‘TmEcode (*)(struct ThreadVars_ *, const void *, void **)’} from incompatible pointer type ‘TmEcode (*)(ThreadVars *, void *, void **)’ {aka ‘TmEcode (*)(struct ThreadVars_ *, void *, void **)’} [-Wincompatible-pointer-types]
  154 |     tmm_modules[TMM_DECODEERFDAG].ThreadInit = DecodeErfDagThreadInit;
      |                                              ^
```

Looks like a prototype const changed?

2024-01-09 11:53 UTC, victorjulien requested changes
I think its better if @sfd takes this, as we have no means to (build) test this.

2024-01-14 14:51 UTC, jlucovsky commented
Closed; continued by @sfd in #10148

2024-01-14 14:51 UTC, closed without merging