dns: add dns.rcode keyword v2
OISF/suricata pull request #10097
Opened 2023-12-26 10:38 UTC by hadiqaalamdar

Feature #6621

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6621) ticket: https://redmine.openinfosecfoundation.org/issues/6621

Describe changes:
- added the dns.rcode field
- made the suggested changes from previous PR
- successfully ran the `cargo clippy --all-features` command as recommended.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1567

2023-12-28 08:40 UTC, inashivb reviewed
Good work, Hadiqa!
Are you able to see s-v failures locally too?

2023-12-29 10:26 UTC, hadiqaalamdar commented
> Good work, Hadiqa! Are you able to see s-v failures locally too?

yes, so the SV tests for rcode seem to all be failing.

2024-01-01 05:31 UTC, inashivb commented
> yes, so the SV tests for rcode seem to all be failing.

I see. Do you need help with that? Could you please share if you have an idea why it might be happening?

2024-01-02 17:39 UTC, jufajardini requested changes
As Shivani has indicated, could you go over the CI failures and share with us if you have an idea of why are the tests failing?

I've also left a review on the SV PR that may add insights on this.

For this PR, for now, just some nit comments inline.

2024-01-02 17:39 UTC, jufajardini commented on src/detect-dns-rcode.c
> +    sigmatch_table[DETECT_AL_DNS_RCODE].url = "/rules/dns-keywords.html#dns-rcode";
Nit: once the code-related changes are done, we'll need to populate the documentation section mentioned in this line ;)

2024-01-02 17:39 UTC, jufajardini commented on src/detect-dns-rcode.h
> +/* Copyright (C) 2019 Open Information Security Foundation
Nit: year 2024

2024-01-02 17:39 UTC, jufajardini commented on src/detect-dns-rcode.c
> +/* Copyright (C) 2023 Open Information Security Foundation
Nit year 2024, now :P

2024-01-03 08:45 UTC, hadiqaalamdar commented
> As Shivani has indicated, could you go over the CI failures and share with us if you have an idea of why are the tests failing?
> 
> I've also left a review on the SV PR that may add insights on this.
> 
> For this PR, for now, just some nit comments inline.

I don't really know why the failures are happening. I didn't see any errors when I ran the code locally. I'll create a new PR and see if the continue to happen.

2024-01-03 12:40 UTC, jufajardini commented
> > As Shivani has indicated, could you go over the CI failures and share with us if you have an idea of why are the tests failing?
> > I've also left a review on the SV PR that may add insights on this.
> > For this PR, for now, just some nit comments inline.
> 
> I don't really know why the failures are happening. I didn't see any errors when I ran the code locally. I'll create a new PR and see if the continue to happen.

Can you run the suricata verify tests locally and see what is the output in the eve.json logs? If the checks are failing, comparing what is on the checks with what the logs actually looks like is one of the first things I do, if there are no errors, to debug a failing test.

2024-01-05 10:54 UTC, hadiqaalamdar commented
New PR: https://github.com/OISF/suricata/pull/10126

2024-01-05 10:54 UTC, closed without merging