mqtt: Improve handling of multiple PDU parsing
OISF/suricata pull request #10107
Opened 2024-01-03 14:30 UTC by jlucovsky

Issue: 6592

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6592](https://redmine.openinfosecfoundation.org/issues/6592)

Describe changes:
- Parse PDU instead of entire stream

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2024-01-03 15:10 UTC, catenacyber commented
Could you have a SV test ? Maybe adding `bsize` To the current mqtt-frames test ?

2024-01-03 17:00 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 17328

2024-01-18 10:39 UTC, catenacyber commented on rust/src/mqtt/mqtt.rs
> +                        current.len() as i64,
This should not be `current.len()` as current may hold multiple PDUs, but rather `start.len() - rem.len()`

2024-01-18 10:39 UTC, catenacyber requested changes
CI needs to be green as well

2024-01-24 15:32 UTC, closed without merging