Clippy fixes v2
OISF/suricata pull request #10124
Opened 2024-01-05 09:33 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None 

Describe changes:
- rust: fix clippy warnings in tests

@jasonish why do I get these and CI is not red ?
Is this because the lint level to deny warnings does not apply to test code ?

#10113 rebased and more commits
Only 19 match_single_binding warnings remaining

2024-01-05 17:09 UTC, jasonish commented on rust/src/tftp/tftp.rs
>          }
In tests I prefer:
```
        let txp = parse_tftp_request(&READ_REQUEST[..]).unwrap();
        assert_eq!(tx, txp);
```

2024-01-05 17:10 UTC, jasonish commented on rust/src/detect/byte_math.rs
>          }
Again, could just unwrap.

2024-01-05 17:12 UTC, jasonish commented on rust/src/dcerpc/dcerpc_udp.rs
>          }
```
assert!(parser::parser_dcerpc_udp_header(request).is_err());
```

2024-01-05 17:13 UTC, jasonish requested changes
Happy to see this ints being fixed up, but I think we should opt for asserts and even unwraps/expects before conditional panics.

2024-01-06 02:40 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 17375

2024-01-06 20:43 UTC, catenacyber commented on rust/src/tftp/tftp.rs
>          }
nice

2024-01-06 20:48 UTC, catenacyber commented on rust/src/detect/byte_math.rs
>          }
indeed

2024-01-06 20:59 UTC, catenacyber commented on rust/src/dcerpc/dcerpc_udp.rs
>          }
yes

2024-01-06 21:20 UTC, catenacyber commented
Replaces by https://github.com/OISF/suricata/pull/10129, thanks Jason for the review

2024-01-06 21:20 UTC, closed without merging