Minor Streaming buffer cleanups/v1
OISF/suricata pull request #10161
Opened 2024-01-15 07:26 UTC by inashivb

2024-01-15 09:50 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 17510

2024-01-20 20:25 UTC, victorjulien commented on src/util-streaming-buffer.c
> +    if (SBB_RB_INSERT(&sb->sbb_tree, sbb) != NULL) {
This should only be called if the tree is empty. Can we fail in that case?

2024-01-22 08:19 UTC, inashivb commented on src/util-streaming-buffer.c
> +    if (SBB_RB_INSERT(&sb->sbb_tree, sbb) != NULL) {
Indeed. I misread it as per its other call sites. I can't think of a reason we'll fail then but that doesn't mean we can't. 😅  Do you recommend I remove this check?

2024-01-22 08:27 UTC, victorjulien commented on src/util-streaming-buffer.c
> +    if (SBB_RB_INSERT(&sb->sbb_tree, sbb) != NULL) {
Did you review the insertion macro? Pretty sure we can't fail in an empty tree. So in that case adding error code that will never trigger is actually harmful

2024-01-22 09:31 UTC, inashivb commented on src/util-streaming-buffer.c
> +    if (SBB_RB_INSERT(&sb->sbb_tree, sbb) != NULL) {
I see. Thank you. Will remove the checks.

2024-01-30 05:44 UTC, victorjulien requested changes
see older inline stuff

2024-01-30 05:48 UTC, closed without merging