dns: add dns.rcode keyword v5
OISF/suricata pull request #10203
Opened 2024-01-19 13:44 UTC by hadiqaalamdar

Feature #6621

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6621) ticket: https://redmine.openinfosecfoundation.org/issues/6621

Previous PR: https://github.com/OISF/suricata/pull/10150

Describe changes:
- modified the code to implement `DetectUintData<u8>` instead of simple u8
- SV tests are running successfully
- cherry-picked changes from https://github.com/OISF/suricata/pull/10142/commits/1fc18c11b95864a4cd7bd1c81866055460c4377d to the etc/schema.json file to fix the schema errors
- cherry-picked changes from this PR https://github.com/OISF/suricata/pull/10073 which modified opcode to  implement `DetectUintData<u8>`. This PR had code that I would have had to replicate, especially `uint.rs` file changes.
- Added documentation for rcode in `doc/userguide/rules/dns-keywords.rst` file.
- successfully ran the following tests:
- from rust dir: make check
- from rust dir: cargo test
- from rust dir: cargo clippy --all-features
- from rust dir: rustfmt src/dns/*
- from suricata dir: ./scripts/clang-format.sh check-branch
- from suricata dir: ./scripts/clang-format.sh branch
- from suricata dir running ./src/suricata -u showed that one unit test had failed. 
- from suricata dir running ./src/suricata -u -U dns showed 7 tests passed.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1578

2024-01-19 14:47 UTC, jlucovsky commented on doc/userguide/rules/dns-keywords.rst
> +----------
nit: make sure that the number of `-` characters matches that in the text above. In this case, there's one extra `-`

2024-01-19 14:47 UTC, jlucovsky commented on doc/userguide/rules/dns-keywords.rst
> +Match on DNS requests where the **rcode** is between 7 and 15, exclusively:
Are 7 and 15 included? If so, suggest "between 7 and 15, inclusively"; exclusive implies something differrent.

[7-15] -- inclusive
[7-15) -- exclusive (15 not included)

2024-01-19 17:16 UTC, jufajardini requested changes
Getting closer and closer to the finish line! :)

It's a bit difficult to check what changes were introduced by you due to the commit history at the moment, but tried to add some useful feedback inline. :)

2024-01-19 17:16 UTC, jufajardini commented on rust/src/dns/detect.rs
> +    tx: &mut DNSTransaction, detect: &mut DetectUintData<u8>, flags: u8,
Could you please add documentation for this function?

2024-01-19 17:16 UTC, jufajardini commented on rust/src/dns/detect.rs
> +    let rcode = (header_flags & 0xf) as u8;
Honest question: why do we need the bitmask for rcode?

2024-01-19 17:19 UTC, jufajardini commented
Jason's commit got merged, can be a good idea to have a new version rebased, to clean up the commit history a bit more :)

2024-01-20 20:59 UTC, catenacyber commented
I think you should remove the commit from https://github.com/OISF/suricata/pull/10073 from this PR. 

These are 2 independent changes, right ? (even if they are close to each other)

2024-01-20 21:04 UTC, catenacyber commented
> modified the code to implement DetectUintData<u8> instead of simple u8

Looks cool :-)

2024-01-22 10:58 UTC, hadiqaalamdar commented
> I think you should remove the commit from #10073 from this PR.
> 
> These are 2 independent changes, right ? (even if they are close to each other)
I had to copy some of the changes, e.g changes in uint.rs, file you made in #10073. Is it okay if I cherrypick the 2 commits from #10073 or do you think that I should copy them in my PR without cherrypicking?

2024-01-22 19:16 UTC, catenacyber commented
> I had to copy some of the changes, e.g changes in `uint.rs` file, you made in #10073.

I do not think you have to do that...
This PR should not change `uint.rs`

Why do you think you need this ?

>  Is it okay if I cherrypick the 2 commits from #10073 or do you think that I should copy them in my PR without cherrypicking and without changing the code for `opcode`?

I updated #10073 (there is a new PR)
But I think you can use `master` branch instead of this PR as a base for your work...

2024-01-24 12:21 UTC, hadiqaalamdar commented
New PR: https://github.com/OISF/suricata/pull/10233

2024-01-24 12:21 UTC, closed without merging