backports 6.0.x: doc: remove references to prehistoric versions v1
OISF/suricata pull request #10220
Opened 2024-01-22 16:20 UTC by lukashino

Remove references that are mentioning Suricata 3 or less 
As a note - only one Suricata 4 reference found:
(suricata-yaml.rst:"In 4.1.x")
Fast pattern selection criteria can be internally found by inspecting SupportFastPatternForSigMatchList and SigTableSetup functions.

Note: The difference in this branch is that there is one `#ifdef` clause that contains references to keywords such as `DETECT_SM_LIST_UMATCH`. However, it is permanently set to `false` so it is never used in the code unless the change is made in the code itself. 

Ticket: #6570
(cherry picked from commit 6e4cc79b398d91e243bd1574cbbcbbf7cd021c5d)

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6698

2024-01-23 08:21 UTC, catenacyber approved these changes
Looks like a clean cherry-pick to me

2024-01-23 13:50 UTC, victorjulien requested changes
see inline

2024-01-23 13:50 UTC, victorjulien commented on doc/userguide/configuration/suricata-yaml.rst
> +  i: suricata: This is Suricata version 7.0.2 RELEASE running in USER mode
this is not what 6.0.x will produce

2024-01-25 12:41 UTC, catenacyber commented
Ticket was rejected

2024-01-25 12:41 UTC, closed without merging