lua: Move to lua 5.4 and include by default v5
OISF/suricata pull request #10263
Opened 2024-01-26 19:12 UTC by J0eJ0h

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4776

Describe changes:

- Move to using lua 5.4
- Remove luajit support and --enable-luajit configure option
- Change --enable-lua option to --disable-lua and build with lua by default
- CI Fixes

https://github.com/OISF/suricata/pull/10255 with:

- All internal references to luajit removed.

2024-03-21 12:51 UTC, jlucovsky reviewed
This standardizes on lua5.4 -- I think that should be mentioned in the release notes or somewhere more appropriate.

2024-03-21 12:51 UTC, jlucovsky commented on .github/workflows/builds.yml
> +      - run: ./configure --with-gnu-ld --enable-fuzztargets --disable-shared  --enable-gccprotect
nit: extra whitespace after `--disable-shared`

2024-03-28 20:55 UTC, catenacyber requested changes
Setting the Github status as it needs a rebase, and there are comments to be taken care of

2024-04-10 22:36 UTC, jasonish commented
Continued at https://github.com/OISF/suricata/pull/10801.

2024-04-10 22:36 UTC, closed without merging