detect: errors on 65k filestore signatures
OISF/suricata pull request #10271
Opened 2024-01-29 15:14 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6393

Describe changes:
- detect: log error when too many filestores

#9997 with proposed fix in previous code review

2024-01-29 19:00 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 17827

2024-01-29 20:53 UTC, victorjulien requested changes

2024-01-29 20:53 UTC, victorjulien commented on src/detect-filestore.c
> +        SCLogError("Too many filestore signatures");
should show what the limit is

2024-01-30 14:35 UTC, catenacyber commented on src/detect-filestore.c
> +        SCLogError("Too many filestore signatures");
Right

2024-01-30 14:35 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/10281

2024-01-30 14:35 UTC, closed without merging