dns: add dns.rrtype keyword
OISF/suricata pull request #10289
Opened 2024-01-31 12:59 UTC by hadiqaalamdar

Feature #6666

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6666) ticket: https://redmine.openinfosecfoundation.org/issues/6666

Previous PR: 

Describe changes:
- added code for rrtype and implemented `DetectUintData<u16>`
- SV tests are running successfully
- Added documentation for rcode in `doc/userguide/rules/dns-keywords.rst` file.
- successfully ran the following tests:
- from rust dir: make check
- from rust dir: cargo test
- from rust dir: cargo clippy --all-features
- from rust dir: rustfmt src/dns/*
- from suricata dir: ./scripts/clang-format.sh check-branch
- from suricata dir: ./scripts/clang-format.sh branch
- from suricata dir running ./src/suricata -u showed that one unit test had failed. 
- from suricata dir running ./src/suricata -u -U dns showed 7 tests passed.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1625

2024-01-31 20:47 UTC, jufajardini requested changes
Good work!

Please see inline comments :)

For the commit message, could you move the ticket reference to the last line? This is more aligned with what we recommend and see, so it's easier for the eye to find that info if it's there :)

2024-01-31 20:47 UTC, jufajardini commented on rust/src/dns/detect.rs
> +    tx: &mut DNSTransaction, detect: &mut DetectUintData<u16>, rrtype: u16,
Seeing this failure: https://github.com/OISF/suricata/actions/runs/7726431734/job/21062732402?pr=10289#step:13:434

I think that this last parameter here should be `flags: u8`, as we see for opcode. The info for rrtype should be present in the `detect` param, from what I understand 🤔

2024-01-31 20:47 UTC, jufajardini commented on src/detect-dns-rrtype.c
> +static int DetectDnsRrtypeMatch(DetectEngineThreadCtx *det_ctx, Flow *f, uint16_t flags,
flags here has to be `uint8_t`, cf https://github.com/OISF/suricata/actions/runs/7726431734/job/21062732402?pr=10289#step:13:434 and https://github.com/OISF/suricata/blob/master/src/detect.h#L1260

2024-01-31 20:47 UTC, jufajardini commented on doc/userguide/rules/dns-keywords.rst
> +
Could you follow the style where you indicate that this is an integer keyword, and a reference to the integer keyword documentation that was recently merged? See example here: https://github.com/OISF/suricata/blob/master/doc/userguide/rules/dhcp-keywords.rst#dhcprebinding_time

2024-02-02 14:06 UTC, closed without merging

2024-02-02 14:06 UTC, hadiqaalamdar commented
New PR: https://github.com/OISF/suricata/pull/10306