config: Remove NSS vestiges
OISF/suricata pull request #10310
Opened 2024-02-04 14:20 UTC by jlucovsky

Continuation of #10290 

Remove NSS vestiges from CI and doc.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6712](https://redmine.openinfosecfoundation.org/issues/6712)

Describe changes:
- Remove NSS from doc and CI pipelines
- Remove duplicate libjansson package from CI

Updates
- remove libnspr

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2024-02-05 19:32 UTC, jasonish approved these changes

2024-02-07 05:08 UTC, victorjulien commented on qa/valgrind.suppress
> -   fun:__nss_lookup_function
I think we need to remove this whole block. Valgrind suppressions are for suppressing valgrind warnings.

2024-02-07 05:08 UTC, victorjulien requested changes
valgrind.suppress needs a further update

2024-02-08 15:41 UTC, jlucovsky commented on qa/valgrind.suppress
> -   fun:__nss_lookup_function
@victorjulien why the entire block that used to contain `__nss_lookup_function`? Are the remaining suppressions no longer valid?

2024-02-09 09:17 UTC, victorjulien commented on qa/valgrind.suppress
> -   fun:__nss_lookup_function
it's a callstack, so we can't just remove one line from it

2024-02-10 13:52 UTC, jlucovsky commented
> For the record, rust/src/ffi/hashing.rs and src/util-file.h still have one mention of nss

I'd like to leave those comments for historical purposes.

2024-02-10 14:01 UTC, jlucovsky commented
Continued in #10356

2024-02-10 14:01 UTC, closed without merging