doc: 3025 http keyword updates v3
OISF/suricata pull request #10329
Opened 2024-02-07 14:41 UTC by jmtaylor90

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3025

Describe changes:
- applied feedback from #10101 
- updated all http keywords documentation
- RTD build of branch - https://rtd-test-suricata.readthedocs.io/en/latest/rules/http-keywords.html

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2024-02-07 14:53 UTC, ozuriexv reviewed
I think it'd be beneficial to add a reference to 'HTTP Primer' explaining what 'sticky buffers' are.  It seems to be explained briefly in '[8.1.6.1 - Modifier Keywords](https://rtd-test-suricata.readthedocs.io/en/latest/rules/intro.html#modifier-keywords)'.

2024-02-08 20:21 UTC, jmtaylor90 commented
> I think it'd be beneficial to add a reference to 'HTTP Primer' explaining what 'sticky buffers' are. It seems to be explained briefly in '[8.1.6.1 - Modifier Keywords](https://rtd-test-suricata.readthedocs.io/en/latest/rules/intro.html#modifier-keywords)'.

will add in next PR

2024-02-14 19:34 UTC, zoomequipd commented on doc/userguide/rules/http-keywords.rst
>  http.stat_msg
Is there any chance we can get a note that reflects the behavior of http.stat_msg on HTTP/2 traffic. 

https://redmine.openinfosecfoundation.org/issues/4067#note-37
```
Philippe Antoine wrote in [#note-37](https://redmine.openinfosecfoundation.org/issues/4067#note-37):
>
>The empty buffer is http_stat_msg for HTTP2
```

Commit creating the constant empty buffer: 
https://github.com/OISF/suricata/commit/22fb385e23991f0a7e3b83aeb2693d8ab21bdf41

2024-02-14 21:50 UTC, jufajardini requested changes
This was massive, thanks for this undertaking!

Left mostly nit comments for typos and the likes., not very confident to review HTTP workings or rule keyword details...

I wonder if something can be done about the sections that have several notes, as I worry that the sheer amount may render some less visible.

Haven't reviewed changes per commit, so no comments on commit separation logic from me.

Thanks once again for this!

2024-02-14 21:50 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> --  Corresponding PCRE modifier: ``Q``
Is it ok to remove this note?

2024-02-14 21:50 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +(see :ref:`http.host`)
The way this is worded for `http.header.raw` is somewhat easier to follow and understand. Do they mean the same?

2024-02-14 21:50 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +To detect if a http2 header name contains a ":" (colon), the keyword
nit:
```suggestion
To detect if an HTTP2 header name contains a ":" (colon), the keyword
```

2024-02-14 21:50 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +of a HTTP1 or HTTP2 request.
nit:
```suggestion
of an HTTP1 or HTTP2 request.
```

2024-02-14 21:50 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +To detect if a http2 header name contains a ":" (colon), the keyword
nit:
```suggestion
To detect if an HTTP2 header name contains a ":" (colon), the keyword
```

2024-02-14 21:50 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +The body of a HTTP responses can be very large, therefore the response body is
nit:
```suggestion
The body of HTTP responses can be very large, therefore the response body is
```

2024-02-14 21:50 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +  it can be decompressed and ``file.data`` can match on the decompress data.
nit: decompressed?

2024-02-14 21:50 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +.. note:: If a HTTP body is using gzip or deflate, ``file.data`` will match on
nit:
```suggestion
.. note:: If an HTTP body is using gzip or deflate, ``file.data`` will match on
```

2024-02-15 21:22 UTC, jmtaylor90 commented on doc/userguide/rules/http-keywords.rst
> + * :ref:`http.cookie`
Indeed, will update in next PR

2024-02-15 21:23 UTC, jmtaylor90 commented on doc/userguide/rules/http-keywords.rst
> +  `<https://www.rfc-editor.org/rfc/rfc2616.html#section-4.2>`_
Yes, I didn't want to hide the external link in this case

2024-02-15 21:24 UTC, jmtaylor90 commented on doc/userguide/rules/http-keywords.rst
> +Would be normalized to :example-rule-emphasis:`Mozilla/5.0\r\n`
No, will correct that in the next PR

2024-02-15 21:28 UTC, jmtaylor90 commented
> This was massive, thanks for this undertaking!
> 
> Left mostly nit comments for typos and the likes., not very confident to review HTTP workings or rule keyword details...
> 
> I wonder if something can be done about the sections that have several notes, as I worry that the sheer amount may render some less visible.

Indeed, some of the keywords just have a number of details that are important. Without making the document a wall of text, I figured using the note:: option at least broke up the content a little  but am open to suggestions on that

> Once wondering if we could reorganize the keyword order alphabetically, or semantically, somehow (might be a separate task, if agreed upon).

I was wondering about ordering as well, I would be open to adding to this PR once decided on the ordering method.

> Haven't reviewed changes per commit, so no comments on commit separation logic from me.
> 
> Thanks once again for this!

2024-02-19 14:43 UTC, jufajardini commented
> > This was massive, thanks for this undertaking!
> > Left mostly nit comments for typos and the likes., not very confident to review HTTP workings or rule keyword details...
> > I wonder if something can be done about the sections that have several notes, as I worry that the sheer amount may render some less visible.
> 
> Indeed, some of the keywords just have a number of details that are important. Without making the document a wall of text, I figured using the note:: option at least broke up the content a little but am open to suggestions on that
> 

Unfortunately, no suggestions, for now, might be the easiest solution, indeed.

> > Once wondering if we could reorganize the keyword order alphabetically, or semantically, somehow (might be a separate task, if agreed upon).
> 
> I was wondering about ordering as well, I would be open to adding to this PR once decided on the ordering method.
> 

As a user, what ordering would make more sense to you? Or just alphabetically would be fine, as at least it's easier to know what should come next?

2024-02-29 22:33 UTC, jmtaylor90 commented
> > > This was massive, thanks for this undertaking!
> > > Left mostly nit comments for typos and the likes., not very confident to review HTTP workings or rule keyword details...
> > > I wonder if something can be done about the sections that have several notes, as I worry that the sheer amount may render some less visible.
> > 
> > 
> > Indeed, some of the keywords just have a number of details that are important. Without making the document a wall of text, I figured using the note:: option at least broke up the content a little but am open to suggestions on that
> 
> Unfortunately, no suggestions, for now, might be the easiest solution, indeed.
> 
> > > Once wondering if we could reorganize the keyword order alphabetically, or semantically, somehow (might be a separate task, if agreed upon).
> > 
> > 
> > I was wondering about ordering as well, I would be open to adding to this PR once decided on the ordering method.
> 
> As a user, what ordering would make more sense to you? Or just alphabetically would be fine, as at least it's easier to know what should come next?

I will have a new PR next week with the alphabetical ordering and the changes suggested so far. Thanks!

2024-03-07 21:54 UTC, jmtaylor90 commented on doc/userguide/rules/http-keywords.rst
> +  to performance than using the :ref:`http.header` buffer (~10% better).
I am not sure but if we don't it's probably worth removing that performance note.

2024-03-07 22:21 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +  to performance than using the :ref:`http.header` buffer (~10% better).
Aha, it comes from this: https://blog.inliniac.net/2012/07/09/suricata-http_user_agent-vs-http_header/

2024-03-07 22:32 UTC, jmtaylor90 commented on doc/userguide/rules/http-keywords.rst
> +  to performance than using the :ref:`http.header` buffer (~10% better).
Do we think that is still accurate enough to mention the performance difference?

2024-03-07 22:46 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +  to performance than using the :ref:`http.header` buffer (~10% better).
Checked with the rest of the team

2024-03-07 23:26 UTC, jmtaylor90 commented on doc/userguide/rules/http-keywords.rst
> +  to performance than using the :ref:`http.header` buffer (~10% better).
what was the verdict? Keep it in or ?

2024-03-08 16:30 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +  to performance than using the :ref:`http.header` buffer (~10% better).
So, according to Victor: It's inspecting less data, so it should be faster. But it's a bit less clear by how much.
Maybe we could add that as it inspects data, it is faster? Do you think that'd work?

2024-03-08 21:08 UTC, jmtaylor90 commented on doc/userguide/rules/http-keywords.rst
> +  to performance than using the :ref:`http.header` buffer (~10% better).
Sounds good, will rework it. Thanks!

2024-03-08 22:13 UTC, jmtaylor90 commented
continued in https://github.com/OISF/suricata/pull/10599

2024-03-08 22:13 UTC, closed without merging