dpdk: add warning in configuration phase and minor DPDK refactoring v1
OISF/suricata pull request #10387
Opened 2024-02-12 20:29 UTC by lukashino

Redmine ticket: 
https://redmine.openinfosecfoundation.org/issues/6739

Describe changes:
- SCEnters added
- refactor code to smaller functions
- rewrite log message to be more consistent
- add a user warning n the change of RX/TX descriptors - on changes caused by the NIC adjustment

2024-02-13 03:20 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 101 | 111 | 109.9% | 

Pipeline 18389

2024-02-13 10:40 UTC, victorjulien commented on src/runmode-dpdk.c
> +            FatalError("EAL cleanup failed (err: %s)", strerror(-retval));
I don't see this as an improvement. The old scheme is as clear, while being less verbose. Would rather unify on that. This also matches use of `strerror(errno)` elsewhere in the code

2024-02-13 10:40 UTC, victorjulien commented on src/runmode-dpdk.c
> +            FatalError("EAL cleanup failed (err: %s)", strerror(-retval));
same for the rest of the PR

2024-02-13 10:40 UTC, victorjulien requested changes
not agreeing with the output changes

2024-02-16 21:00 UTC, lukashino commented
continues in #10449

2024-02-16 21:00 UTC, closed without merging