dns: add dns.rrtype keyword v6
OISF/suricata pull request #10459
Opened 2024-02-19 14:03 UTC by hadiqaalamdar

Feature #6666

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6666) ticket: https://redmine.openinfosecfoundation.org/issues/6666

Previous PR: https:https://github.com/OISF/suricata/pull/10435

Describe changes:
- rebased with master
- renamed the unit test for rrtype in `detect.rs` file.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1655

2024-02-20 06:17 UTC, inashivb requested changes
Looking pretty good. :)
Just some nits inline.

2024-02-20 06:17 UTC, inashivb commented on rust/src/dns/detect.rs
> +        }
unnecessary else block?

2024-02-20 06:17 UTC, inashivb commented on rust/src/dns/detect.rs
> +    };
unnecessary else blocks?

2024-02-21 11:21 UTC, hadiqaalamdar commented
New PR: https://github.com/OISF/suricata/pull/10481

2024-02-21 11:21 UTC, closed without merging