Decode ppoe pointer arithmetic 6787 v3
OISF/suricata pull request #10463
Opened 2024-02-19 15:13 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6787

Describe changes:
- decode/pppoe: fix pointer arithmetic, and do in only in debug mode because it is useless otherwise

#10461 with compilation warning fixed by taking more code into the #ifdef DEBUG section

2024-02-19 18:05 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 101 | 111 | 109.9% | 

Pipeline 18631

2024-03-09 06:50 UTC, victorjulien requested changes

2024-03-09 06:50 UTC, victorjulien commented on src/decode-pppoe.c
> +    while (pkt_pppoedt < pkt_pppoedt + (len - sizeof(PPPOEDiscoveryTag)) && pppoe_length >= 4 &&
can this be rewritten to be more readable? Both this and the original code are basically unreadable IMHO

2024-03-11 15:02 UTC, catenacyber commented
Continued in https://github.com/OISF/suricata/pull/10615

2024-03-11 15:02 UTC, closed without merging