doc: Describe noalert keyword
OISF/suricata pull request #10596
Opened 2024-03-08 13:20 UTC by jlucovsky

Continuation of #10586 

Issue: 6685

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6685](https://redmine.openinfosecfoundation.org/issues/6685)

Describe changes:
- Document `noalert` keyword.

Update:
- Address review comments

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2024-03-08 17:09 UTC, jufajardini approved these changes
Looks good to me!
For future reference, if you want, we have a `example-rule` container element that allows to highlight specific portions of the rule and a bit more, if needed: https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html#rule-examples

2024-03-09 06:22 UTC, victorjulien requested changes

2024-03-09 13:46 UTC, jlucovsky commented
> Looks good to me! For future reference, if you want, we have a `example-rule` container element that allows to highlight specific portions of the rule and a bit more, if needed: https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html#rule-examples

Thanks -- I wasn't aware and will make an update with these.

2024-03-09 14:06 UTC, jlucovsky commented
Continued in #10606

2024-03-09 14:06 UTC, closed without merging