doc: 3025 http keyword updates v4
OISF/suricata pull request #10599
Opened 2024-03-08 22:12 UTC by jmtaylor90

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3025

Describe changes:
- applied feedback from https://github.com/OISF/suricata/pull/10329
- updated all http keywords documentation
- RTD build of branch https://rtd-test-suricata.readthedocs.io/en/latest/rules/http-keywords.html

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2024-03-27 22:19 UTC, jufajardini requested changes
Hi there, just reviewed this comparing to comments from the previous PR, and resolved all comments by me that seemed to have been addressed. Seems that we're mostly done! 🎉  💪🏽 
I think the other requests were also tackled.
I've left inline comments for missed typos and for a possible note to be added about PCRE modifiers.

Commit separation was rather strict! Maybe they could have been squashed as per change type (removal / reordering etc), but from my part I don't think it's necessary to change that, now. Dunno if others would have a comment on this.

I've noticed that the keywords reordering was done based on alphabetical + if the keyword is applied to request/ response or both. Seems to work for me, too.

Please let us know if there is anything in particular that was not checked and you want to ensure that was reviewed!

(thanks for this work, as usual! :) )

2024-03-27 22:19 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
I've noticed that the notes about corresponding PCRE modifiers were removed. Was wondering if adding just one mention to that, maybe in this section, pointing to Suricata's modifiers (https://docs.suricata.io/en/latest/rules/payload-keywords.html#suricata-s-modifiers)  would be a good idea?

2024-03-27 22:19 UTC, jufajardini commented on doc/userguide/rules/http-keywords.rst
> +in an HTTP request or response. This is useful for checking for a headers
nit: 
```suggestion
in an HTTP request or response. This is useful for checking for a header's
```

2024-03-28 21:36 UTC, jmtaylor90 commented
continued in https://github.com/OISF/suricata/pull/10735

2024-03-28 21:36 UTC, closed without merging