Bug/6790 add worker sync on finish v3
OISF/suricata pull request #10628
Opened 2024-03-13 08:43 UTC by lukashino

Follow-up of: https://github.com/OISF/suricata/pull/10564
Ticket: #6790
https://redmine.openinfosecfoundation.org/issues/6790

Describe changes:
v3
- refactored the receive loop

v2
- added a pointer check after calloc operation
- improved the reasoning in the commit message

v1
- worker synchronization added before the port is closed
- in the peered modes, the thread only closes the peered port - it cannot close its own port because it might still be used by the other peered threads

2024-03-13 09:35 UTC, victorjulien commented on src/runmode-dpdk.c
>      SC_ATOMIC_RESET(iconf->inconsitent_numa_cnt);
unrelated to the PR, but noting it now: typo should be "inconsistent"

2024-03-13 09:41 UTC, victorjulien commented on src/source-dpdk.c
> +            if (!PacketInitFromMbuf(ptv, ptv->received_mbufs[i], &p)) {
can we just refactor this to
```c
Packet *p = PacketInitFromMbuf(ptv, ptv->received_mbufs[i]);
if (p == NULL)
    continue;
```

2024-03-13 09:43 UTC, victorjulien commented on src/source-dpdk.c
> +    if (!rte_pktmbuf_is_contiguous(mbuf) && !segmented_mbufs_warned) {
how expensive is `rte_pktmbuf_is_contiguous`? May be cheaper to check `segmented_mbufs_warned` first?

2024-03-13 09:43 UTC, victorjulien commented on src/source-dpdk.c
> +static void DPDKSegmentedMbufWarning(struct rte_mbuf *mbuf)
inline? Runs for each pkt I think

2024-03-13 09:43 UTC, victorjulien commented on src/source-dpdk.c
> +static bool PacketInitFromMbuf(DPDKThreadVars *ptv, struct rte_mbuf *mbuf, Packet **pkt_out)
inline?

2024-03-13 09:45 UTC, victorjulien requested changes
Looks good overall, a few comments inline

2024-03-14 12:39 UTC, lukashino commented
I inlined your comments, let's continue in https://github.com/OISF/suricata/pull/10642

2024-03-14 12:39 UTC, closed without merging