detect/transform: from_base64 transform
OISF/suricata pull request #10651
Opened 2024-03-15 12:03 UTC by jlucovsky

Continuation of #10561 

This PR provides the `from_base64` transform used to match on content decoded with base64 using the mode (default rfc4648).

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6487](https://redmine.openinfosecfoundation.org/issues/6487)

Describe changes:
- New transform: `from_base64`
- Documentation
- Keyword parser in rust.

Updates:
- Address review comments, including adding the `SC` prefix for some items exported to C

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=pr/1670
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2024-03-15 12:38 UTC, catenacyber commented on rust/src/detect/transform_base64.rs
> +    ModeRelax = 0,
Could this replace the `Base64Mode` ? So that we do not confuse

2024-03-15 19:05 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 19376

2024-03-21 13:31 UTC, catenacyber requested changes
Could you rebase to get green CI ? And see also my other comment...

2024-03-21 14:36 UTC, jlucovsky commented
Continued in #10689

2024-03-21 14:36 UTC, closed without merging