profiling/rules: Clear profiling flag at end
OISF/suricata pull request #10653
Opened 2024-03-16 13:05 UTC by jlucovsky

Issue: 6861

When profiling ends, clear the per-packet profiling flag to prevent future profiling processing on the packet *unless it was enabled* again for that packet.

With lightweight rule profiling, it's possible to perform profiling end-time processing if profiling was active in the past but since has been disabled.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6861](https://redmine.openinfosecfoundation.org/issues/6861)

Describe changes:
- Clear per-packet profiling flag when profiling ends. It'll be reset if the packet is selected for profiling in the future.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2024-03-16 16:20 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 19538

2024-03-18 08:27 UTC, victorjulien commented
I find the explanation a bit incomplete. I had to study the code to understand the issue. Can you expand the explanation esp with a step by step explanation of the "state" of things while starting profile, it getting disabled, finishing profiling?

Wrt unsetting the flag, can we not just use the logic what we use for keywords?
```c
if (profiling_keyword_enabled && profiling_keyword_entered) {
```

2024-03-18 08:27 UTC, victorjulien requested changes
see inline

2024-03-18 08:31 UTC, victorjulien commented
wrt the explanation, I'm looking for a explanation like what I did in 7956fa52423f80858643b25080efba2f64d78512

2024-03-18 13:05 UTC, jlucovsky commented
> I find the explanation a bit incomplete. I had to study the code to understand the issue. Can you expand the explanation esp with a step by step explanation of the "state" of things while starting profile, it getting disabled, finishing profiling?
> 
> Wrt unsetting the flag, can we not just use the logic what we use for keywords?
> 
> ```c
> if (profiling_keyword_enabled && profiling_keyword_entered) {
> ```

We could add `profiling_keyword_entered` to the `if`. Note that packets are marked with `PKT_PROFILE` on a sampled basis so it's quite possible that the current packet is not being profiled.

I'll update the PR with an expanded comment.

2024-03-19 14:05 UTC, jlucovsky commented
Continued in #10665

2024-03-19 14:05 UTC, closed without merging