imap: extend detection patterns - v4
OISF/suricata pull request #10661
Opened 2024-03-18 18:11 UTC by mmaatuq

Ticket: #2886

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/2886) ticket:2886

Describe changes:
- extend detection patterns for imap protocol as per [rfc9051](https://datatracker.ietf.org/doc/html/rfc9051)
- compared to this previous [PR](https://github.com/OISF/suricata/pull/10646)  comments on PR #10646 were incorporated 
- this is not comprehensive and might create more false positives, but i think this tradeoff is acceptable, and we can overcome these limitations when we add a complete parser. 

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1620

2024-03-21 13:50 UTC, catenacyber commented
Could you rebase https://github.com/OISF/suricata-verify/pull/1620 on top of latest SV master to get a greener CI ?

2024-03-21 14:29 UTC, mmaatuq commented
> Could you rebase [OISF/suricata-verify#1620](https://github.com/OISF/suricata-verify/pull/1620) on top of latest SV master to get a greener CI ?

Hey, I just did and updated SV_BRANCH tage.

2024-03-21 15:28 UTC, catenacyber commented
Looks like CI is red because unit tests are failing. Could you investigate why ?

2024-03-21 19:04 UTC, mmaatuq commented
> Looks like CI is red because unit tests are failing. Could you investigate why ?

here are my findings after a quick investigation: 
- log error message is  doesn't tell why it failed for example i can't know why such case failed,
` Test AppLayerTest10                                               : STREAM MEMORY IN USE 37888
STREAM REASSEMBLY MEMORY IN USE 116736
FAILED`
- looking at the test itself, I suspected that maybe some **FAIL_IF** expressions that involves **alproto**, **alproto_tc**, **alproto_ts**  could be the reason, commented such expressions but test still fail.
- by trail and error  i found that for this statement 
`    if (AppLayerProtoDetectPMRegisterPatternCI(IPPROTO_TCP, ALPROTO_IMAP, " CAPABILITY",
                31 /*20 for max tag len + space + len(CAPABILITY)*/, 0, STREAM_TOSERVER) < 0) {
        return -1;
    }

`
it fails if depth >= 18
and for depth <= 17 all tests pass. 

- any clue about such case? 
- as next I'll try to look closely at a test to check which  **FAIL_IF**   is responsible.

2024-03-21 20:16 UTC, catenacyber commented
Strange, wonder if https://github.com/OISF/suricata/pull/8892/commits/57ef16cab9c6873c913b7386879566f03472295a could fix it...

2024-03-21 20:34 UTC, mmaatuq commented
> Strange, wonder if [57ef16c](https://github.com/OISF/suricata/commit/57ef16cab9c6873c913b7386879566f03472295a) could fix it...

I applied it, but unfortunately it didn't.

2024-03-21 21:32 UTC, catenacyber commented
The problem seems to lie in the tests using 17 bytes, and expecting pattern matching detection to be done...

2024-03-27 16:16 UTC, jasonish requested changes
Unit tests must pass.

2024-03-27 16:39 UTC, mmaatuq commented
> Unit tests must pass.

The used depth "31" is because we assumed that tag could be at maximum "20" chars which is not officially documented,  so how bad is it to suggest keep depth "17" which will make unit tests  pass and might miss some detections.

2024-03-31 07:33 UTC, closed without merging