doc: update eBPF/compilation instructions v4
OISF/suricata pull request #10788
Opened 2024-04-09 07:24 UTC by lukashino

Follow-up of #10614 

Link to Redmine tickets:
- https://redmine.openinfosecfoundation.org/issues/6599
- https://redmine.openinfosecfoundation.org/issues/6686

Describe changes:
v4
- inlined and shortened PATH variable edits in the Rust section
- can *be* cloned - be added

v3 
- updates to the docs per Jeff's suggestions
- removed the instruction to install i386 headers for the eBPF 

v2
- remove recommended configure parameters

v1
- small edit in eBPF instructions to prefer libbpf-dev package to the cloning&compilation
- porting changes from the improved version of installation instructions that got merged into master-6.0.x

2024-04-09 20:36 UTC, jufajardini approved these changes
Looks good to me!

Thanks for adding the changes per version, made it easier to know what to look at, too. :)

2024-04-11 05:00 UTC, victorjulien requested changes
some deps feedback. Not all new to this PR, but lets fix it anyway.

2024-04-11 06:48 UTC, victorjulien commented on doc/userguide/install.rst
> +    sudo apt-get install autoconf automake build-essential cargo cbindgen \
Do we have CI checks that exactly use these recommendations? I guess we could reverse the logic, and include the CI check commands here using `literalinclude` (see app-layer-frames.rst for an example)

2024-04-14 17:15 UTC, lukashino commented
Continues in https://github.com/OISF/suricata/pull/10840

2024-04-14 17:15 UTC, closed without merging