Feat/6927 add unit tests v2
OISF/suricata pull request #10838
Opened 2024-04-14 10:45 UTC by lukashino

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6927
Follow-up of: #10786 

Describe changes:
v2
- added a FatalError check on the number of LiveDevices
- changed #if HAVE_DPDK to #if defined(HAVE_DPDK) && defined(UNITTESTS)
- enabled unit tests in the Github workflow runs on Ubuntu and Fedora tasks

v1
- function-guarded variable
- fix the CPU exclude logic
- add DPDK unit tests

2024-04-14 13:05 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 20058

2024-04-17 13:22 UTC, catenacyber commented on src/util-device.c
> +    TAILQ_INIT(&pre_live_devices); // reset the list
Should it not be done in a separate "reset" function ?

Looks strange to see `SomeFuncFinalize` end with `INIT`

2024-04-17 13:27 UTC, catenacyber commented on src/util-affinity.h
> +int UnitTestsUtilAffinityVerifyCPURequirement(void);
Is this function used outside of tests ?

2024-04-17 13:28 UTC, catenacyber commented on src/util-affinity.c
> +#if defined(UNITTESTS) && !defined __CYGWIN__ && !defined OS_WIN32 && !defined __OpenBSD__ &&      \
Looks like this line should have only been changed in one commit

2024-04-17 17:03 UTC, catenacyber commented on src/util-affinity.h
> +int UnitTestsUtilAffinityVerifyCPURequirement(void);
> What do you imply? Ah, should it be guarded by #if defined UNIT_TEST?

Indeed, but trying to ask the question in a way that you found it yourself ;-)

2024-04-30 09:26 UTC, catenacyber requested changes
Needs at least a rebase

2024-06-08 05:24 UTC, victorjulien commented
On the next PR, please set a descriptive title.

2024-07-14 21:00 UTC, lukashino commented
Follow up in https://github.com/OISF/suricata/pull/11494

2024-07-14 21:00 UTC, closed without merging