datasets: fix parsing of ip4 in ip6
OISF/suricata pull request #10928
Opened 2024-04-21 18:42 UTC by regit

The lookup function was not taking into account that we can have an IPv4 or an IPv6 address as parameters and that this addresses need to be converted to Suricata internal storage. By using the already defined dedicated parsing function, we are fixing the issue.

Issue: #6969

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6969

Describe changes:
- Fix dataset lookup function

2024-04-21 21:05 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .memcap.pressure | 57 | 60 | 105.26% | 

Pipeline 20241

2024-04-23 13:28 UTC, victorjulien requested changes

2024-04-23 13:28 UTC, victorjulien commented on src/datasets.c
> +                SCLogWarning("Failing import");
this warning acts like an error here, it's also not providing any useful info. What is a user supposed to do when they see it?

2024-08-27 13:30 UTC, catenacyber commented
Continued in https://github.com/OISF/suricata/pull/11663

2024-08-27 13:30 UTC, closed without merging