pgsql/logger: open json object from logger fn - v1
OISF/suricata pull request #10951
Opened 2024-04-25 02:11 UTC by jufajardini

Before, the JsonBuilder object for the pgsql event was being created from the C-side function that actually called the Rust logger.

This resulted that if another module - such as the Json Alert called the PGSQL logger, we wouldn't have the `pgsql` key present in the log output
- only its inner fields.

Bug #6983

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6983

Describe changes:
- open pgsql json object from rust's pgsql's logger function, instead of from the C-side

### Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1796

2024-04-25 04:45 UTC, victorjulien requested changes

2024-04-25 04:45 UTC, victorjulien commented on rust/src/pgsql/logger.rs
> +    js.close()?;
do we need another close before line 39?

2024-04-25 05:20 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 20337

2024-04-30 21:15 UTC, jufajardini commented
Replaced by: https://github.com/OISF/suricata/pull/10997

2024-04-30 21:15 UTC, closed without merging