protodetect: overwrite rflow flag detected by PM
OISF/suricata pull request #11100
Opened 2024-05-19 18:01 UTC by ilya-bakhtin

rflow flag initially detected by PM must be overwritten by the results from PP if alproto from PP is finally taken.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
- [ ] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues
      (if applicable)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
Currently, when rflow condition is initially detected by PM, and then alproto is updated by PP, the rflow is never reverted.
If alproto detected by PP is finally used then rflow detected by PP must be taken.

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1837
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-05-31 13:54 UTC, catenacyber commented
Thanks @ilya-bakhtin 

Could you please create a redmine ticket for this ?
I think a better fix may be to improve the DCERPC/UDP probing parser.
```
diff --git a/rust/src/dcerpc/dcerpc_udp.rs b/rust/src/dcerpc/dcerpc_udp.rs
index 2007c867bf..0b4b30e2bf 100644
--- a/rust/src/dcerpc/dcerpc_udp.rs
+++ b/rust/src/dcerpc/dcerpc_udp.rs
@@ -299,7 +299,8 @@ fn probe(input: &[u8]) -> (bool, bool) {
             let is_dcerpc = hdr.rpc_vers == 0x04 &&
                 (hdr.flags2 & 0xfc == 0) &&
                 (hdr.drep[0] & 0xee == 0) &&
-                (hdr.drep[1] <= 3);
+                (hdr.drep[1] <= 3) &&
+                (hdr.fragnum == 0);
             return (is_dcerpc, is_request);
         },
         Err(_) => (false, false),
```

This way, we would no longer need the so-descrobed `HACK` in `AppLayerProtoDetectGetProto`

2024-06-12 14:10 UTC, catenacyber requested changes
Needs a ticket, and also a response to the above question

2024-06-20 19:31 UTC, ilya-bakhtin commented
https://redmine.openinfosecfoundation.org/issues/7111

2024-06-20 19:46 UTC, ilya-bakhtin commented
Improving the DCERPC probing parser is a good idea.
After that, we can simplify logic in the applayer-detect-proto and remove dependency on ALPROTO_ in a module that normally must not use explicit alproto id numbers.
I'll be thinking about how to make changes less intrusive.

2024-06-21 07:58 UTC, catenacyber commented
Thanks Ilya, will wait for the next version

2024-07-26 14:46 UTC, catenacyber commented
Replaced by #11541

2024-07-26 14:46 UTC, closed without merging