util:radix-tree: Fix possible dereference of nullptr
OISF/suricata pull request #11164
Opened 2024-05-28 16:42 UTC by jtstrs

Fix possible dereference of nullptr in case of unsuccessful allocation of memory memory for tree nodes

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7049

Describe changes:
- Add check of node pointers after allocation of memory;
- If memory allocated successfully, behavior do not change;
- If allocation fail, release already allocated memory and exit from function;

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-05-29 04:08 UTC, inashivb commented on src/util-radix-tree.c
> +
nit: unnecessary line

2024-05-29 04:08 UTC, inashivb requested changes
Hi!
The changes look good to me. Could you please update your commit message to meet our contribution guidelines and resubmit? See: https://docs.suricata.io/en/latest/devguide/contributing/code-submission-process.html#commits
It's too long and does not specify subsystem or the ticket.

2024-05-29 05:14 UTC, jtstrs commented
@inashivb , sure, sorry for that, will update soon

2024-05-31 12:14 UTC, inashivb commented
> @inashivb , sure, sorry for that, will update soon

Hey! Thanks for the update. Sorry but it still misses the ticket.
1. The commit message could be improved in accordance with your PR subject and be `util/radix-tree: fix possible...`
2. For reference about what a commit message should look like, you can check your own last merged commit in the codebase. 😉 
3. We prefer new PRs for any changes made. If you could that, that'll be great! Thanks!

2024-05-31 18:03 UTC, closed without merging