LDAP protocol parser v3
OISF/suricata pull request #11163
Opened 2024-05-28 10:27 UTC by glongo

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues
      (if applicable)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/1199

Describe changes:
- Rebase of #11087 

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1860

2024-06-02 19:02 UTC, catenacyber commented
Thanks for this work Giuseppe.

Taking a step back, my big question is :
Are there detection keywords ? frames ? (frames may be cheap to add and powerful)

Could you add the redmine ticket number in a commit message ?
(@jasonish is not CI supposed to be red because of this missing ? )

Looks like there is some documentation to add...

2024-06-02 19:03 UTC, catenacyber requested changes
I did not re-look at the code, but this needs some more polishing :-)

2024-06-02 19:09 UTC, jasonish commented
> Thanks for this work Giuseppe.
> 
> 
> 
> Taking a step back, my big question is :
> 
> Are there detection keywords ? frames ? (frames may be cheap to add and powerful)
> 
> 
> 
> Could you add the redmine ticket number in a commit message ?
> 
> (@jasonish is not CI supposed to be red because of this missing ? )

There's no check for that.

2024-06-10 23:13 UTC, jasonish commented
When looking at a pcap with:
- bind
- search
- unbind

Suricata doesn't log in that order. Can we fix that?

2024-06-10 23:14 UTC, jasonish commented on rust/src/ldap/logger.rs
> +    js.set_string("message", &msg.diagnostic_message.0)?;
These 2 seem empty a lot. I wonder if we should only log them when there is data.

2024-06-10 23:23 UTC, jasonish commented
I find the logging very verbose, which on one hand is nice, but I'm going to guess if this is deployed on a network with LDAP, it might just lead to overload. 

Do we have any idea what kind of load this would generate on a network where LDAP is used?

Can we reduce the datapoints logged?

Taking a quick look at a PCAP I pulled from cloudshark:

```
  "ldap": {
    "request": {
      "message_id": 5,
      "operation": "search_request",
      "search_request": {
        "base_object": "cn=Users,dc=cloudshark-a,dc=example,dc=com",
        "scope": 2,
        "deref_alias": 0,
        "size_limit": 0,
        "time_limit": 0,
        "types_only": false,
        "attributes": [
          "objectClass",
          "name",
          "gidNumber",
          "objectGUID",
          "objectSID",
          "whenChanged",
          "uSNChanged",
          "groupType"
        ]
      },
      "controls": [
        {
          "control_type": "1.2.840.113556.1.4.319",
          "criticality": false,
          "control_value": "3006020203e80400"
        }
      ]
    },
    "responses": [
      {
        "operation": "search_result_done",
        "search_result_done": {
          "result_code": "success",
          "matched_dn": "",
          "message": ""
        },
        "controls": [
          {
            "control_type": "1.2.840.113556.1.4.319",
            "criticality": false,
            "control_value": "3084000000050201000400"
          }
        ]
      }
    ]
  }
```

I think we have to reason about:
- 1:1 parity with keywords. Thats a lot right there, and that's just one message type
- What could be eliminated? Is our goal to provide as much context as Wireshark? Or should going to PCAP still be the way to get full fidelity.

What I'm getting at is this could be a lot of data, perhaps too much. Do rule writers need access to every buffer?  Or would frames be a better approach for rule writers, then the log being a much more succint summary of what happened.

2024-06-11 07:37 UTC, glongo commented
> When looking at a pcap with:
> 
>     * bind
> 
>     * search
> 
>     * unbind
> 
> 
> Suricata doesn't log in that order. Can we fix that?

How they are ordered?

2024-06-11 22:24 UTC, jasonish commented
> > When looking at a pcap with:
> > ```
> > * bind
> > 
> > * search
> > 
> > * unbind
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Suricata doesn't log in that order. Can we fix that?
> 
> How they are ordered?

In the pcap we have:
- bind request
- bind response
- search
- unbind request

In the eve output we have:
- search
- unbind
- bind
[ldap-and-search.pcap.gz](https://github.com/user-attachments/files/15795276/ldap-and-search.pcap.gz)

2024-06-21 13:51 UTC, glongo commented
Replaced with https://github.com/OISF/suricata/pull/11349

2024-06-21 13:51 UTC, closed without merging