pgsql: 6983 and 7000 7.0.x backports - v1
OISF/suricata pull request #11269
Opened 2024-06-06 21:22 UTC by jufajardini

Back port of https://github.com/OISF/suricata/pull/11234

Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7066
https://redmine.openinfosecfoundation.org/issues/7001

Describe changes:
- clean cherry picks from commits from afore mentioned PR

SV tests didn't require update as the app-layer metadata was for the moment kept out of the alerts for the tests created - at least while a pgsql rule would be a stream-only rule.

2024-06-07 00:20 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 20990

2024-06-12 14:15 UTC, catenacyber commented
> SV tests didn't require update as the app-layer metadata was for the moment kept out of the alerts for the tests created - at least while a pgsql rule would be a stream-only rule.

Do we need this if there is no improvement in SV tests ?

I think we do need this, but maybe a bit more with SV tests and alert pgsql metadata logging.
What do you think ?

2024-06-21 20:38 UTC, victorjulien requested changes
As discussed in person, needs changes in master first.

2024-06-26 12:50 UTC, jufajardini commented
> As discussed in person, needs changes in master first.

Will close for now, to reduce noise.

2024-06-26 12:50 UTC, closed without merging

2024-06-26 12:51 UTC, jufajardini commented
> > SV tests didn't require update as the app-layer metadata was for the moment kept out of the alerts for the tests created - at least while a pgsql rule would be a stream-only rule.
> 
> Do we need this if there is no improvement in SV tests ?
> 
> I think we do need this, but maybe a bit more with SV tests and alert pgsql metadata logging. What do you think ?

Will follow this request, once I fix master.