output: Add linktype name
OISF/suricata pull request #11279
Opened 2024-06-09 12:07 UTC by jlucovsky

Continuation of #11277 

Issue: 6954

This commit adds the linktype name to the output stream. The name is determined from the pcap utility function pcap_datalink_val_to_name

Link to ticket: https://redmine.openinfosecfoundation.org/issues/6954

Describe changes:
- Include the linktype name alongside linktype
- Update the schema with linktype_name

Updates:
- Rebased sv branch

### Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1853

2024-06-09 14:30 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 21024

2024-06-12 14:19 UTC, catenacyber approved these changes
Thanks for the work :-)

Personally, I would still not log `linktype_name` if `dl_name == NULL`, but ok this was also

- CI : 🟢 
- Code : good for me
- Commits segmentation : one commit is enough
- Commit messages : good enough for me
- Git ID set : looks fine for me
- CLA : you already contributed :-p
- Doc update : ok in json schema
- Redmine ticket : ok
- Rustfmt : no rust
- Tests : SV ok
- Dependencies added: none

2024-07-10 04:49 UTC, victorjulien commented
@jlucovsky this is blocked by https://github.com/OISF/suricata-verify/pull/1853#issuecomment-2173368628

2024-07-27 07:40 UTC, victorjulien requested changes
Needs more testing / more thorough SV tests.

2024-08-02 17:08 UTC, jufajardini commented
Can this be closed in favor of https://github.com/OISF/suricata/pull/11584?

2024-08-04 06:28 UTC, victorjulien commented
replaced by #11584

2024-08-04 06:28 UTC, closed without merging