detect/transform: from_base64 transform
OISF/suricata pull request #11300
Opened 2024-06-13 12:31 UTC by jlucovsky

Continuation of #11299 

This PR provides the `from_base64` transform used to match on content decoded with base64 using the mode (default rfc4648).

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6487](https://redmine.openinfosecfoundation.org/issues/6487)

Describe changes:
- New transform: `from_base64`
- Documentation
- Keyword parser in rust.

Updates:
- Doc: include what happens to the buffer if the input contains bytes that couldn't be decoded.
- Address other review comments.
- Format fix up

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1670

2024-06-13 21:50 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPW1_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 137 | 146 | 106.57% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 642 | 678 | 105.61% | 

Pipeline 21083

2024-06-13 22:33 UTC, jasonish commented on src/util-base64.c
> +            &num_decoded, Base64ModeRFC2045);
If you wanted to keep the all caps you can suppress the warning with `allow(non_camel_case_types)`.  Check the top of `core.rs` for an example.

But this is looking good.

2024-06-20 09:44 UTC, catenacyber requested changes
Could you review the ASAN SV report ?

Also maybe we want https://redmine.openinfosecfoundation.org/issues/7065 first

We do have 2 pure rust base64 decoders duplicates with the C ones...

2024-06-20 10:26 UTC, inashivb commented
> Could you review the ASAN SV report ?
> 
> Also maybe we want https://redmine.openinfosecfoundation.org/issues/7065 first
> 
> We do have 2 pure rust base64 decoders duplicates with the C ones...

I'll work on this next week likely and will make the updates as needed to this keyword.
If this is ready, I think it does not need to be blocked.

2024-06-21 09:14 UTC, jlucovsky commented
Continued in #11346

2024-06-21 09:14 UTC, closed without merging