packet: Ensure app_layer_events is not reused as packet is recycled
OISF/suricata pull request #11322
Opened 2024-06-18 14:00 UTC by jlucovsky

The app_layer_event packet is allocated once and then the memory is re-used. There are a few places where behavior is conditional on whether it's in use (non-NULL). As packets are recycled, the pointer is never reset to NULL. As a result, incorrect behavior can occur if the pointer value is checked.

This PR changes the packet recycle logic to first free the memory (if used) and then clear the pointer to prevent logic issues.

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7106

Describe changes:
- Removed unused AF-PACKET cpp value (flagged by compilation warning)
- Free and clear the app_layer_event memory
-

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-06-18 14:40 UTC, inashivb commented on src/packet.c
>      p->events.cnt = 0;
Do we need to reset this?

2024-06-18 14:41 UTC, inashivb commented on src/packet.c
>      p->events.cnt = 0;
ah these are diff events. nvm.

2024-06-18 17:10 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 642 | 621 | 96.73% | 

Pipeline 21124

2024-06-18 17:30 UTC, victorjulien requested changes
would like to see this fixed elsewhere, like in the mask function that checks the pointer

2024-06-19 10:33 UTC, catenacyber commented on src/source-af-packet.c
> -#define MAX_MAPS 32
Nice :-)

2024-06-19 11:43 UTC, catenacyber commented
@jlucovsky I am taking on this one for https://github.com/OISF/suricata/pull/11303 with other connex fixes

2024-06-19 11:56 UTC, catenacyber commented
Continued in https://github.com/OISF/suricata/pull/11328

2024-06-19 11:56 UTC, closed without merging