Thresholds/v20 backoff/v1
OISF/suricata pull request #11359
Opened 2024-06-24 12:24 UTC by victorjulien

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1939

#11358 plus backoff support

https://redmine.openinfosecfoundation.org/issues/7120

2024-06-24 16:00 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 21193

2024-06-25 22:12 UTC, jasonish requested changes
Nice, I like alot. Tested live and it looks good there. Still need a closer review. But throwing the requested changes for some doc on this new option.

2024-06-27 04:27 UTC, victorjulien commented on src/detect-engine-threshold.c
> +                te->backoff.next_value *= td->multiplier;
hah, forgot to implement overflow handling

2024-06-28 08:00 UTC, victorjulien commented
comments addressed in #11388

2024-06-28 08:00 UTC, closed without merging