Update bypass docs to use new keywords
OISF/suricata pull request #11443
Opened 2024-07-07 18:24 UTC by ozuriexv

Documentation for the 'bypass' keyword uses the legacy keyword 'http_host;' as opposed to the modernised 'http.host;'.

I'm unable to find a version of Suricata that utilises 'bypass;' while 'http_host;' is the preferred HTTP host keyword.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues
      (if applicable)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7143

Describe changes:
- changed 'http_host;' to 'http.host;' in the example demonstration of the 'bypass;' keyword.

2024-07-08 18:52 UTC, ozuriexv commented
> Thanks for catching that, and for your diligence in checking the versions!
> 
> The commit message is very descriptive (I like that!), but not following our guidelines: https://docs.suricata.io/en/latest/devguide/contributing/code-submission-process.html#commits Could you adjust that, please?
> 
> It seems that we have mentions to the legacy `http_host` style in quite a few other places. Don't want to push you to have more on your plate, but I'm thinking that maybe we could make the ticket about updating the mentions to `http_host` where possible... I'll consult with Victor about this.

I believe the commit now follows the guidelines.  As for outstanding issues of a similar type, I'll happily work through them and submit them as I find them.

2024-07-09 17:57 UTC, jufajardini commented
> > Thanks for catching that, and for your diligence in checking the versions!
> > The commit message is very descriptive (I like that!), but not following our guidelines: https://docs.suricata.io/en/latest/devguide/contributing/code-submission-process.html#commits Could you adjust that, please?
> > It seems that we have mentions to the legacy `http_host` style in quite a few other places. Don't want to push you to have more on your plate, but I'm thinking that maybe we could make the ticket about updating the mentions to `http_host` where possible... I'll consult with Victor about this.
> 
> I believe the commit now follows the guidelines. As for outstanding issues of a similar type, I'll happily work through them and submit them as I find them.

The PR title now indeed follows the guideline, we're still missing the commit message, though :P :)

Thanks for offering your time to help improve the documentation around this! I've created an umbrella ticket for that: https://redmine.openinfosecfoundation.org/issues/7145 we can create tickets for each specific effort from there.

2024-07-19 13:45 UTC, catenacyber requested changes
Thanks for the work.
Juliana requested some changes

2024-08-26 19:50 UTC, jufajardini commented
Hi @ozuriexv do you think you have some cycles to spare on this, still? :)

2024-11-18 14:58 UTC, catenacyber commented
Closing this PR as stale @ozuriexv you are welcome to open a new PR with a better commit message (and thanks for noticing this by the way)

2024-11-18 14:58 UTC, closed without merging