Pcap perf/v5
OISF/suricata pull request #11457
Opened 2024-07-09 14:12 UTC by victorjulien

https://redmine.openinfosecfoundation.org/issues/7155

Replaces / builds on #10635

2024-07-09 16:12 UTC, jasonish commented on src/source-pcap-file.c
> +        }
```
./src/suricata --pcap-file-buffer-size 4096
```
leads to warning:
```
Warning: pcap: pcap-file.buffer-size value of 4096 is invalid. Valid range is 4096-67108864 [PcapFileGlobalInit:source-pcap-file.c:161]
```

2024-07-09 16:13 UTC, jasonish requested changes
Off by one, otherwise looks good when fixup commit merged.

2024-07-10 08:42 UTC, victorjulien commented on src/source-pcap-file.c
> +        }
Fixed

2024-07-10 08:43 UTC, closed without merging

2024-07-10 08:43 UTC, victorjulien commented
replaced by #11464