output/reference: Include reference information in alert (if configured)
OISF/suricata pull request #11481
Opened 2024-07-11 17:59 UTC by jlucovsky

Continuation of #11284   

When configured, include the reference value in the alert. The configuration value is in the `alert` section:  types.alert.reference. The default value is off/no. Set to yes to include the expanded reference from the rule in the alert record.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [4974](https://redmine.openinfosecfoundation.org/issues/4974)

Describe changes:
- Add `reference` value to suricata.yaml.in (default no/off)
- Set flag in output logger if the config setting is on
- Format the reference as a sequence, e.g., `references: [ "ref-1" [, "ref-2" [, ...]]]`

Updates: 
- Moved config setting to metadata.rule
- Rebase

### Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1808

2024-07-11 19:24 UTC, jufajardini requested changes
Noticed a couple of things with the `suricata.yaml.in` changes. The rest, as far as I could see, looks good :)

2024-07-12 03:00 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 21494

2024-07-12 19:57 UTC, jlucovsky commented on doc/userguide/output/eve/eve-json-output.rst
> +            #reference: no            # include reference information, if present, in the alert
Yes, i'll make an update.

2024-07-12 19:57 UTC, jlucovsky commented on suricata.yaml.in
> +            # metadata:
I think so as `metadata` is both a scalar value and a section.

2024-07-13 13:34 UTC, jlucovsky commented
Continued in #11491

2024-07-13 13:34 UTC, closed without merging