Base64 decoder rust/v4
OISF/suricata pull request #11487
Opened 2024-07-12 10:00 UTC by inashivb

Link to tickets:
- https://redmine.openinfosecfoundation.org/issues/7065
- https://redmine.openinfosecfoundation.org/issues/7058
- https://redmine.openinfosecfoundation.org/issues/6280

Previous PR: https://github.com/OISF/suricata/pull/11479

Changes since v3:
- fixed buffer overflow due to size constraints
- fixed CString conversion issues, length calculations

2024-07-12 17:05 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 21504

2024-07-12 20:29 UTC, jasonish commented
> @jasonish could you please take look at the rust code in this PR? Specially if what's done in [7ffcbad](https://github.com/OISF/suricata/pull/11487/commits/7ffcbad23218606f0368808afbc7d23d465d8567) is correct. Thank you! 🙇🏽‍♀️

It looks ok, but seems out of place?  The other conversion function in `log.rs` is there as its only used by that module, and is private to that module.  This utility function does seem out of place here though.

Some extra thoughts:
- In a function named `rs_base64_decode`, I am decoding base64. If that base64 has NULs in it, I want them. This looks like a specialized base64 decode that returns a sane C string. Perhaps the naming a function documentation should provide that..  Also, this is C name space...  Perhaps `SCBase64DecodeToCString`?
- The file can just be named `base64.rs`, it doesn't need the `sc`.

2024-07-12 20:30 UTC, jasonish commented on rust/src/log.rs
> +pub fn vec_to_safe_cstring(val: Vec<u8>) -> CString {
As mentioned, seems out of place is the module. As it is only to support the specialized base64decode function, should probably live alongside it.

2024-07-12 20:32 UTC, jasonish commented on rust/src/utils/scbase64.rs
> +pub unsafe extern "C" fn rs_base64_decode(input: *const u8, len: u32, max_decoded: u32, mode: Base64Mode) -> *mut Base64Decoded {
As metioned, naming. Should follow `SCBase64Decode` format.. But `ToCString` added or something.

2024-07-12 21:50 UTC, jasonish commented
One last thing to consider, after functionality is verified is merging with the existing `ffi:base64` module we have.

- The one under FFI is to just expose base64 functionality to C.
- The `utils/base64` could be nice pure Rust functions that provide all the functionality needed to Rust, which the functions in `ffi/rust` expose to C.

2024-07-19 13:44 UTC, catenacyber requested changes
Jason requested changes, and I think you are working on them already ;-)

2024-07-22 09:19 UTC, closed without merging