smtp: Prevent error messages on packet path
OISF/suricata pull request #11520
Opened 2024-07-18 13:51 UTC by jlucovsky

Continuation of #11470 

Issue: 7126

This commit abandons the use of StringParseUint32 which generates an error message of there are non-numeric characters.

The SMTP parser had used this function on the packet path; this commit uses `ByteExtractStringUint32` instead.

An example of the content causing the error message to be emitted:

    3460 LAST

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7126

Describe changes:
- Use `ByteExtractStringUint32` instead of `StringParseUint32` function that emits error messages

Updates:
- Abandoned `strtoul` in favor of `ByteExtractStringUint32`

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-07-18 16:25 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 21611

2024-07-19 15:13 UTC, catenacyber commented on src/app-layer-smtp.c
> +    if (ByteExtractStringUint32(&state->bdat_chunk_len, 10, 0, strbuf) < 0) {
I like that

2024-07-19 15:13 UTC, catenacyber commented on src/detect-gid.c
> +    if (errno == ERANGE || endptr == NULL || *endptr != '\0') {
Should we use `StringParseUint32` here ?

2024-07-26 14:51 UTC, catenacyber commented on src/detect-gid.c
> +    if (errno == ERANGE || endptr == NULL || *endptr != '\0') {
StringParseUint32 seems more readable than this `strtoul` condition

2024-07-26 14:55 UTC, catenacyber requested changes
Thanks for the work :-)

- CI : 🟢 
- Code : looks good enough, I would remove strtoul in detect-sid and such as well
- Commits segmentation : good
- Commit messages : `detect: Clear errno before strtoul` could have an explanation about why
- Git ID set : looks fine for me
- CLA : you already contributed
- Doc update : not needed
- Redmine ticket : ok
- Rustfmt : no rust
- Tests : 🟠  can we have a SV test for this ? There is a pcap in the redmine ticket
- Dependencies added: none

2024-08-14 14:15 UTC, jlucovsky commented
Continued in #11630

2024-08-14 14:15 UTC, closed without merging