detect: allow rule which need both directions to match
OISF/suricata pull request #11530
Opened 2024-07-19 11:24 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5665

Describe changes:
- allows bidirectional signature matching !

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1922

https://github.com/OISF/suricata/pull/11528 with better doc bullet list

2024-07-19 19:50 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 21630

2024-07-24 18:01 UTC, jufajardini requested changes
Left minor comments for docs.

Managed to review up until `detect-engine.c` (around https://github.com/OISF/suricata/pull/11530/files#diff-f0400524fccdb926fe9697ed027b4210459222917a866616235d162b880370f2R1449). So far, seems good!

Following up on a previous PR comment about name suggestions, what about transaction rule? (or something that brought attention to this aspect) Asking also because the code itself refers to `<>` rules as bidir rules, so if we could avoid possible misunderstandings there, that'd be great.

One question that emerged while reviewing was: what happens if a rule tries to use negated or absent content?

2024-07-25 04:42 UTC, inashivb commented
> Following up on a previous PR comment about name suggestions, what about transaction rule? (or something that brought attention to this aspect) Asking also because the code itself refers to `<>` rules as bidir rules, so if we could avoid possible misunderstandings there, that'd be great.

+1

2024-07-26 14:14 UTC, catenacyber commented
> One question that emerged while reviewing was: what happens if a rule tries to use negated or absent content?

This should work as unidirectional rules that use negated content...
Do you have an example ?

2024-07-26 14:20 UTC, catenacyber commented on doc/userguide/rules/intro.rst
> +.. container:: example-rule
ok fixing

2024-07-26 14:24 UTC, catenacyber commented on src/detect-flow.c
> +    sigmatch_table[DETECT_BIDIR_TOCLIENT].url = "/rules/flow-keywords.html#TODO";
Thanks, fixing this

2024-07-26 14:26 UTC, catenacyber commented on src/detect-engine-mpm.c
> +            if (app->dir == 1) {
You can create an optimization ticket (if there is not one already), and it should be a boolean like `if (app->dir_toclient)`

2024-07-26 14:28 UTC, catenacyber commented
Thanks Juliana, continued in https://github.com/OISF/suricata/pull/11561

2024-07-26 14:28 UTC, closed without merging

2024-07-30 19:07 UTC, jufajardini commented
> > One question that emerged while reviewing was: what happens if a rule tries to use negated or absent content?
> 
> This should work as unidirectional rules that use negated content... Do you have an example ?

I'll try to come up with one (and see if I manage to test it using the corresponding SV branch for the most recent version of this work :) )

2024-07-30 21:31 UTC, jufajardini commented on src/detect-engine-mpm.c
> +            if (app->dir == 1) {
Ticket created - https://redmine.openinfosecfoundation.org/issues/7186