output/reference: Include reference information in alert (if configured)
OISF/suricata pull request #11588
Opened 2024-07-30 15:35 UTC by jlucovsky

Continuation of #11565       

When configured, include the reference value in the alert. The configuration value is in the `alert` section:  types.alert.reference. The default value is off/no. Set to yes to include the expanded reference from the rule in the alert record.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [4974](https://redmine.openinfosecfoundation.org/issues/4974)

Describe changes:
- Add `reference` value to suricata.yaml.in (default no/off)
- Set flag in output logger if the config setting is on
- Format the reference as a sequence, e.g., `references: [ "ref-1" [, "ref-2" [, ...]]]`

Updates: 
- Rebase

### Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1808

2024-07-30 22:05 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 138 | 147 | 106.52% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 648 | 703 | 108.49% | 

Pipeline 21785

2024-07-31 14:49 UTC, jufajardini requested changes
(sorry for not catching these before!)

2024-07-31 14:49 UTC, jufajardini commented on src/detect-reference.c
> +        /* already bound checked to be REFERENCE_CONTENT_NAME_MAX or less */
nit-ish: the comments about the bound checks are mismatched, here, right? (i.e., here it should be `REFERENCE_CONTENT_SYSTEM_MAX` )

2024-07-31 14:49 UTC, jufajardini commented on suricata.yaml.in
> +                # reference: no        # include reference information from the rule
(I apologize for not thinking of that before, but) we should add `reference` info to [EVE advanced settings](https://docs.suricata.io/en/latest/output/eve/eve-json-output.html#alerts), and we should also update https://github.com/OISF/suricata/blob/master/doc/userguide/partials/eve-log.yaml#L77 to reflect what we have here.

2024-08-13 14:56 UTC, jlucovsky commented
Continued in #11625

2024-08-13 14:56 UTC, closed without merging

2024-08-22 15:41 UTC, jufajardini commented on src/detect-reference.c
> +        /* already bound checked to be REFERENCE_CONTENT_NAME_MAX or less */
heh, just noticed that I typo'ed when adding my review. sheesh >__<'