eve/dns: make version required (cherry-pick from master)
OISF/suricata pull request #11586
Opened 2024-07-30 14:07 UTC by jlucovsky

The "eve.version" field is not always logged. Update the schema to enforce that it is, and fix it for records that don't log it.

Ticket: #7167
(cherry picked from commit fcc1b1067b5e4c3b9b063ab90fa073de57577968)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7168

Describe changes:
- Cherry pick fcc1b1067b5e4c3b9b063ab90fa073de57577968 from master
-
-

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-07-30 14:40 UTC, victorjulien approved these changes

2024-08-01 05:10 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 21806

2024-08-06 15:55 UTC, victorjulien commented
```
Number of concurrent jobs: 8
/tmp/sv-staging/bug-2158/output/eve.json - INVALID. Errors:
1./dns "version" is a required property
===> bug-2158: FAILED: Invalid JSON schema
```

2024-08-06 15:56 UTC, victorjulien commented
This leads to SV errors. In general, @jasonish do you think we need this for 7?

2024-08-06 16:05 UTC, jasonish commented
> This leads to SV errors. In general, @jasonish do you think we need this for 7?

I thought it might help people transition to 8 by having this in 7.  For example, they could update their log processing to expect a version and handle accordingly before upgrading to 8, as a prep step. But in practice it should be easy enough to assume a version of "2" is no version is present.  Perhaps just a documentation note in the 8.0 docs.

2024-08-06 16:10 UTC, victorjulien commented
> > This leads to SV errors. In general, @jasonish do you think we need this for 7?
> 
> I thought it might help people transition to 8 by having this in 7. For example, they could update their log processing to expect a version and handle accordingly before upgrading to 8, as a prep step. But in practice it should be easy enough to assume a version of "2" is no version is present. Perhaps just a documentation note in the 8.0 docs.

Not opposed to adding it, but I guess it needs some work to make SV happy.

2024-08-06 16:10 UTC, victorjulien requested changes
see inline

2024-08-06 16:12 UTC, jasonish commented
> > > This leads to SV errors. In general, @jasonish do you think we need this for 7?
> > 
> > 
> > I thought it might help people transition to 8 by having this in 7. For example, they could update their log processing to expect a version and handle accordingly before upgrading to 8, as a prep step. But in practice it should be easy enough to assume a version of "2" is no version is present. Perhaps just a documentation note in the 8.0 docs.
> 
> Not opposed to adding it, but I guess it needs some work to make SV happy.

Yes, I'll take a look at that, but at a lesser priority than these other 7.0.x PRs.

2024-08-26 19:12 UTC, jasonish commented
Replaced by https://github.com/OISF/suricata/pull/11660.

2024-08-26 19:12 UTC, closed without merging