pgsql: track 'progress' in tx per direction - v3
OISF/suricata pull request #11618
Opened 2024-08-08 00:50 UTC by jufajardini

Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7113

Previous PR: https://github.com/OISF/suricata/pull/11547

Describe changes:
- track `tx_completion` per tx direction
- add more `PgsqlStateProgress` states to `tx_completion` check (especially for `to_server` direction)
- reorganize `PgsqlStateProgress` enum to separate `to_server` and `to_client` states
- bring the trigger raw stream reassembly call to the moment when tx is completed

Update:
- split the function that checks for tx_completion to per-direction functions, too, and decouple checking for transaction completion from the global state
- mark request or response as completed as soon as we have that info
- add a comment to explain why we're marking a response as done when parsing a request
- reword commit message, previous version was weird.

Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2004

2024-08-08 03:20 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 22017

2024-08-08 05:28 UTC, victorjulien commented on rust/src/pgsql/pgsql.rs
> +                if tx_old.tx_req_state < PgsqlTxReqProgress::TxReqDone && tx_old.tx_res_state < PgsqlTxResProgress::TxResDone {
how common will this be? Will we not more commonly have the `Req` state as `TxReqDone`? AFAICS in most cases when we create a tx the req state will already be set to done?

2024-08-08 05:31 UTC, victorjulien commented on rust/src/pgsql/pgsql.rs
> +                    let temp_state: PgsqlStateProgress;
this could be made slightly more compact by using the same tuple logic as with the response?

2024-08-08 05:32 UTC, victorjulien commented on rust/src/pgsql/pgsql.rs
> +                    let tx_completed = if let Some(state) = PgsqlState::request_next_state(&request) {
I think the code is much cleaner now, thank. Do feel it could use a comment explaining the state transition work flow

2024-08-08 05:32 UTC, victorjulien commented on rust/src/pgsql/pgsql.rs
> +pub extern "C" fn rs_pgsql_tx_get_res_state(tx: *mut std::os::raw::c_void) -> PgsqlTxResProgress {
style: use new API style here `SCPgslTx...`

2024-08-08 05:36 UTC, victorjulien requested changes
almost there... see final comments inline

2024-08-15 23:07 UTC, jufajardini commented
Replaced by: https://github.com/OISF/suricata/pull/11635

2024-08-15 23:07 UTC, closed without merging