lua: use lua from crates.io rather than github
OISF/suricata pull request #11624
Opened 2024-08-12 22:09 UTC by jasonish

This allows offline builds to work when this crate is vendored.

2024-08-27 14:00 UTC, catenacyber commented
Is there a ticket for this ?

2024-08-27 20:51 UTC, jasonish commented
> Is there a ticket for this ?

There is now: https://redmine.openinfosecfoundation.org/issues/7226

2024-08-28 07:28 UTC, catenacyber requested changes
Could you rebase with the commit including the ticket number ?

How is this tested ? (should offline build be part of CI ?)

2024-09-12 14:16 UTC, jasonish commented
Rebase and fix here: https://github.com/OISF/suricata/pull/11762

2024-09-12 14:16 UTC, closed without merging