Backport of 6553/6875 to main-7.0.x
OISF/suricata pull request #11639
Opened 2024-08-18 13:05 UTC by jlucovsky

Continuation of #11634 

Link to ticket: https://redmine.openinfosecfoundation.org/issues/6555

Describe changes:
- Cherry-pick commits from https://github.com/OISF/suricata/pull/10654 for issue 6555
- s-v updates for 7.0.7+

Updates:
- Initialize membuffer values (detected via asan)
- Cherry-pick fix for 6875 to avoid dbv error.

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2012
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-08-18 15:30 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 22157

2024-08-22 15:09 UTC, jufajardini commented
We should create the backport ticket for https://redmine.openinfosecfoundation.org/issues/6875, right?

2024-08-27 12:42 UTC, jlucovsky commented on src/util-buffer.c
> +    MemBufferReset(buffer);
Yes -- this is new. 

I have mixed feelings on whether this should be a separate commit. The cherry-pick of commit 9c3669b03fc3903c30ced9088361e74fd4aec04f introduces instability; this change makes it stable. Thus, is it ok for a commit to add instability and another commit to restore it?

2024-08-27 12:46 UTC, jlucovsky commented
> Cherry-picks - all relevant ones seem to be there. Only a comment about the ASAN-related change, to understand if we should put it in a separate commit.
> 
> Wondering (not sure) if we should add anything to the upgrading to 7 section...

Issue 7224 created for backport of 6875.

2024-08-27 13:06 UTC, jasonish commented on src/util-buffer.c
> +    MemBufferReset(buffer);
Maybe mention in the commit message about the addition made during the backport of that commit?

2024-08-27 13:07 UTC, jasonish commented
> Wondering (not sure) if we should add anything to the upgrading to 7 section...

While this does change the output in 7, I do not believe in does in any breaking type of way, so I don't think we need to document it in an upgrade section.

2024-08-28 21:04 UTC, jasonish requested changes
Comments inline, but I think I'd lean towards that extra fix as its own commit.

2024-08-30 16:03 UTC, jufajardini commented
> Comments inline, but I think I'd lean towards that extra fix as its own commit.

partly related: should we also fix this in master?

2024-09-03 13:32 UTC, jlucovsky commented on src/util-buffer.c
> +    MemBufferReset(buffer);
I'll make an update to the commit message that includes the additional changes.

2024-09-03 13:59 UTC, jlucovsky commented
Continued in #11709

2024-09-03 13:59 UTC, closed without merging