doc/rfb: mention accidental fix for security_result log
OISF/suricata pull request #11636
Opened 2024-08-16 14:55 UTC by catenacyber

Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7198

Describe changes:
- doc/rfb: mention accidental fix for security_result log

As requested in https://github.com/OISF/suricata/pull/11629#discussion_r1718466414

2024-08-16 16:12 UTC, jufajardini approved these changes

2024-08-21 08:18 UTC, satta commented on doc/userguide/upgrade.rst
> +  sometimes looged with a dash instead of an underscore.
s/oo/o/

2024-08-21 21:17 UTC, jasonish requested changes
Typo.

2024-08-25 20:25 UTC, catenacyber commented on doc/userguide/upgrade.rst
> +  sometimes looged with a dash instead of an underscore.
opps

2024-08-25 20:25 UTC, catenacyber commented
Typo fixed in https://github.com/OISF/suricata/pull/11658

2024-08-25 20:25 UTC, closed without merging