Convert the napatech packet source to a plugin
OISF/suricata pull request #11651
Opened 2024-08-21 12:55 UTC by jlucovsky

Continuation of #11646  

This PR contains the changes to distribute and build the Napatech source modules as a "capture plugin". 

Describe changes:
- Converted the Napatech source modules to be suitable for a capture plugin
- User-level upgrade documentation 

Updates:
- Doc update -- use "Napatech" instead of "NAPATECH"
- Revert unnecessary change to decode module name -- `NapatechDecode`.
- Combine like commits (remove unnecessary fixup commit)

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-08-21 12:57 UTC, jlucovsky commented
@ralpheastwood I've tested this on a system with a Napatech NT40 4x1G. If you have time to test this, it'd be helpful.

2024-08-22 20:15 UTC, jufajardini requested changes
The documentation is rather easy to follow - I think it is good for understanding some concepts about Suricata plugins as a whole. Thanks for that!

One minor thing I noticed is that it seems that throughout the sections the noun version `command line` is being used, instead of the adjective `command-line` one. (nitty picky D: )

2024-08-22 20:15 UTC, jufajardini commented on doc/userguide/upgrade/8.0-napatech-plugin.rst
> +Existing Napatech command line options and configuration should continue to work.
same here.

2024-08-22 20:15 UTC, jufajardini commented on plugins/napatech/README.md
> +data on the command line a capture plugin, but this plugin does not yet handle
Are we missing something here? Maybe:
```suggestion
data on the command line to a capture plugin, but this plugin does not yet handle
```

2024-08-24 13:43 UTC, jlucovsky commented
Continued in #11657

2024-08-24 13:43 UTC, closed without merging