[detect] Harmonize code for validate callbacks 5634 v2
OISF/suricata pull request #11699
Opened 2024-09-02 18:45 UTC by catenacyber

Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/5634

Describe changes:
- detect: change the ValidateCallback prototype to deduplicate code
- detect: use one function for md5-like keywords (quic-cyu-hash, ssh-hassh, tls-ja3-hash...)

#11697 with clean git history

This was done on the way to convert quic keywords to rust like https://github.com/OISF/suricata/pull/11575

With this PR, it should be easy to add a wrapper for rust for this ValidateCallback stuff

2024-09-03 05:20 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
  

Pipeline 22324

2024-09-24 00:25 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 22780

2024-10-08 09:22 UTC, victorjulien requested changes
This is a nice cleanup.

I think we do need a good understanding of how rule validation changed per keyword, and document that in the upgrade guide, esp if we are stricter for some keywords than we were before.

2024-10-08 09:22 UTC, victorjulien commented on src/detect.h
> +typedef struct DetectContentData_ {
would like to keep this in detect-content.h, can this be reworked to make that happen?

2024-10-08 12:57 UTC, catenacyber commented
> Do we have a list of which keyword got stricter? If so, we need them to be listed as such in the upgrade docs.

Adding this

2024-10-08 13:07 UTC, catenacyber commented
Next in https://github.com/OISF/suricata/pull/11902

2024-10-08 13:07 UTC, closed without merging