rust: keep older version of serde
OISF/suricata pull request #11741
Opened 2024-09-10 08:18 UTC by catenacyber

Link to ticket: https://redmine.openinfosecfoundation.org/issues/
None, just fixing the CIFuzz in the CI

Describe changes:
- rust: keep older version of serde

Reverts part of 599a451e44131e8c52a74eb175fb143e7db2ef6b

2024-09-10 09:25 UTC, victorjulien commented
Is there no way to get cifuzz to use a more recent compiler?

2024-09-10 12:32 UTC, catenacyber commented
> Is there no way to get cifuzz to use a more recent compiler?

https://github.com/google/oss-fuzz/pull/12365 is the good way

The problem behind is coverage, whose format has been bumped recently in clang and rust, and they need to match...

2024-09-10 12:32 UTC, catenacyber commented
#11745 is this commit + a try to fix CI fuzzing

2024-09-10 14:31 UTC, jasonish commented
Should be able to do this in our `Cargo.lock.in` so it sticks with:
```
+serde = { version = "=1.0.197" }
+serde_derive = { version = "1.0.197" }
```

2024-09-11 09:10 UTC, victorjulien requested changes
needs a cargo.toml.in update like is done in #11753

2024-09-11 09:29 UTC, victorjulien commented
> > needs a cargo.toml.in update like is done in #11753
> 
> Why so ? Why not go on with #11753 then ?



> > needs a cargo.toml.in update like is done in #11753
> 
> Why so ? Why not go on with #11753 then ?

That adds the additional fuzz target that isn't ready for merge.

2024-09-11 10:03 UTC, catenacyber commented
Next version in https://github.com/OISF/suricata/pull/11756 even if I do not understand the point

2024-09-12 14:45 UTC, catenacyber commented
Reopening as I think this is still the simplest way to go

2024-09-12 16:12 UTC, closed without merging