hyperscan: add caching mechanism for hyperscan contexts v5
OISF/suricata pull request #11811
Opened 2024-09-23 11:17 UTC by lukashino

Followup of https://github.com/OISF/suricata/pull/11774

Cache Hyperscan serialized databases to disk to prevent compilation of the same databases when Suricata is run again with the same ruleset.
The current work operates in the logging folder and caches individual Hyperscan databases - potentially the ruleset might be even slightly changed and it still can reuse part of the unchanged signature groups.
Loading **fresh** ET Open ruleset:  19 seconds
Loading **cached** ET Open ruleset: 07 seconds

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7170

Describe changes:
v5:
- rebased
- commit message update
- docs update

v4:
- rebased
- changed the default caching directory to somewhere /var/lib/suricata/cache/hs
- custom cache directory path option added
- docs added
- the default settings changed - enabled on the config generation, **disabled** when the option is not present in the config

v3
- rebased
- MPM caching is still left on by default.

v2
- improved styling to follow Suricata code styleguide
- increased cache file name length from 10 to 20 characters
- cache file name is a hash of the patterns - now only HS relevant fields are hashed - as long as the group of patterns itself is not changed then it is reused
- minor refactors
- added a safe variant of littlehash2 function
- added suricata.yaml option to enable/disable caching
- changed the storage location to the configured logging directory

v1
- initial work to cache and load Hyperscan databases from the disk

2024-09-25 14:49 UTC, jufajardini commented on suricata.yaml.in
> +  # Cache MPM contexts to the disk for avoid rule compilation at the startup.
interestingly, [this version](https://github.com/OISF/suricata/pull/11708/files#diff-6edad567c7414ca3b78009e7d315547542cbb77455e7a223c11719d2734fd3dbR1675) had better preposition usage :P

2024-09-25 15:02 UTC, jufajardini reviewed
Commit explanations look good to me, considering past reviews.

I did notice however that we failed to notice that they're not referencing the redmine ticket >_<'

2024-09-25 19:07 UTC, jasonish commented
Hitting an issue when running with privilege dropping. For example:
- remove the cache directory: `sudo rm -rf var/lib/suricata/cache/`
- recreate as if setup for privilege dropping:
  - `sudo mkdir var/lib/suricata/cache`
  - `sudo chown -R root:jason var/lib/suricata/cache`
  - `sudo chmod 2775 var/lib/suricata/cache`
- Run Suricata: `sudo ./src/suricata -i enp10s0 --user jason`
- Results in (would be many more but we limit to one warning):
    ```
    Warning: mpm-hs: Failed to create Hyperscan cache file, make sure the folder exist and is writable or adjust sgh-mpm-caching-path setting (/opt/suricata/8.0.0-dev/var/lib/suricata/cache/hs/17049829294979608135_v1.hs) [HSSaveCache:util-mpm-hs.c:765]
    ```

It appears the caching is done before privileges are dropped, and there is no access after privileges are dropped.

And then during a rule reload, where privileges are dropped, we don't have access to this directory.

2024-09-25 19:31 UTC, jasonish commented
> Hitting an issue when running with privilege dropping. For example:
> 
>     * remove the cache directory: `sudo rm -rf var/lib/suricata/cache/`
> 
>     * recreate as if setup for privilege dropping:
>       
>       * `sudo mkdir var/lib/suricata/cache`
>       * `sudo chown -R root:jason var/lib/suricata/cache`
>       * `sudo chmod 2775 var/lib/suricata/cache`
> 
>     * Run Suricata: `sudo ./src/suricata -i enp10s0 --user jason`
> 
>     * Results in (would be many more but we limit to one warning):
>       ```
>       Warning: mpm-hs: Failed to create Hyperscan cache file, make sure the folder exist and is writable or adjust sgh-mpm-caching-path setting (/opt/suricata/8.0.0-dev/var/lib/suricata/cache/hs/17049829294979608135_v1.hs) [HSSaveCache:util-mpm-hs.c:765]
>       ```
> 
> 
> It appears the caching is done before privileges are dropped, and there is no access after privileges are dropped.
> 
> And then during a rule reload, where privileges are dropped, we don't have access to this directory.

Ok, so the directory creation is done before privilege dropping. If that can be delayed til after privilege dropping we should be good. For example, the file store directory layout is made after dropping privileges.

2024-09-25 19:31 UTC, jasonish requested changes
Comments in-line with respect to some required changes when running with privilege dropping.

2024-09-26 23:40 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 649 | 622 | 95.84% | 

Pipeline 22886

2024-10-06 21:53 UTC, lukashino commented
goto https://github.com/OISF/suricata/pull/11887

2024-10-06 21:53 UTC, closed without merging