Feat/decouple stream bypass from tls encrypted bypass v4
OISF/suricata pull request #11831
Opened 2024-09-24 21:22 UTC by lukashino

Following up on https://github.com/OISF/suricata/pull/11801

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6788

Describe changes:
v4
- rebased
- changed SSH bypass defaults to hopefully be in sync with the previous settings

v3
- added SSH app-layer option `encryption-handling` allowing to choose whether to continue inspection on SSH once it turns encrypted
- added SV tests
- minor docs updates

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2047

2024-09-25 04:35 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 22800

2024-09-27 13:22 UTC, victorjulien commented
We also need an addition to the upgrade section, I think.

2024-09-27 13:24 UTC, victorjulien commented
Blocked by issues in the SV test

2024-10-03 01:56 UTC, jufajardini requested changes
Wondering if we should add a note in the upgrading section about this new option for SSL, of it too small to be needed there.

2024-10-03 01:56 UTC, jufajardini commented on doc/userguide/performance/ignoring-traffic.rst
> +`app-layer.protocols.tls.encryption-handling` options to `bypass` Suricata
```suggestion
`app-layer.protocols.ssh.encryption-handling` options to `bypass` Suricata
```

2024-10-03 01:56 UTC, jufajardini commented on suricata.yaml.in
> +      # encryption-handling: bypass
Shouldn't we indicate here what is the default?

2024-10-03 01:56 UTC, jufajardini commented on suricata.yaml.in
> +      # encryption-handling: bypass
Is the behavior here the same as we have for tls, or is there a difference?

2024-10-06 21:53 UTC, lukashino commented
goto https://github.com/OISF/suricata/pull/11886

2024-10-06 21:53 UTC, closed without merging