decode/ethertype: Event on unknown ethertype
OISF/suricata pull request #11850
Opened 2024-10-01 13:30 UTC by jlucovsky

Continuation of #11632 

Issue: 7129

Create a decode/engine event if unknown ethertypes are observed.

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7129

Describe changes:
- Add an event created when unknown ethertypes are observed
- Update schema with event counter
- Add rule for event.

Updates
- Include the ethertype when ethernet information is logged.

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1954
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-10-01 17:05 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .uptime | 649 | 623 | 95.99% | 

Pipeline 22938

2024-11-21 17:03 UTC, catenacyber approved these changes
Thanks for the work

CI : ✅
Code : good
Commits segmentation : ok, not sure if commit "doc/threshold: Threshold keyword clarifications" belongs here
Commit messages : good
Git ID set : looks fine for me
CLA : you already contributed
Doc update : nice addition 👏 not sure we should list all the currently recognized ether types as it will grow outdated
Redmine ticket : ok, should it target 8 ?
Rustfmt : no rust
Tests : nice, thanks (why does not json log 0x integers :-p)
Dependencies added: none

2025-01-06 09:29 UTC, victorjulien requested changes
see inline

2025-01-06 09:29 UTC, victorjulien commented on src/decode.h
> +#define PKT_IS_UNKNOWN BIT_U32(31)
I don't want to use this flag space for a protocol specific counter. Also, the flag is named way to generically.

2025-01-06 09:29 UTC, victorjulien commented on src/decode.h
> +            ENGINE_SET_UNKNOWN_EVENT(p, ETHERNET_UNKNOWN_ETHERTYPE);
why not set the event here and increment the counter. Seems to make the flag obsolete

2025-01-28 13:34 UTC, jlucovsky commented on src/decode.h
> +            ENGINE_SET_UNKNOWN_EVENT(p, ETHERNET_UNKNOWN_ETHERTYPE);
Is there a value in having 2 counters for an unknown ethernet type?

The decoder counts occurrences of unknown ethertypes; the same occurrence is counted twice with the event.

Eg.,
```
decoder.unknown_ethertype                                    | Total                     | 281
decoder.event.ethernet.unknown_ethertype                     | Total                     | 281
```

2025-01-28 13:36 UTC, victorjulien commented on src/decode.h
> +            ENGINE_SET_UNKNOWN_EVENT(p, ETHERNET_UNKNOWN_ETHERTYPE);
how do we handle this for other cases?

2025-01-28 14:02 UTC, jlucovsky commented on src/decode.h
> +            ENGINE_SET_UNKNOWN_EVENT(p, ETHERNET_UNKNOWN_ETHERTYPE);
The other decoders count occurrences, e.g., ethernet, vntag, etc with events for discrete conditions (e.g., header too small).

The unknown case is unique -- we added a counter (Dec 2022) for unknown ether types. However, the counter seems unnecessary with the event tracking the same value.

Can we keep the duality for 8 (maybe?) and remove the counter in 9 leaving behind only the event?

2025-01-28 14:12 UTC, victorjulien commented on src/decode.h
> +            ENGINE_SET_UNKNOWN_EVENT(p, ETHERNET_UNKNOWN_ETHERTYPE);
This approach makes sense to me.

2025-01-28 14:56 UTC, jlucovsky commented on src/decode.h
> +            ENGINE_SET_UNKNOWN_EVENT(p, ETHERNET_UNKNOWN_ETHERTYPE);
I've created an issue to track removing the non-event based counter for post 8.0: https://redmine.openinfosecfoundation.org/issues/7528

2025-01-28 15:08 UTC, closed without merging