plugins: add support for ndpi-like plugins - v1
OISF/suricata pull request #11969
Opened 2024-10-15 22:22 UTC by jasonish

Non-draft version of nDPI plugin support.

Previous PR: https://github.com/OISF/suricata/pull/11944

Includes:
- flow lifecycle callbacks
- thread init callback
- eve output callback

2024-10-16 04:40 UTC, victorjulien commented on src/flow-callbacks.h
> +typedef void (*SCFlowInitCallbackFn)(ThreadVars *tv, Flow *f, const Packet *p, void *user);
Think we should document these typedefs as well as the place where the callback itself is registered? When is it called, with what args, etc.

2024-10-16 04:41 UTC, victorjulien commented on src/output-eve.c
> +bool EveRegisterCallback(EveUserCallbackFn fn, void *user)
Should the SC prefix be added here as well?

2024-10-16 04:42 UTC, victorjulien commented on src/output-json.c
> +#include "output-eve.h"
typically suricata-common is the first include

2024-10-16 05:20 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 23113

2024-10-16 09:31 UTC, victorjulien commented on src/flow-manager.c
> +    SCFlowRunFinishCallbacks(tv, f);
need this also in `FlowGetUsedFlow` I think

2024-10-16 09:32 UTC, victorjulien requested changes
Looks good. See inline comments on the naming prefix.

Also, wonder if these new files should start in a new dir structure (remember that one? :))

2024-10-17 18:20 UTC, jasonish commented
> Also, wonder if these new files should start in a new dir structure (remember that one? :))

Not yet, I don't think.  We have to decide if we should do the re-org to a new directory as well, to look and feel more like a first class library: https://github.com/OISF/suricata/pull/10421

2024-10-17 18:20 UTC, closed without merging