applayer/htp: convert to new FAIL/PASS API v-4
OISF/suricata pull request #11960
Opened 2024-10-14 19:17 UTC by Nancyenos

Ticket: #6935

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [ ] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [ ] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [ ] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [ ] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [ ] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
-
-
- Convertted applayer/htp:  to new FAIL/PASS API
- previous pr #11950 

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-10-15 02:19 UTC, jufajardini requested changes
Thanks for this work, I've left a few inline comments with changes that are needed.

I noticed that you've added some new checks in some tests, in general, they seem to make sense, so good :)

However, I've noticed that several tests (for example, `HTPParserTest11` and `HTPParserTest12` and some others further down) are missing some clean-ups. Is there a reason why you didn't fully convert and clean up those? For all unit tests in this file, we want to go through the same procedure of removing the if checks and replacing them with the `FAIL/IF` macros.

2024-10-15 02:19 UTC, jufajardini commented on src/app-layer-htp.c
> +    SCFree(name);
I think it would be fine if you put this along with the other `free` statements, as we only care about memory leaks in case of test success.

2024-10-15 02:19 UTC, jufajardini commented on src/app-layer-htp.c
>          if (4 != bstr_len(tx_ud->request_uri_normalized)) {
I think the rest of this test was left behind unchanged :P

2024-10-15 02:19 UTC, jufajardini commented on src/app-layer-htp.c
> +    FAIL_IF_NULL(tx->request_method);
I'm curious: why did you add this check?

2024-10-15 10:34 UTC, Nancyenos commented
Hey @jufajardini .Thank you for the review...I will work on the review and the rest of the cleanup....i wanted to be sure i was on the right path..

2024-10-15 22:59 UTC, jufajardini commented
> Hey @jufajardini .Thank you for the review...I will work on the review and the rest of the cleanup....i wanted to be sure i was on the right path..

I see, that's fair, just, when that is the case, please let us know in the PR that it's a work in progress (or just WIP), and point out that you want to know if you're on the right track - this sets the expectations and lets us know what we're looking at, or where to offer more guidance :)

2024-10-16 07:51 UTC, Nancyenos commented
continued work in #11973

2024-10-16 07:51 UTC, closed without merging