MySQL: parser v2
OISF/suricata pull request #11996
Opened 2024-10-21 03:33 UTC by QianKaiLin

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [x] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: 

Describe changes:
- fix mysql parser bug.
- fix mysql logger bug.
- add mysql detection keywords `mysql.command` and `mysql.rows`
- add SV tests.
- upgrade User Guide document and Upgrade document.

SV_REPO=https://github.com/QianKaiLin/suricata-verify
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2067

2024-10-21 07:48 UTC, inashivb requested changes
Could you please take a look at all the CI failures, fix them and resubmit?
Thank you!

2024-10-21 09:17 UTC, QianKaiLin commented
> Could you please take a look at all the CI failures, fix them and resubmit? Thank you!

Yeah, I will fix it.

2024-10-25 00:57 UTC, jufajardini commented
I've re-authorized the CI checks. As a reminder, before the work can be merged, commits that just fix changes introduced by this PR should be squashed into their related original commits ;)

2025-01-28 15:11 UTC, catenacyber commented
@QianKaiLin would you do a new PR with a rebased version ? Thanks for your work

2025-02-07 03:14 UTC, closed without merging