eve/tls: reimplement basic and extended logging in terms of custom - v2
OISF/suricata pull request #11991
Opened 2024-10-18 15:59 UTC by jasonish

Commit c79a382 added ALPN logging to extended TLS output but there was no way to add this to custom. To prevent this from happening in the future, implement basic and extended logging in terms of custom.

Ticket: https://redmine.openinfosecfoundation.org/issues/7333

Changes from previous PR https://github.com/OISF/suricata/pull/11984:
- one line removal of unused code
- update doc and configuration example to have a complete list of custom fields

2024-10-18 16:39 UTC, victorjulien approved these changes

2024-10-18 18:41 UTC, jufajardini approved these changes
<3

2024-10-18 19:35 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 23137

2024-10-20 06:26 UTC, victorjulien requested changes
memory safety issue, see inline

2024-10-20 06:26 UTC, victorjulien commented on src/output-json-tls.c
> +    bool session_resumed;
`ethernet-eve` fails this PR with an additional empty TLS event, but only on my arm7 (32bit jobs). That test just uses a `tls` setting in eve, no additional config. Turns out this field is then left uninitialized.

2024-10-20 06:26 UTC, victorjulien commented on src/output-json-tls.c
>      if (unlikely(tls_ctx == NULL))
Using SCCalloc the line above here fixes it.

2024-10-20 06:26 UTC, victorjulien commented on src/output-json-tls.c
> +    LOG_TLS_FIELD_SUBJECT |
maybe not needed, but my eyes first went here to try if this needed brackets

2024-10-20 06:26 UTC, victorjulien commented on src/output-json-tls.c
> +#define LOG_TLS_FIELD_SERVER_ALPNS      (1 << 19)
think it would be good to switch to `BIT_U64` while at it

2024-10-20 06:26 UTC, victorjulien commented on src/output-json-tls.c
> +    tls_ctx->fields = BASIC_FIELDS;
tls_ctx->session_resumed is left uninitialized here

2024-10-21 15:40 UTC, jasonish commented
Replaced by https://github.com/OISF/suricata/pull/12000.

2024-10-21 15:40 UTC, closed without merging