Remove duplicate function declarations-v5
OISF/suricata pull request #12015
Opened 2024-10-23 09:51 UTC by Nancyenos

Ticket: #7297

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7297

Describe changes:
-
-Remove duplicate function declarations
- updated commit message to include a prefix misc:
- previou pr #11998

2024-10-23 17:59 UTC, jufajardini approved these changes
Looks good to me, thanks :)

2024-10-24 07:31 UTC, victorjulien approved these changes

2024-10-24 19:05 UTC, jufajardini requested changes
While the changes here look good, a recent merge of other changes has resulted in conflicts that will have to be solved.

This can be done by rebasing your work on top of the latest changes in master.

Can you please do that and submit a new PR? :)

2024-10-24 19:16 UTC, Nancyenos commented
okay

2024-10-24 19:16 UTC, closed without merging