detect/analyzer: add more details for the tcp window keyword-v1
OISF/suricata pull request #12021
Opened 2024-10-23 21:49 UTC by Nancyenos

Ticket: 6352

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [ ] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [ ] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
-detect/analyzer: add more details for the tcp window keyword
-I need help with this, am in the right direction?
-Also am thinking of below tests and would like to know if i need to add more, i tested for exact and negated size
```
alert tcp any any -> any any (msg:"TCP window size"; window:30336; sid:1;)
alert tcp any any -> any any (msg:"TCP window size"; window:!1024; sid:42368;)
```

=

2024-10-23 22:33 UTC, jufajardini requested changes
This looks like the right approach to me, too :)

One minor change needed (a typo), please see inline comment.

The rules you've shared for the test candidates look good to me, maybe we could have one of them use `tcp.window`, instead of `window`,  just to showcase that both work.

2024-10-23 22:33 UTC, jufajardini commented on src/detect-engine-analyzer.c
> +                jb_set_bool(js, "negate", wd->negated);
```suggestion
                jb_set_bool(js, "negated", wd->negated);
```

2024-10-24 05:50 UTC, Nancyenos commented
Thankyou so much for the help @jufajardini

2024-10-24 19:08 UTC, jufajardini commented
Work continued with https://github.com/OISF/suricata/pull/12024

2024-10-24 19:08 UTC, closed without merging