detect/analyzer: add more details for the tcp window keyword-v2
OISF/suricata pull request #12024
Opened 2024-10-24 07:50 UTC by Nancyenos

Ticket: 6352

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [ ] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [ ] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
-Add more details for the tcp-window keyword
-
-

### Provide values to any of the below to override the defaults.

SV_BRANCH=

2024-10-24 11:14 UTC, inashivb commented on src/detect-engine-analyzer.c
> +            }
This is looking good. Congrats! :)
I think your suricata-verify PR needs work though

2024-10-24 19:16 UTC, jufajardini requested changes
Once the SV work is sorted, you can also rebase the work here and submit a new PR :)

2024-10-24 20:48 UTC, Nancyenos commented
> Once the SV work is sorted, you can also rebase the work here and submit a new PR :)

ok.will do

2024-10-25 14:38 UTC, Nancyenos commented
work continued in #12035

2024-10-25 14:38 UTC, closed without merging