hyperscan: add caching mechanism for hyperscan contexts v9
OISF/suricata pull request #12048
Opened 2024-10-28 17:51 UTC by lukashino

Followup of https://github.com/OISF/suricata/pull/11888

Cache Hyperscan serialized databases to disk to prevent compilation of the same databases when Suricata is run again with the same ruleset.

Loading **fresh** ET Open ruleset:  19 seconds
Loading **cached** ET Open ruleset: 07 seconds

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7170

Describe changes:
v9:
- rebase
- split HS MPM codebase into multiple files - core functions, Hyperscan MPM functions, HS caching functions
- recommitted the code
- minor tweaks from the previous PR, docs update
- made DetectEngineMpmCachingEnabled private (possible also for DetectEngineMpmCachingGetPath), but checkout v8 thread - decision needed
- some discussion threads in v8 can/should be brought up again and be decided

v7: (v6 was private)
- fix docs and add ticket number to the commit
- fix privilege drop issue, files are created after privilege drop, tested also rule reload - it worked fine 
- refactor the util-mpm-hs code, primarily prepare function 
- rebase

v5:
- rebased
- commit message update
- docs update

v4:
- rebased
- changed the default caching directory to somewhere /var/lib/suricata/cache/hs
- custom cache directory path option added
- docs added
- the default settings changed - enabled on the config generation, **disabled** when the option is not present in the config

v3
- rebased
- MPM caching is still left on by default.

v2
- improved styling to follow Suricata code styleguide
- increased cache file name length from 10 to 20 characters
- cache file name is a hash of the patterns - now only HS relevant fields are hashed - as long as the group of patterns itself is not changed then it is reused
- minor refactors
- added a safe variant of littlehash2 function
- added suricata.yaml option to enable/disable caching
- changed the storage location to the configured logging directory

v1
- initial work to cache and load Hyperscan databases from the disk

2024-10-28 20:20 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 23194

2024-11-21 18:11 UTC, victorjulien requested changes
incomplete review: noted I had some pending comments so here they are

2024-11-25 15:27 UTC, lukashino commented
> > Loading cached ET Open ruleset: 07 seconds

> 7 or 0.7 ?

7 seconds, because well it's not just loading the ruleset it's the complete Suricata startup

2025-01-14 15:37 UTC, lukashino commented
Next https://github.com/OISF/suricata/pull/12394

2025-01-14 15:37 UTC, closed without merging