TLS-JSON: Allow logging of client handshake parameters
OISF/suricata pull request #12071
Opened 2024-11-01 06:36 UTC by gtedesco-r7

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [ ] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/6695

## Description
Add a new custom log field "client_hello" which logs the following:
1. TLS extensions, excluding GREASE, SNI and ALPN
2. All cipher suites, excluding GREASE
3. All signature algorithms, excluding GREASE

The use-case is for logging TLS handshake parameters in order to survey them, and so that JA4 hashes can be computed offline (in the case that they're not already computed for the purposes of rule matching).

My questions are:
- should we exclude grease/SNI/ALPN or keep them in...
- is this schema acceptable? or should I flatten it out?
- in future should we looking at moving more things into rust, eg. put ALPNs and other parameters there to avoid duplication between C and rust structs, and have rust become something a "TLS handshake" struct, which can compute a JA3 or a JA4 as needed? It seems to me like that would simplify a lot and maximise the amount of safe code

2024-11-28 08:31 UTC, catenacyber commented
Thanks for the work.

Some quick remarks even if the review is not complete but still giving you some feedback :
- commit title should rather be output/tls than `TLS/JSON`
- Why only client ? Why not do server extensions as well ?
- Miss a suricata-verify test ⚠️ 
- Does this work if ja4 is disabled ? (I do not think so but maybe it should be independent)

> should we exclude grease/SNI/ALPN or keep them in...

Grease maybe... Why do you exclude SNI and ALPN ?

> is this schema acceptable? or should I flatten it out?

Looks good, but should have an update in etc/schema.json

> in future should we looking at moving more things into rust, eg. put ALPNs and other parameters there to avoid duplication between C and rust structs, and have rust become something a "TLS handshake" struct, which can compute a JA3 or a JA4 as needed? It seems to me like that would simplify a lot and maximise the amount of safe code

Generally speaking, we want most code in rust, and hope to put all TLS code in rust some day but that is a huge effort...

2024-11-28 08:31 UTC, catenacyber requested changes
Needs at least a suricata-verify test

2024-12-02 08:35 UTC, catenacyber commented
Good, waiting on the next version then

2024-12-02 11:12 UTC, victorjulien commented
I think I would reorg the priorities to:

0. SV test
1. Fixes: Change commit title, fix SV tests, add schema, etc..
2. Make it all work even when JA4 is disabled
3. Add server support

Putting server last as we can already have value w/o the server side, right? Feels like it could be a follow up effort to also keep this effort relatively small and easier to handle.

2025-01-27 15:52 UTC, catenacyber commented
Friendly ping @gtedesco-r7 will you be working back on this ?

2025-01-28 12:11 UTC, rmcconnell-r7 commented
Hey @catenacyber - we are currently making an effort to create a V2 for this, yeah.

2025-01-29 14:09 UTC, catenacyber commented
Replaced by #12501

2025-01-29 14:09 UTC, closed without merging