Decouple stream bypass from TLS encrypted bypass v6
OISF/suricata pull request #12082
Opened 2024-11-03 20:50 UTC by lukashino

Following up on https://github.com/OISF/suricata/pull/11886

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6788

Describe changes:
v6
- rebased 

v5
- rebased
- added upgrade section
- fixed docs - Thanks Juliana
- SV tests should pass now

v4
- rebased
- changed SSH bypass defaults to hopefully be in sync with the previous settings

v3
- added SSH app-layer option `encryption-handling` allowing to choose whether to continue inspection on SSH once it turns encrypted
- added SV tests
- minor docs updates

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2114

2024-11-03 23:15 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on SURI_TLPR1_alerts_cmp.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .app_layer.flow.dcerpc_tcp | 40 | 42 | 105.0% | 

Pipeline 23244

2024-11-04 08:46 UTC, lukashino commented
^ This should get a rerun, kinda weird that it didn't bypass dcerpc where that should not be affected by the PR at all - my assumption is that dcerpc_tcp runs unencrypted.

2024-11-04 12:03 UTC, victorjulien requested changes
see inline

2024-11-04 12:03 UTC, victorjulien commented on rust/src/ssh/ssh.rs
> +fn enc_bypass_is_enabled() -> bool {
style: here and beyond, lets replace `enc` with `encrypt` or `encryption` for readability.

2024-11-04 12:03 UTC, victorjulien commented on src/app-layer-ssh.c
> +            if (strcmp(enc_handle->val, "full") == 0) {
"full" to me means `APP_LAYER_PARSER_NO_INSPECTION` isn't set either. It just means full processing and inspection of the rest of the flow even if encrypted phase has started

2024-11-04 12:03 UTC, victorjulien commented on suricata.yaml.in
> +      # - full:    keep tracking and inspection as normal
not what the code does, see above

2024-11-04 15:50 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 23247

2024-12-08 22:43 UTC, lukashino commented
continues in https://github.com/OISF/suricata/pull/12249

2024-12-08 22:43 UTC, closed without merging