detect: don't run pkt sigs on ffr pkts
OISF/suricata pull request #12095
Opened 2024-11-07 14:29 UTC by victorjulien

Last packet from the TLS TCP session moves TCP state to CLOSED.

This flags the app-layer with APP_LAYER_PARSER_EOF_TS or APP_LAYER_PARSER_EOF_TC depending on the direction of the final packet. This flag will just have been set in a single direction.

This leads to the last packet updating the inspect id in that packets direction.

At the end of the TLS session a pseudo packet is created, because:
 - flow has ended
 - inspected tx id == 0, for at least one direction
 - total txs is 1

Then a packet rule matches:

```
alert tcp any any -> any 443 (flow: to_server;                  \
        flowbits:isset,tls_error;                               \
        sid:09901033; rev:1;                                    \
        msg:"Allow TLS error handling (outgoing packet)"; )
```

The `SIG_MASK_REQUIRE_REAL_PKT` is not preventing the match, as the `flowbits` keyword doesn't set it.

To avoid this match. This patch skips signatures of the `SIG_TYPE_PKT` for flow end packets.

Ticket: #7318.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2121

2024-11-07 16:50 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 23284

2024-11-18 14:19 UTC, catenacyber commented
@jufajardini can you remind me what `SIG_TYPE_PKT` are ?
Are we here with the default case in `SignatureSetType` ? (because signature uses flowbits only)
Are there other cases besides flowbits (and flowints I suppose) where we get `s->type == SIG_TYPE_PKT` without `SIG_MASK_REQUIRE_REAL_PKT` ?

2024-11-18 14:53 UTC, catenacyber commented
Should it work the same for `SIG_TYPE_APPLAYER` ?
That is 
```
alert tls any any -> any 443 (flow: to_server;                  \
        flowbits:isset,tls_error;                               \
        sid:09901033; rev:1;                                    \
        msg:"Allow TLS error handling (outgoing packet)"; )
```

using tls in rule's alproto instead of tcp

2024-11-22 13:53 UTC, victorjulien commented
> Should it work the same for `SIG_TYPE_APPLAYER` ? That is
> 
> ```
> alert tls any any -> any 443 (flow: to_server;                  \
>         flowbits:isset,tls_error;                               \
>         sid:09901033; rev:1;                                    \
>         msg:"Allow TLS error handling (outgoing packet)"; )
> ```
> 
> using tls in rule's alproto instead of tcp

That won't lead to a `SIG_TYPE_APPLAYER` rule. IIRC currently the only rule that would lead to `SIG_TYPE_APPLAYER` is something like: `alert tls any any -> any any (sid:1;)`. Any inspect engine or general match condition will make it a different type.

A `SIG_TYPE_APPLAYER` does act mostly like a `SIG_TYPE_PKT` rule, with the exception that it applies the rule action to the flow instead of just the packet.

There are several SV tests that fail if I include `SIG_TYPE_APPLAYER` in the check here, so that would mean another behavior change.

2024-11-25 08:42 UTC, inashivb commented
The patch makes sense to me but,
I still do not understand why is it ok at this point to have TLS parser tell total txs == 1, when there are no txs and the flow has ended.. 🥲

2024-11-25 16:16 UTC, jasonish commented
> The patch makes sense to me but, I still do not understand why is it ok at this point to have TLS parser tell total txs == 1, when there are no txs and the flow has ended.. 🥲

With the PCAP from the initial report, the handshake was not complete.  So it actually makes sense that the 1, and only 1 transaction on TLS would still be considered active on flow close.. However, I think the check could be made smarter to check the state of the transaction before always returning 1. However, in the specific PCAP the behaviour is correct I think.

2024-11-26 05:38 UTC, inashivb commented
> > The patch makes sense to me but, I still do not understand why is it ok at this point to have TLS parser tell total txs == 1, when there are no txs and the flow has ended.. 🥲
> 
> With the PCAP from the initial report, the handshake was not complete. So it actually makes sense that the 1, and only 1 transaction on TLS would still be considered active on flow close.. However, I think the check could be made smarter to check the state of the transaction before always returning 1. However, in the specific PCAP the behaviour is correct I think.

I had totally missed the handshake failure. Thanks for explaining! 🙇🏽‍♀️ 
+1 to making the state of transaction reported by TLS parser smarter.

2024-11-27 14:59 UTC, catenacyber requested changes
Thanks for the work, almost good except SV test 

CI : ✅
Code : good
Commits segmentation : ok
Commit messages : good
Git ID set : looks fine for me
CLA : you already contributed
Doc update : @jufajardini should there be a doc update about signature type packet not matching on pseudo packets ?
Redmine ticket : ok
Rustfmt : no rust
Tests : SV PR is failing for 7 🔴 
Dependencies added: none

@jufajardini where can we find your presentation about signature types ?

2024-11-27 15:40 UTC, jufajardini commented
> Thanks for the work, almost good except SV test
> 
> CI : ✅ Code : good Commits segmentation : ok Commit messages : good Git ID set : looks fine for me CLA : you already contributed Doc update : @jufajardini should there be a doc update about signature type packet not matching on pseudo packets ? Redmine ticket : ok Rustfmt : no rust Tests : SV PR is failing for 7 🔴 Dependencies added: none
> 
> @jufajardini where can we find your presentation about signature types ?

Working on a new version of the PR atm. I'll take into account your comments here to try to add more examples. Current it this: https://github.com/OISF/suricata/pull/12114

I'll share a pdf with the presentation with you, as I think we haven't published those yet.

2024-11-27 15:44 UTC, jufajardini commented
> Doc update : @jufajardini should there be a doc update about signature type packet not matching on pseudo packets ? 

I'll add something about this to the new docs.

2024-11-27 20:14 UTC, catenacyber commented
Thanks Juliana

Why is a rule with flowbits a packet type ?
Because it is the default type if we have a keyword (not IP only) and it is not app-layer transaction ?

2024-11-27 20:17 UTC, victorjulien commented
> Thanks Juliana
> 
> Why is a rule with flowbits a packet type ? Because it is the default type if we have a keyword (not IP only) and it is not app-layer transaction ?

Flowbits can change per packet, at least in theory. The flowbits analysis isn't sophisticated enough to see if this is true.

2024-11-28 11:14 UTC, victorjulien commented
#12169 plus https://github.com/OISF/suricata-verify/pull/2148 shows what it could look like with `SIG_TYPE_APPLAYER` included.

2024-12-10 09:08 UTC, catenacyber commented
Rebased in https://github.com/OISF/suricata/pull/12257 with good SV test

2024-12-10 09:08 UTC, closed without merging