Dev/ldap v0.2: small improvements to the LDAP parser
OISF/suricata pull request #12119
Opened 2024-11-13 15:33 UTC by chifflier

## Contribution style:
- [X] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [X] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [NA] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [NA] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [NA] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Describe changes:

This pull request does minor changes to the LDAP app-layer:
- add port 3268 to the default monitored ports. This port is used by ActiveDirectory for global operations (not local to the current domain)
- Add support for the STARTTLS extended operation, so now the TLS handshake (and the Certificate) can be inspected and logged. It also takes care to check if STARTTLS succeeds, to avoid errors.

The STARTTLS work will have a matching PR in suricata-verify

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2128

2024-11-13 15:40 UTC, chifflier commented
> Do you have pcaps for this to add to our SV tests?

Yes! see https://github.com/OISF/suricata-verify/pull/2128

2024-11-14 08:34 UTC, victorjulien commented
Can you reference https://redmine.openinfosecfoundation.org/issues/7394 in the starttls commit?

Format (on its own line):
`Ticket: #7394.`

2024-11-14 18:53 UTC, victorjulien requested changes
as discussed in person, there will be a new revision

2024-11-14 18:54 UTC, victorjulien commented
> > Do you have pcaps for this to add to our SV tests?
> 
> Yes! see [OISF/suricata-verify#2128](https://github.com/OISF/suricata-verify/pull/2128)

Can you add the SV branch in the PR body like so:
```
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2128
```
Then CI will use it. The interface will make it a clickable link (like how it is now in this PR)

2024-11-26 15:32 UTC, chifflier commented
Replaced by https://github.com/OISF/suricata/pull/12152

2024-11-26 15:32 UTC, closed without merging