transform: luaxform transform script
OISF/suricata pull request #12211
Opened 2024-12-03 13:57 UTC by jlucovsky

Continuation of #12187

Add the `luaxform` transform that uses a Lua script to receive and transform a sticky buffer.

Lua transforms receive arguments
- (always): length of input buffer and input buffer
- (always): number of additional arguments (may be 0)
- (when present): argument array (bounded by argument count)

Arguments are passed to the Lua script as they appear in the rule:
```
 luaxform:./lua/lua-transform.lua, bytes 4, offset 13, hash sha256;
 ```
 When the transform is invoked, 3 additional arguments are passed (arg count will be 3)
- `bytes 4`
- `offset 13`
- `hash sha256`

The Lua script is responsible for parsing and using the arguments and returning a tuple: `output-buffer, output-buffer-byte-count`

I used this Lua script:
```
function init (args)
  -- Optional, no return value
end

function transform(input_len, input, argc, args)
    SCLogNotice("Input length: " .. input_len .. " arg-count: " .. argc)
    for i = 1, argc do
        print("Argument " .. i .. ":", args[i])
    end
    return string.upper(input), input_len
end

return 0
```

Example rule using the Lua script:
```
alert http any any -> any any (msg:"Lua Xform example"; flow:established;  file.data; luaxform:./lua/lua-transform.lua; content: "abc"; sid: 1;)
```
Link to ticket: https://redmine.openinfosecfoundation.org/issues/2290

Describe changes:
- Luaxform transform changes

Updates
- Rebase

### Provide values to any of the below to override the defaults.

- To use an LibHTP, Suricata-Verify or Suricata-Update pull request,
  link to the pull request in the respective `_BRANCH` variable.
- Leave unused overrides blank or remove.

SV_REPO=
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2090
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2024-12-03 17:45 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 23651

2024-12-05 14:16 UTC, jufajardini requested changes
Sorry for taking so long to get back to reviewing this... >_<

2024-12-05 14:16 UTC, jufajardini commented on doc/userguide/rules/transforms.rst
> +       return string.upper(sub)
Tried to test this script, but failed. Compared with https://github.com/OISF/suricata-verify/pull/2090/files#diff-86d8335380df431e0f206e1735863fbf40088a75554a65682b9e23a481168414 and I think it's missing:
```suggestion
       return string.upper(sub), bytes
```

2024-12-08 14:27 UTC, jlucovsky commented
Continued in #12246

2024-12-08 14:27 UTC, closed without merging