src: remove unused struct fields
OISF/suricata pull request #12299
Opened 2024-12-17 20:39 UTC by catenacyber

Link to ticket: https://redmine.openinfosecfoundation.org/issues/
None, just a simple cleanup

Describe changes:
- src: remove unused struct fields

What about `counter_tcp_pseudo_failed` ?

2024-12-17 20:48 UTC, victorjulien commented
> What about counter_tcp_pseudo_failed ?

Never incremented it seems, so it can be removed.

2024-12-18 04:45 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 23983

2024-12-18 07:20 UTC, victorjulien approved these changes

2025-01-04 18:34 UTC, victorjulien requested changes
Scan-build is unhappy.

2025-01-07 13:03 UTC, catenacyber commented
Next in https://github.com/OISF/suricata/pull/12345

2025-01-07 13:03 UTC, closed without merging