DPDK rte_flow rules RSS support for more NICs - v2
OISF/suricata pull request #12317
Opened 2024-12-21 14:41 UTC by adaki4

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7337

Previous PR https://github.com/OISF/suricata/pull/12315

Describe changes:
v2
- expand on individual commit messages
- change "ifs" to "else ifs" in DevicePostStartPMDSpecificActions() in source-dpdk.c
- remove unused RSS hash key configuration from util-dpdk-ice.c
- change RSS hash function to RTE_ETH_HASH_FUNCTION_SYMMETRIC_TOEPLITZ (was RTE_ETH_HASH_FUNCTION_TOEPLITZ) in util-dpdk-ice.c

v1
- move the base of rte_flow rules RSS configuration from util-dpdk-i40e.c to separate file
- add rte_flow rules RSS configuration for mlx5, ixgbe and ice drivers (only i40e until now)
- until now i40e hashed packets by 5 tuple, now (also other mentioned drivers) hash by ip src and ip dst only.

Ticket: [#7337](https://redmine.openinfosecfoundation.org/issues/7337)

2025-01-04 12:59 UTC, victorjulien requested changes
Some minor comments inline.

@lukashino can you review the logic?

2025-01-04 12:59 UTC, victorjulien commented on src/util-dpdk-ice.c
> +            SCLogError("Unable to flush rte_flow rules of %s: %s Flush error msg: %s", port_name,
I would like to see all error messages use a pattern of
`0000:XXXX: unable to ...`, so use the interface identifier as a prefix.

2025-01-04 12:59 UTC, victorjulien commented on src/util-dpdk-rss.c
> +int DeviceSetRSSFlowQueues(int port_id, const char *port_name, struct rte_flow_action_rss rss_conf)
these are public functions using the `Device` prefix. I think we need a `Dpdk` prefix here, as `Device` has another meaning in our codebase.

2025-01-06 12:34 UTC, adaki4 commented on src/util-dpdk-ice.c
> +            SCLogError("Unable to flush rte_flow rules of %s: %s Flush error msg: %s", port_name,
Okay, I will also update SCLogDebugs in src/util-dpdk-rss.c to match this pattern.

2025-01-06 18:20 UTC, lukashino commented
I internally reviewed this before but I'll give it one more pass. Most of my comments were addressed. I'll also individually test it to make sure everything works.

2025-01-12 17:57 UTC, lukashino requested changes
[56025 - W#01-af:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#01-af:00.1) received packets 1200
[56026 - W#02-af:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#02-af:00.1) received packets 0
[56027 - W#03-af:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#03-af:00.1) received packets 0
[56028 - W#04-af:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#04-af:00.1) received packets 0
[56029 - W#01-19:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#01-19:00.1) received packets 602
[56030 - W#02-19:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#02-19:00.1) received packets 198
[56031 - W#03-19:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#03-19:00.1) received packets 198
[56032 - W#04-19:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#04-19:00.1) received packets 202
[56033 - W#01-3b:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#01-3b:00.1) received packets 602
[56034 - W#02-3b:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#02-3b:00.1) received packets 198
[56035 - W#03-3b:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#03-3b:00.1) received packets 198
[56036 - W#04-3b:00.1] 2025-01-12 18:55:33 Perf: dpdk: (W#04-3b:00.1) received packets 202

The testing shows that the `ice` card is not distributing the traffic correctly. Tested on DPDK v22.11.1

2025-01-12 19:31 UTC, lukashino commented
Otherwise, the changes look good to me.

2025-01-14 22:08 UTC, lukashino commented
# Testing a follow-up v3 version leads to: 

## DPDK v19.11.14 from dpdk-stable:

[115716 - W#01-af:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#01-af:00.1) received packets 500
[115717 - W#02-af:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#02-af:00.1) received packets 502
[115718 - W#03-af:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#03-af:00.1) received packets 100
[115719 - W#04-af:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#04-af:00.1) received packets 98
[115720 - W#01-19:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#01-19:00.1) received packets 200
[115721 - W#02-19:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#02-19:00.1) received packets 200
[115722 - W#03-19:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#03-19:00.1) received packets 600
[115723 - W#04-19:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#04-19:00.1) received packets 200
[115724 - W#01-3b:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#01-3b:00.1) received packets 602
[115725 - W#02-3b:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#02-3b:00.1) received packets 198
[115726 - W#03-3b:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#03-3b:00.1) received packets 198
[115727 - W#04-3b:00.1] 2025-01-14 22:26:50 Perf: dpdk: (W#04-3b:00.1) received packets 202

ice driver behaves a bit odd, the distribution is a bit weird. 

Though, on an unrelated note, Mellanox driver seems to have issues:
```
...
net_mlx5: port 2 unable to disable interrupt on Rx queue 1                                        
net_mlx5: port 2 unable to disable interrupt on Rx queue 3                                                                                                                           
net_mlx5: port 2 unable to disable interrupt on Rx queue 2                                   
net_mlx5: port 2 unable to disable interrupt on Rx queue 0
...
```

## DPDK 20.11.10:

i40e not working, complaining about rte_flow rule:

```
Perf: dpdk: 0000:19:00.1: NIC is on NUMA 0, thread on NUMA 1 [ReceiveDPDKThreadInit:source-dpdk.c:619]                                                                                                            
Perf: threads: Setting prio 0 for thread "W#04-19:00.1" to cpu/core 8, thread id 150355 [TmThreadSetupOptions:tm-threads.c:883]                                                                                   
Error: dpdk-rss: 0000:19:00.1: rte_flow rule creation error: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:157]                                                                                               
Error: dpdk-rss: 0000:19:00.1: rte_flow rule validation error: Invalid argument, errmsg: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:160]                                                                   
Error: dpdk-rss: 0000:19:00.1: rte_flow rule creation error: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:157]                                                                                                Error: dpdk-rss: 0000:19:00.1: rte_flow rule validation error: Invalid argument, errmsg: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:160]
Error: dpdk-rss: 0000:19:00.1: rte_flow rule creation error: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:157]                                                                                                Error: dpdk-rss: 0000:19:00.1: rte_flow rule validation error: Invalid argument, errmsg: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:160]
Error: dpdk-rss: 0000:19:00.1: rte_flow rule creation error: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:157]                                                                                                Error: dpdk-rss: 0000:19:00.1: rte_flow rule validation error: Invalid argument, errmsg: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:160]
Error: dpdk-rss: 0000:19:00.1: rte_flow rule creation error: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:157]                                                                                                Error: dpdk-rss: 0000:19:00.1: rte_flow rule validation error: Invalid argument, errmsg: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:160]
Error: dpdk-rss: 0000:19:00.1: rte_flow rule creation error: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:157]                                                                                               
Error: dpdk-rss: 0000:19:00.1: rte_flow rule validation error: Invalid argument, errmsg: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:160]                                                                   
Error: dpdk-rss: 0000:19:00.1: rte_flow rule creation error: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:157]
Error: dpdk-rss: 0000:19:00.1: rte_flow rule validation error: Invalid argument, errmsg: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:160]                                                                   
Error: dpdk-rss: 0000:19:00.1: rte_flow rule creation error: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:157]                                                                                               
Error: dpdk-rss: 0000:19:00.1: rte_flow rule validation error: Invalid argument, errmsg: invalid pctype [DPDKCreateRSSFlow:util-dpdk-rss.c:160]
Warning: dpdk: 0000:19:00.1: NIC is on NUMA 0, 2 threads on different NUMA node(s) [ReceiveDPDKThreadInit:source-dpdk.c:649] 
```

[150348 - W#01-af:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#01-af:00.1) received packets 602
[150349 - W#02-af:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#02-af:00.1) received packets 198
[150350 - W#03-af:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#03-af:00.1) received packets 198
[150351 - W#04-af:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#04-af:00.1) received packets 202
[150352 - W#01-19:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#01-19:00.1) received packets 1200
[150353 - W#02-19:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#02-19:00.1) received packets 0
[150354 - W#03-19:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#03-19:00.1) received packets 0
[150355 - W#04-19:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#04-19:00.1) received packets 0
[150356 - W#01-3b:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#01-3b:00.1) received packets 602
[150357 - W#02-3b:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#02-3b:00.1) received packets 198
[150358 - W#03-3b:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#03-3b:00.1) received packets 198
[150359 - W#04-3b:00.1] 2025-01-14 22:36:49 Perf: dpdk: (W#04-3b:00.1) received packets 202

## DPDK 21.11.8

Works ok. 

## DPDK 22.11.6 

Works ok.

## DPDK 23.11.x (installed from the global repo)

Works ok.

## DPDK 24.11.1

Works ok.

2025-01-23 15:32 UTC, adaki4 commented
Continues in #12458

2025-01-23 15:32 UTC, closed without merging