analysis: report rule state altered by other rule
OISF/suricata pull request #12311
Opened 2024-12-20 02:27 UTC by jufajardini

Flowbits can make a rule such as a packet rule be treated as a stateful rule, without actually changing the rule type.

Add a flag to allow reporting such cases via engine analysis.

Task #7456

Link to ticket: https://redmine.openinfosecfoundation.org/issues/
https://redmine.openinfosecfoundation.org/issues/7456

Previous PR: https://github.com/OISF/suricata/pull/12286

Output samples:
`flowbits:set` rule
```json
{
  "raw": "alert http any any -> any any (msg:\"Setting flowbit fb2, app_tx rule\";http.uri;content:\"something\";flowbits:set,fb2;sid:1901;)",
  "id": 1901,
  "gid": 1,
  "rev": 0,
  "msg": "Setting flowbit fb2, app_tx rule",
  "app_proto": "http_any",
  "requirements": [
    "flow"
  ],
  "type": "app_tx",
  "rule_state_dependant": false,
}
```

`flowbits:isset` rule
```json
{
  "raw": "alert ip any any -> any any (msg:\"Is-Setting flowbit fb2, pkt rule\";flowbits:isset,fb2;sid:1904;)",
  "id": 1904,
  "gid": 1,
  "rev": 0,
  "msg": "Is-Setting flowbit fb2, pkt rule",
  "app_proto": "unknown",
  "requirements": [
    "flow"
  ],
  "type": "pkt",
  "rule_state_dependant": {
    "rule_depends_on_sid": 1901,
    "rule_depends_on_flowbit": "fb2"
  },
}
```

Describe changes:
- besides indicating that there is a dependency, indicate
- what flowbit causes it
- what is the rule id setting said flowbit
- I've tried to keep the `init_data` mostly generic, in case there are other scenarios where this could happen - but at least when it's time to report this via the `engine-analysis`, we need the info to fetch the variable name
- I've removed/ discarded the idea of showing a counter of other signatures also affecting, as it's basically only the `set` command that does that, from what I could understand

### Provide values to any of the below to override the defaults.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2201

2024-12-20 05:45 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 24033

2024-12-20 06:19 UTC, inashivb reviewed
Wondering why don't we try and combine the output of `flowbits.json` or make that one more rich perhaps and point to the state event to look at in there somehow w one field in the `rules.json` output?

2024-12-20 09:26 UTC, victorjulien commented on src/detect.h
> +    uint32_t rule_state_variable_idx;
I think this is fine. This is an init-time only helper struct

2024-12-20 09:31 UTC, victorjulien commented on src/detect-engine-analyzer.c
> +        jb_set_string(ctx.js, "rule_depends_on_flowbit",
can this just be `flowbit`? Seems the key is a bit redundant with the object name.

Also, as Shivani is asking: this is 1-N essentially, can we list them all? I'm changing my mind a bit on this. I think being complete is probably best.

So
```json
"rule_state_dependant": {
    "sids": [ 1901, 124, 666 ],
    "flowbits": [ "fb2", "abc" ],
},
```

2025-01-03 17:45 UTC, jufajardini commented on src/detect-engine-analyzer.c
> +        jb_set_uint(ctx.js, "rule_depends_on_sid", s->init_data->rule_state_dependant_id);
> what if there are multiple dependencies?

I thought of that at first, but from what I understood, only one rule can `set` a flowbits variable, isn't that so?

2025-01-03 17:48 UTC, jufajardini commented on src/detect-engine-analyzer.c
> +        jb_set_string(ctx.js, "rule_depends_on_flowbit",
I thought only one rule could `set` a flowbits rule, that's why I used this approach. Given that that's not the case, it's a bit more complicated to be done, but I'll follow that approach. I'll pursue understanding Shivani's comment about `flowbits.json` and see if that helps, too, somehow.

2025-01-07 08:08 UTC, inashivb commented on src/detect-engine-analyzer.c
> +        jb_set_uint(ctx.js, "rule_depends_on_sid", s->init_data->rule_state_dependant_id);
I think a rule is only "dependent" on a certain rule or flowbit when you're checking whether a flowbit was set so essentially the `isset` command. `set` does not mean the rule is dependent.
1. Combinations of `isset` that can show you multiple dependencies are as follows. Assume `fb1` was set by `sid: 1` and `fb2` was set by `sid: 2`
`and` support: `flowbits: isset, fb1; flowbits: isset, fb2;` -> dependent on `sid:1` and `sid: 2`.
`or` support: `flowbits: isset, fb1|fb2;` -> also dependent on `sid:1` and `sid: 2`.
2. Suricata does not seem to have a reservation against two different rules setting a flowbit so maybe there are usecases for that too. So, yes, there can be multiple rules setting the same flowbit.

2025-01-07 08:09 UTC, inashivb commented on src/detect-engine-analyzer.c
> +        jb_set_string(ctx.js, "rule_depends_on_flowbit",
>  I'll pursue understanding Shivani's comment about flowbits.json and see if that helps, too, somehow.

From what I got from Victor's comment, I think your approach is what we want so you can skip that :)

2025-01-28 18:40 UTC, jufajardini commented
> So, what is the outcome of the review ?

A new version will be shared today or tomorrow.

2025-01-28 21:39 UTC, catenacyber requested changes
So, changes are requested and coming

2025-01-31 02:28 UTC, jufajardini commented
Replaced by: https://github.com/OISF/suricata/pull/12515

2025-01-31 02:28 UTC, closed without merging

2025-01-31 02:29 UTC, jufajardini commented on src/detect-engine-analyzer.c
> +        jb_set_string(ctx.js, "rule_depends_on_flowbit",
you were actually right, thanks for the explanations and feedback :)