Datajson v3.1
OISF/suricata pull request #12319
Opened 2024-12-22 20:24 UTC by regit

Update of #12289.

This is a major functional upgrade and it also has code organization update as most datajson code is now in its own files to limit the size of file like datasets.c that was becoming really complicated to manage.

On the functional side, there is a new feature that changes the scope of the original proposal.

There is a lot of tools were the IOCs are published in a format like the following:
```JSON
{
  "info": {
    "threat": [
      {
        "context": "gold old test",
        "year": 2005,
        "host": {
          "fqdn": "www.testmyids.com",
          "domain": "testmyids.com"
        }
      },
      {
        "context": "not old test",
        "year": 2015,
        "host": {
          "fqdn": "www.testmyids.org",
          "domain": "testmyids.org"
        }
      },
      {
        "context": "old test",
        "year": 2023,
        "host": {
          "domain": "testmyids.com"
        }
      }
    ]
  }
}
```
There is a object containing an array and in this array, we have one object per IOC and some of the key contains the IOC we want to inject in the Suricata.

The feature update consists in giving the capabilities to directly handle this type of data in Suricata. To do so, 2 options have been added:
- json_key to known which key contains the value to inject in dataset
- array_key to indicate where the array is

In the previous example, we can use it with the following match:

```
http.host; datajson:isset,nk,type string,load hosts-nested-key.json,key nk, json_key host.fqdn, array_key info.threat;
```

A signature with this match will then produce something like:

```JSON
 "alert": {
     "extra": {
         "nk":  {
            "context": "gold old test",
            "year": 2005,
            "host": {
              "fqdn": "www.testmyids.com",
               "domain": "testmyids.com"
            }
        }
   }
}
```

The previous data format has been kept  and this new one is thus an additional choice to the user. The advantage is that it does not require post processing to inject the data in Suricata which should be convenient for most users.

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [x] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

Describe changes:
- add additional data format
- document new data format
- move code to dedicated files
- rebase the code

SV_BRANCH=https://redmine.openinfosecfoundation.org/issues/7372

2024-12-22 20:30 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 24045

2024-12-22 20:40 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 24046

2024-12-22 23:08 UTC, jasonish commented
I modified the PR description to fix the SV branch and restarted the checks.

2024-12-23 07:16 UTC, regit commented
> I modified the PR description to fix the SV branch and restarted the checks.

Sorry I missed that again.

2024-12-23 07:20 UTC, inashivb commented
@regit there are some build errors in the CI checks as well. Have you looked at them?

2024-12-23 08:22 UTC, regit commented
> @regit there are some build errors in the CI checks as well. Have you looked at them?

Indeed going to fix that

2024-12-23 08:39 UTC, regit commented
Setting to draft as it needs some more love but I would be happy to get feedback on the concept.

2024-12-23 11:55 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 24048

2024-12-23 20:55 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 24049

2024-12-24 08:15 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on build_asan.
  

Pipeline 24050

2024-12-24 17:00 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 139 | 145 | 104.32% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 623 | 643 | 103.21% | 

Pipeline 24052

2024-12-27 22:50 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on SURI_TLPW2_autofp_suri_time.

ERROR: QA failed on SURI_TLPR1_suri_time.
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 139 | 144 | 103.6% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 623 | 645 | 103.53% | 

Pipeline 24054

2025-01-29 20:06 UTC, catenacyber requested changes
This needs at least a rebase to get a clean version.

> There is a lot of tools were the IOCs are published in a format like the following:

Is this a standard ?
I used to have rather a context associated with a list of elements like
```
    "threat": [
      {
        "context": "bad",
        "domains": ["toto.com", "badtoto.fr"]
      },
      {
        "context": "evilAPT",
        "domains": ["aptcnc.com", "fallback.com"]
      },
```

2025-03-02 16:21 UTC, regit commented
So the dataset parsing code has been moved to rust. OK, it looks like you really hate me.

2025-03-02 20:51 UTC, regit commented
Rebased.

2025-03-02 20:51 UTC, closed without merging

2025-03-03 11:00 UTC, inashivb commented
> So the dataset parsing code has been moved to rust. OK, it looks like you really hate me.

I did wonder why Victor asked for it. 😜