DPDK rte_flow rules RSS support for more NICs - v1
OISF/suricata pull request #12315
Opened 2024-12-20 16:35 UTC by adaki4

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/7337

Describe changes:
- move the base of rte_flow rules RSS configuration from util-dpdk-i40e.c to separate file
- add rte_flow rules RSS configuration for mlx5, ixgbe and ice drivers (only i40e until now)
- until now i40e hashed packets by 5 tuple, now (also other mentioned drivers) hash by ip src and ip dst only.

These changes were made for future support of more rte_flow rules (e.g. vxlan or nvgre header hardware offload) that can be chained on certain NICs via certain rte_flow attributes. 

Ticket: [#7337](https://redmine.openinfosecfoundation.org/issues/7337)

2024-12-20 18:27 UTC, victorjulien requested changes
I would like to see a bit more explanation in the commit messages about what these flow rules do. Right now it seems to expect quite in-depth knowledge to be able to understand them.

2024-12-20 18:27 UTC, victorjulien commented on src/source-dpdk.c
> +    if (strcmp(driver_name, "net_ixgbe") == 0)
nit: should be else if's

2024-12-21 10:22 UTC, adaki4 commented on src/source-dpdk.c
> +    if (strcmp(driver_name, "net_ixgbe") == 0)
Sure, I can change that.

2024-12-21 14:43 UTC, adaki4 commented
Continues in https://github.com/OISF/suricata/pull/12317

2024-12-21 14:43 UTC, closed without merging