Add clang tidy
OISF/suricata pull request #12322
Opened 2024-12-27 08:19 UTC by regit

This patchset adds a .clang-tidy file. It will be used by clangd to provide additional diagnostics in the code.

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [x] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [x] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/3837

Describe changes:
- Add clang-tidy file
- Fix a thread safety warning to be able to use concurrency checks

2024-12-27 10:45 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 24053

2024-12-27 20:49 UTC, regit commented
There is a build issue on non Linux. Cooking a fix.

2025-01-10 15:54 UTC, victorjulien commented
I'm looking at how I can test this, and I'm struggling to make it work w/o getting flooded with warnings.

E.g. trying a single file
```
clang-tidy --quiet src/suricata.c -- -I. -Isrc -I rust/gen|head
5773 warnings and 20 errors generated.
Error while processing /home/victor/sync/devel/eidps/src/suricata.c.
error: too many errors emitted, stopping now [clang-diagnostic-error]
/home/victor/sync/devel/eidps/src/conf.h:85:1: error: unknown type name 'bool' [clang-diagnostic-error]
   85 | bool ConfNodeHasChildren(const ConfNode *node);
      | ^
/home/victor/sync/devel/eidps/src/flow-queue.h:28:10: warning: circular header file dependency detected while including 'flow.h', please check the include path [misc-header-include-cycle]
   28 | #include "flow.h"
      |          ^
/home/victor/sync/devel/eidps/src/flow.h:537:10: note: 'flow-queue.h' included from here
  537 | #include "flow-queue.h"
      |          ^
```

2025-01-10 19:37 UTC, regit commented
> I'm looking at how I can test this, and I'm struggling to make it work w/o getting flooded with warnings.
> 
> E.g. trying a single file
> ```
> clang-tidy --quiet src/suricata.c -- -I. -Isrc -I rust/gen|head
> 5773 warnings and 20 errors generated.
> Error while processing /home/victor/sync/devel/eidps/src/suricata.c.
> error: too many errors emitted, stopping now [clang-diagnostic-error]
> /home/victor/sync/devel/eidps/src/conf.h:85:1: error: unknown type name 'bool' [clang-diagnostic-error]
>    85 | bool ConfNodeHasChildren(const ConfNode *node);
>       | ^
> /home/victor/sync/devel/eidps/src/flow-queue.h:28:10: warning: circular header file dependency detected while including 'flow.h', please check the include path [misc-header-include-cycle]
>    28 | #include "flow.h"
>       |          ^
> /home/victor/sync/devel/eidps/src/flow.h:537:10: note: 'flow-queue.h' included from here
>   537 | #include "flow-queue.h"
>       |          ^
> ```

I'm not using it in the command line but via the editor. If you have LSP via clangd activated (should be the default), it is going to pick the clang-tidy file without configuration and add some analysis to the file as warning.

2025-01-10 21:31 UTC, victorjulien commented
Hmm I would really like to figure out how else it can be made useful. If the clangd method can work, it should also be usable directly somehow.

2025-01-11 19:38 UTC, regit commented
> Hmm I would really like to figure out how else it can be made useful. If the clangd method can work, it should also be usable directly somehow.

Discovered 2 things:
- clang-tidy displays the total number of warnings for the directory
- there is some checks used only in clang-tidy and not through clangd

After small fixes on non accurate fixes, we have around 76 warnings in suricata.c.

2025-01-11 21:32 UTC, regit commented
@victorjulien I've pushed some more commits on top of the MR. I've played a bit with the `--fix` option of clang-tidy and it produces some interesting patches.

There is some checks that we could disable but I wanted you and the team to potentially take a look at them and take a decision.

One annoying one is unused-parameters. It is useful in some cases but very verbose when there is API usage.
The [documentation for the check](https://clang.llvm.org/extra/clang-tidy/checks/misc/unused-parameters.html) propose an interesting solution but it needs C23.

2025-01-11 22:00 UTC, regit commented
I'm stopping playing with it. This is ready for review.

2025-01-11 23:50 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 24169

2025-01-12 02:10 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 24170

2025-01-12 08:15 UTC, victorjulien commented
Most the of the fixes look sane to me, though the linter annotations are a bit obnoxious I think.

How are invoking things? I'm getting warnings like unknown `bool` type which suggest that I'm missing something basic, like includes not getting picked up.

2025-01-12 12:31 UTC, victorjulien commented
Making sure `autoconf.h` is used (by removing `HAVE_CONFIG_H` guards) helps a lot for me.

I can see this be very useful, also in CI. So I guess I'd like to see a basic config that passes on our current code (with some fixes if needed). Then we can start an iterative process of adding more checks or making them stricter.

2025-01-12 12:32 UTC, victorjulien commented
Wonder also if we can just scan + fix just a single check at a time? E.g. this one would be nice to do now
```
/home/victor/sync/devel/eidps/src/app-layer-dnp3.c:82:30: warning: macro argument should be enclosed in parentheses [bugprone-macro-parentheses]
   82 | #define DNP3_OBJ_PREFIX(x) ((x >> 4) & 0x7)
      |                              ^
      |                              ()
/home/victor/sync/devel/eidps/src/app-layer-dnp3.c:85:29: warning: macro argument should be enclosed in parentheses [bugprone-macro-parentheses]
   85 | #define DNP3_OBJ_RANGE(x)  (x & 0xf)
      |                             ^
      |                             ()
```

2025-01-12 12:33 UTC, victorjulien commented
Similar for this class of suggestions
```
/home/victor/sync/devel/eidps/src/app-layer-dnp3.c:343:5: warning: do not use 'else' after 'return' [readability-else-after-return]
  343 |     else {
      |     ^~~~~~
  344 |         return (blocks * DNP3_BLOCK_SIZE);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  345 |     }
      |     ~
```

2025-01-12 12:36 UTC, victorjulien commented
Also liking
```
rust/gen/rust-bindings.h:6727:13: warning: function 'HTTP2MimicHttp1Request' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name]
 6727 | extern void HTTP2MimicHttp1Request(void *orig_state, void *new_state);
      |             ^
/home/victor/sync/devel/eidps/src/app-layer-http2.c:74:6: note: the definition seen here
   74 | void HTTP2MimicHttp1Request(void *alstate_orig, void *h2s)
      |      ^
rust/gen/rust-bindings.h:6727:13: note: differing parameters are named here: ('orig_state', 'new_state'), in definition: ('alstate_orig', 'h2s')
 6727 | extern void HTTP2MimicHttp1Request(void *orig_state, void *new_state); 
      |             ^                            ~~~~~~~~~~        ~~~~~~~~~
      |                                          alstate_orig      h2s
```

2025-01-12 13:34 UTC, regit commented
Do you have a compile_database.json ? (Can use bear of you don't have). Having it fixes most of the include issue.Le 12 janv. 2025 09:15, Victor Julien ***@***.***> a écrit :
Most the of the fixes look sane to me, though the linter annotations are a bit obnoxious I think.
How are invoking things? I'm getting warnings like unknown bool type which suggest that I'm missing something basic, like includes not getting picked up.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-01-28 15:51 UTC, catenacyber commented
What is the status here ?
(and is CI getting red if I have a PR that is not clean according to clang-tidy ? )

2025-01-28 16:21 UTC, victorjulien commented
Would like to see minimal passing config that we can hook into CI, then incrementally make it stricter and fix the issues.

2025-01-28 21:39 UTC, catenacyber requested changes
So, requesting changes as per Victor's comment

2025-04-28 14:32 UTC, regit commented
I'm playing with one of the available action that handles clang tidy on a subset of the change.

On possibility is to create this type of comments on the PR:
https://github.com/regit/suricata/pull/54#discussion_r2063651448

It is also possible to just fail the checks.

Let me know what you prefer.

Also, as clang-tidy needs a compile_commands.json file, I'm planning to merge Nixos PR and this one.

Let me also know if it's good with you.

2025-04-28 16:42 UTC, jasonish commented
Would be nice to have the .clang-tidy in file before all fixes and CI is ready. Already finding it useful for my editor.

2025-04-28 18:05 UTC, regit commented
> Would be nice to have the .clang-tidy in file before all fixes and CI is ready. Already finding it useful for my editor.

I agree, this is part of my init in development to check the .clang-tidy file.

2025-06-19 08:09 UTC, catenacyber commented
Closing in favor of #13485 right ?

2025-06-19 08:09 UTC, closed without merging