SDP: implements sticky buffers v3
OISF/suricata pull request #12327
Opened 2024-12-30 16:34 UTC by glongo

Make sure these boxes are checked accordingly before submitting your Pull Request -- thank you.

## Contribution style:
- [x] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/contributing/contribution-process.html

## Our Contribution agreements:
- [x] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)

## Changes (if applicable):
- [x] I have updated the User Guide (in [doc/userguide/](https://github.com/OISF/suricata/tree/304271e63a9e388412f25f0f94a1a0da4bf619d9/doc/userguide)) to reflect the changes made
- [x] I have updated the JSON schema (in [etc/schema.json](https://github.com/OISF/suricata/blob/304271e63a9e388412f25f0f94a1a0da4bf619d9/etc/schema.json)) to reflect all logging changes
      (including schema descriptions)
- [ ] I have created a ticket at
      https://redmine.openinfosecfoundation.org/projects/suricata/issues

Link to ticket: https://redmine.openinfosecfoundation.org/issues/

- https://redmine.openinfosecfoundation.org/issues/7291
- https://redmine.openinfosecfoundation.org/issues/7305
- https://redmine.openinfosecfoundation.org/issues/7325

Describe changes:
- Rebase
- Sticky buffers for SDP have been implemented.
  -  The empty check within sticky buffer for optional fields has been removed 
- `sdp.media.bandwidth` and `sdp.media.attribute` sticky buffers have not been implemented yet because the media field is a vector of `MediaDescription`, and both the `bandwidth` and `attribute` fields are vectors as well.
I believe the multi-buffer API cannot handle such a situation.
If I'm not mistaken, a simple solution could be to "stringify" these fields like this:
```
"media_description": {
    "bandwidth": "AS:64,AS:65,AS:66",
    "attribute": "sendonly,recvonly"
}
```
- Media's encryption key is logged now.
- Multiple `time` and `repeat_time` fields are now parsed correctly

Personal considerations:
- The `sdp.media.*` sticky buffers were initially meant to be named `sdp.media_descriptions.*`, but I realized the names were too long. I wonder if I should rename the `media_description` field to `media` for consistency.
- I don't like the name `sdp.media.media`; I would prefer to rename it to `sdp.media.name`, or just `sdp.media`, and adjust the logged field name if necessary.
- CI will probably fail due to the changes made to the way the time and repeat_time fields are logged.

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/2210

2025-01-28 12:27 UTC, catenacyber approved these changes
Thanks for the work Giuseppe :-)

CI : ✅
Code : good
Commits segmentation : nice, great for scoring ;-)
Commit messages : good
Git ID set : looks fine for me
CLA : you already contributed
Doc update : nice
Redmine ticket : ok, I put a reference to this PR in them ;-)
Rustfmt : ok
Tests : nice, thanks
Dependencies added: none

2025-01-28 12:29 UTC, catenacyber commented on doc/userguide/rules/sdp-keywords.rst
> +sdp.media_description.encryption_key     Both
⚠️ is this `sdp.media_description.encryption_key` or `sdp.media.encryption_key` ?

2025-01-28 12:31 UTC, catenacyber commented on rust/src/sdp/logger.rs
> +            if let Some(enc_key) = &m.encryption_key {
Maybe if you make `pub struct SdpMessage` to `pub(crate) struct SdpMessage` you would have got a warning that this field was unused ;-)

2025-01-28 12:32 UTC, catenacyber commented on rust/src/sdp/logger.rs
> +    js.open_array("time_descriptions")?;
Does the array have always one element ?
We do not want to open and log empty array

2025-01-28 12:32 UTC, catenacyber commented on rust/src/sdp/logger.rs
> +    js.open_array("time_descriptions")?;
I guess it does because of `many1` right ?

2025-01-28 12:36 UTC, catenacyber commented
> * `sdp.media.bandwidth` and `sdp.media.attribute` sticky buffers have not been implemented yet because the media field is a vector of `MediaDescription`, and both the `bandwidth` and `attribute` fields are vectors as well.
>   I believe the multi-buffer API cannot handle such a situation.

I believe the multi-buffer API can handle such a situation.
See `rs_http2_tx_get_header_name` where http2 tx has an array of http2 frames which may have an array of headers...

> Personal considerations:
> 
> * The `sdp.media.*` sticky buffers were initially meant to be named `sdp.media_descriptions.*`, but I realized the names were too long. I wonder if I should rename the `media_description` field to `media` for consistency.

Sounds good to me to have both consistent

> * I don't like the name `sdp.media.media`; I would prefer to rename it to `sdp.media.name`, or just `sdp.media`, and adjust the logged field name if necessary.

Ok

> * CI will probably fail due to the changes made to the way the time and repeat_time fields are logged.

It did not fail. Why should it ?

2025-01-28 12:37 UTC, catenacyber commented on rust/src/sdp/parser.rs
> +    let origin_line = format!(
nit could we avoid the reformat and use the raw bytes just parsing once ?

2025-01-28 12:38 UTC, catenacyber requested changes
Needs a rebase now

2025-01-28 12:38 UTC, catenacyber commented on src/detect-engine-register.c
> +    ScDetectSdpRegister();
nit but Jason told the correct prefix is `SC` not `Sc`

2025-01-28 12:39 UTC, catenacyber commented on rust/src/sdp/detect.rs
> +        if !session_name.is_empty() {
Can we not distinguish an absent session name and an empty one ?

2025-02-09 11:06 UTC, glongo commented
Replaced with https://github.com/OISF/suricata/pull/12546

2025-02-09 11:06 UTC, closed without merging