doc/userguide: align and update doc to reflect config file
OISF/suricata pull request #5292
Opened 2020-08-12 21:39 UTC by norg

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

https://redmine.openinfosecfoundation.org/issues/3046

Describe changes:
- This reorders the documentation parts to reflect the order in the actual config yaml file
- It adds all missing parts and sections that appear in the config file
- Content was updated to reflect some changes already happend
- Minor wording and related fixes
- Adding a lot of info to the default values as noted in the redmine, not yet all are covered
- inludes some TODO as comments that still need to be done (documented) or are open questions, so could be also called WIP somehow

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2020-08-25 06:14 UTC, victorjulien requested changes
Sphinx generates warnings, please address those.

Also, if you feel a PR is 'WIP' quality, please open it as a 'draft' PR

Have not looked into the actual changes yet, will do so once CI passes.

2020-08-25 21:58 UTC, norg commented
I fixed the file store label issue, so feel free to give first feedback to the content of this draft.

2020-09-12 20:09 UTC, norg commented
@jlucovsky I did the rebase and fixed two merge conflicts. I pushed the updated to this PR (since it's still just a Draft)

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +have different priority's. In the option 'prio' you can set a priority for each
s/priority's/priorities/

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +Luajit has a strange memory requirement, it's 'states' need to be in the
s/it's/its/

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +If the pool was depleted a hint will be printed at the engines exit.
"will be printed when the engine exits"

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +mind that a rule reload temporary doubles the states requirement.
s/states/state's/

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +only do its job if you compiled Suricata with --enable profiling.
``--enable-profiling``

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +in yaml.
s/in yaml//

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +Using NFQUEUE in iptables rules, will send packets to Suricata. If the
values and option names in "``" here and everywhere.

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +The Pf_ring is a library that aims to improve packet capture
Suggest "PF Ring" instead of "The Pf_ring"

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +three options within Pf_ring: interface, cluster-id and cluster-type.
"Pf_ring" or "Pf-ring"?

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +to be load for use. You can set the directory where the files can be
"loaded"

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +from. There are much more rule-files available.
s/much/many

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +If you set a file-name that appears to be not existing, Suricata will
Rule files that don't exist are ignored by Suricata (a error (warning?)) message will be displayed).

2020-09-15 14:29 UTC, jlucovsky commented on doc/userguide/configuration/suricata-yaml.rst
> +You can set the direction of the classification configuration.
"direction"? or "filename"?

2020-09-19 20:29 UTC, norg commented
Thanks I will include those fixes/suggestions in the next PR version for that.

2021-04-20 08:33 UTC, victorjulien requested changes
Needs rebase

2021-12-13 14:55 UTC, closed without merging