dnp3: fixed wrong flow direction identification
OISF/suricata pull request #5324
Opened 2020-08-25 13:12 UTC by ilya-bakhtin

dnp3 is communication between so-called master and outstation
in our terms master is a client and outstation is a server
DIR flag in dnp3 header is nonzero when a packet is from master
so if DIR is nonzero then the packet is 'toserver'

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
The condition when the direction is reversed is changed according to dnp3 specification.
The value of returned rdir is changed to follow the pattern used in the caller.

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2020-08-25 13:32 UTC, ilya-bakhtin commented
Please note the existing dnp3-midstream-confirm is failing since it's based on a wrongly patched file.
It's taken from real complete communication available at suricata-verify/tests/dnp3-eve/input.pcap
Please compare suricata-verify/tests/dnp3-midstream-confirm/dnp3_confirm.pcap with packet # 9 from input.pcap
You will see the same packet but with ports order changed.

I prepared the correct test based on the same source. It's available at my fork of suricata-verify:
https://github.com/ilya-bakhtin/suricata-verify/commit/9105cd3084c2735caf7104e2764255756ee07d7a

2020-08-26 11:55 UTC, catenacyber commented
Thanks @ilya-bakhtin for this
It looks right as `*rdir` should not be set to `1` but rather to `STREAM_TOSERVER` or `STREAM_TOCLIENT` as your patch fixes.

> Please note the existing dnp3-midstream-confirm is failing

Could you make a PR to suricara-verify to fix this ?
And then reference it in your first comment
`sed s/#suricata-verify-pr:/suricata-verify-pr:XXX/` with XXX being the right number

2020-08-26 12:04 UTC, ilya-bakhtin commented
i guessed pull request was already there
https://github.com/OISF/suricata-verify/pull/304

2020-08-26 12:16 UTC, catenacyber commented
Thanks, I updated your first comment to add it, and try to re-run CI

2020-08-26 19:12 UTC, catenacyber commented
> You will see the same packet but with ports order changed.

Ports order should not impact the detection direction, does it ?

I think the test.yaml `flow.pkts_toclient: 1` is just wrong, the pcap is ok

2020-08-26 19:28 UTC, ilya-bakhtin commented
I'm still not 100% sure, but probably to proof buffer overflow fix, it's necessary to patch DIR flag in the packet instead of ports swapping. If DIR flag indicates proper direction then execution does not go into the path where overflow is possible (was possible before mentioned fix).

2020-08-27 16:09 UTC, catenacyber requested changes
There may be another bug in `DNP3ProbingParser` preventing this patch from being OK

2020-08-27 16:09 UTC, catenacyber commented on src/app-layer-dnp3.c
>  end:
What do you think of the code a few lines above coming to this label ?
```
if (DNP3ContainsBanner(input, len)) {
        SCLogDebug("Packet contains a DNP3 banner.");
        goto end;
    }
```

In this case, we certainly cannot use `hdr->control`

2020-08-27 17:58 UTC, ilya-bakhtin commented
Yes, it's a preexisting issue so i did not pay attention.
Also in a case of banner the direction can not be to server.
Please see https://github.com/OISF/suricata/pull/5330

2020-08-27 19:14 UTC, catenacyber commented
Closing in favor of the new #5330

2020-08-27 19:14 UTC, closed without merging

2020-08-27 19:15 UTC, catenacyber commented
> Yes, it's a preexisting issue so i did not pay attention.

Indeed, it caught my eye while reviewing