Enum dir rust/v1
OISF/suricata pull request #5416
Opened 2020-09-11 18:54 UTC by inashivb

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3832

2020-09-11 18:54 UTC, inashivb commented
@jasonish @victorjulien do you like this?
Any changes I should make?
Should I do the same for other protocols as well?

2021-04-29 08:30 UTC, catenacyber commented
Looks a good idea.
Can it be exported to C ? Like `SshStateFinished` for an example

2021-04-29 08:31 UTC, catenacyber commented
(so as to have only one definition)

2021-04-29 19:18 UTC, jasonish commented on rust/src/core.rs
> +
Can you try adding repr(C) here as well?  Then maybe it can be the source of truth and used from C as well.

2021-04-29 19:19 UTC, jasonish requested changes
I'd like to see this rebased.  Its a good candidate to become an enum on the Rust side I think.

2021-07-01 06:29 UTC, closed without merging

2021-08-12 18:05 UTC, inashivb commented
Replaced w #6294