dcerpc-udp: fixed several dcerpc-udp related issues
OISF/suricata pull request #5462
Opened 2020-10-03 18:46 UTC by ilya-bakhtin

- proper flag definitions for connectionless dcerpc are used
- proper pairing of messages into transaction by activity uid and sequence number is implemented
- removed unnecessary (wrong) code that came from C implementation

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
DCERPC UDP is a connectionless version. However original implementation wrongly uses TCP flag bit definitions. The fix defines proper connectionless flags and uses them to identify fragmentation, etc. 

Original implementation wrongly pairs messages in a transaction by serial number. DCERPC UDP messages must be paired by activity uid and sequence number.

Removed unnecessary code that came from C implementation

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2020-10-07 08:38 UTC, inashivb approved these changes
LGTM. Thanks. I did use the incorrect field to match the records. And the way you have handled the data is much cleaner. I'll take inspiration from this for any parsers that I may write in future. :)

2020-10-07 14:46 UTC, inashivb requested changes
Hi @ilya-bakhtin !
Your changes are good but I think we could have better commit messages (more explanation) and separate commits for the three issues that you have mentioned. Could you please do that?
Thanks for all your work!

2020-10-07 19:28 UTC, ilya-bakhtin commented
I'm sorry, but it's not possible to separate the changes since the original implementation is completely incorrect.

2020-10-08 07:17 UTC, inashivb commented
Hi @ilya-bakhtin !
One way I see we can break changes is:
- Commit to add new flag definitions required by UDP implementation. https://github.com/OISF/suricata/pull/5462/files#diff-2b8a5ffea2bc960ec0235b738e1d6262R32-R77
- Commit to add activityuuid and seqnum to transaction struct and using it in the existing code to match the right records.
- Commit to cleanup all the redundant code and fields. (This can include changes like https://github.com/OISF/suricata/pull/5462/files#diff-2b8a5ffea2bc960ec0235b738e1d6262L1267, https://github.com/OISF/suricata/pull/5462/files#diff-249c00140a1008d7a0f0ce27b5683916L269-L292 and https://github.com/OISF/suricata/pull/5462/files#diff-249c00140a1008d7a0f0ce27b5683916L90-L108 etc)

Would this work?

2020-11-24 11:21 UTC, victorjulien commented
@inashivb reworked this into #5558, thanks both!

2020-11-24 11:21 UTC, closed without merging