rust: fix rust build for rustc 1.24.1
OISF/suricata pull request #5481
Opened 2020-10-11 20:03 UTC by Sylfrena

Builds for suricata fail with rustc 1.24.1 due to usage of `crate`
to specify the absolute path for the app-layer-parser with the errors:
    
    error[E0433]: `crate` can only be used in absolute paths
    error: `crate` in paths is experimental

Modify relevant files to use relative paths instead.

Fixes Bug ~#4064~

Reference:
https://travis-ci.com/github/OISF/suricata/jobs/396870085

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4064

Describe changes:
- Remove `crate` from absolute path, and therefore, use relative path for the app-layer-parser.

2020-10-11 20:40 UTC, Sylfrena commented
Hi @jasonish,

The Travis CI build seems to be failing in my case, but I am unable to figure out the reason. 
What do I need to improve in this PR?

2020-10-11 22:28 UTC, jasonish commented
> Hi @jasonish,
> 
> The Travis CI build seems to be failing in my case, but I am unable to figure out the reason.
> What do I need to improve in this PR?

@Sylfrena I think this error is on Travis's side, nothing to do with your PR.  I've restarted the build over there.

2020-10-12 06:50 UTC, inashivb commented
Hi @Sylfrena !
Thanks for your first contribution to the project! :)

I see
```
warning: unknown lint: `ellipsis_inclusive_range_patterns`

  --> src/lib.rs:18:10

   |

18 | #![allow(ellipsis_inclusive_range_patterns)] // TODO: Remove when MSRV is higher than 1.24

   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   |

   = note: #[warn(unknown_lints)] on by default
```
on QA (https://travis-ci.com/github/OISF/suricata/jobs/398027318#L1594). Could you please fix this and submit a new PR?

Good job!

2020-10-12 09:06 UTC, victorjulien requested changes
Please implement the suggestions by Shivani here https://github.com/OISF/suricata/pull/5481#issuecomment-706910331

2020-10-12 14:22 UTC, Sylfrena commented
Hi @inashivb,

Since this is a different error than the previous one, would you like me to send the new PR with only fixing the `unknown lint` warning, or should the new PR have both the changes ? If it should have both the changes, then can I send a PR having 2 commits, one for each change?

2020-10-13 06:39 UTC, inashivb commented
> Hi @inashivb,
> 
> Since this is a different error than the previous one, would you like me to send the new PR with only fixing the `unknown lint` warning, or should the new PR have both the changes ? If it should have both the changes, then can I send a PR having 2 commits, one for each change?

Yes, please. One new PR with two commits for each of the changes. Make sure to include relevant context in both the commits.

2020-10-13 12:12 UTC, Sylfrena commented
Replaced with #5486

2020-10-13 12:13 UTC, closed without merging