Optimization 3825 v1
OISF/suricata pull request #5511
Opened 2020-10-25 16:19 UTC by jufajardini

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3825

Describe changes:
- filecontainer: add Files structure, to replace/unify SMBFiles and NFSFiles
- smb/files: delete SMBFiles implementation
- smb/smb: replace SMBFiles with Files
- nfs/nfs: delete NFSFiles implementation, replace former declarations with Files' ones

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2020-10-25 16:22 UTC, jufajardini commented
So, taking into account the commit guidelines, and one of the first feedbacks Shivani offered, I wasn't sure, here, how many commits I should have, nor what should be the best way of logically organising them. 

Should they be done by file - as in, should I have 4 commits for this? Or could it be like I did, by type of change and directories involved?

Thanks in advance for any feedbacks!

2020-10-25 16:40 UTC, jufajardini commented
I will close it because there's a missing module error, but I still appreciate some feedback regarding the previous comment, if possible :)

2020-10-26 07:17 UTC, victorjulien requested changes
I think the change is small enough to be a single commit. It also helps the issue that each commit needs to build correctly.

Can you do a new branch + new PR with a single commit?

2020-10-26 07:17 UTC, victorjulien commented on rust/src/smb/smb.rs
> +            files: Files::new(), // replacing SMBFiles with Files
this comment can be removed

2020-10-26 09:59 UTC, victorjulien commented on rust/src/filecontainer.rs
> +// Unifying the definition of files SMBFiles and NFSFiles (HTTP2 too, soon)
this comment should be updated to what it is now, it should not be about what it was or how we got there. That type of info should go into the git commit messages.

2020-10-26 09:59 UTC, victorjulien commented on rust/src/smb/smb.rs
> +    // replacing SMBFiles with Files
this comment should be removed

2020-10-26 09:59 UTC, victorjulien commented on rust/src/nfs/nfs.rs
> +    // replacing NFSFiles with the new structure derived from it
comment should be removed

2020-10-26 21:13 UTC, jufajardini commented
Changes implemented in new PR: https://github.com/OISF/suricata/pull/5513

2020-10-26 21:13 UTC, closed without merging