Modify TLS certificate decoding of validity timestamps to support tim…
OISF/suricata pull request #5764
Opened 2021-01-21 17:26 UTC by Fredamabob

Modify TLS certificate decoding of validity timestamps to support times between 1950 and 2049, as per RFC 5280

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3253

Describe changes:
- Modified the TLS cert validity timestamp parsing functions to return LONG_MIN on error instead of 0, to allow for timestamps at epoch 0 (1970). A previous version of that code also checked for any epoch value <=0, which meant that any valid timestamp between 1950 and 1969 (RFC5280) was rejected. The code got refactored since, but was still left with the edge case of epoch=0.
- Added a test case to verify that a ts between 1950 and epoch 0 is parsed correctly.
- Added a test case to verify that a ts at epoch 0 is parsed correctly

2021-02-02 08:12 UTC, catenacyber approved these changes
Looks good to me.
Could you squash the commits together ?

2021-02-02 08:14 UTC, catenacyber commented
And maybe add a comment in the code referring to https://tools.ietf.org/html/rfc5280#section-4.1.2.5.1

2022-03-10 15:49 UTC, catenacyber requested changes
Could you prefix the commit title by `tls` cf https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Code_Submission_Quality_Criteria 
> Naming convention: prefix message with sub-system ("rule parsing: fixing foobar").

2022-04-26 15:08 UTC, suricata-qa commented
Warning: no commits in this PR have specified the following ticket(s):
- 3253 - https://redmine.openinfosecfoundation.org/issues/3253

Please update the commit(s) and submit a new PR.

2022-07-06 13:19 UTC, catenacyber commented
Friendly ping @Fredamabob are you planning to work on this again ?

2022-12-26 16:47 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/8324

2022-12-26 16:47 UTC, closed without merging