detect/content: Consider distance in validation
OISF/suricata pull request #5881
Opened 2021-02-19 14:02 UTC by jlucovsky

Continuation of #5854

This commit modifies the validation callback to include the distance
during validation.

Values of distance that cause the right edge to be exceeded are
considered an error and the signature will be rejected.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [2982](https://redmine.openinfosecfoundation.org/issues/2982)

Describe changes:
- Handle negative distance values

suricata-verify-pr: 446
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2021-04-20 12:20 UTC, victorjulien commented on src/detect-content.c
> +            right_edge = (uint32_t)abs(cd->distance) - right_edge;
distance describes a relation between 2 patterns, so we'd have to look at something like
`right_edge = prev_cd->content_len + prev_cd->offset + cur_cd->distance`

2021-04-20 12:21 UTC, victorjulien requested changes
see comment

2021-08-24 08:00 UTC, suricata-qa commented
ERROR: ASAN TEST FAIL in tlpr1_asan_suri QA test

Pipeline 3889

2021-09-25 02:00 UTC, suricata-qa commented
ERROR: ASAN TEST FAIL in tlpr1_asan_suri QA test

Pipeline 3889

2022-01-21 15:19 UTC, jlucovsky commented
Continued in #6838

2022-01-21 15:19 UTC, closed without merging