doc/dcerpc: add proto keywords
OISF/suricata pull request #5919
Opened 2021-02-24 12:00 UTC by inashivb

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3029

2021-02-26 10:47 UTC, victorjulien requested changes

2021-02-26 10:47 UTC, victorjulien commented on doc/userguide/rules/dcerpc-keywords.rst
> +dcerpc.opnum
If you look at `rust/src/dcerpc/detect.rs` you will see that this supports more complex options as well.

2021-02-26 10:47 UTC, victorjulien commented on doc/userguide/rules/dcerpc-keywords.rst
> +  dcerpc.iface:<uuid>;
If you look at `rust/src/dcerpc/detect.rs` you will see that this supports more complex options as well.

2021-05-21 17:33 UTC, inashivb commented
Replaced with #6134

2021-05-21 17:33 UTC, closed without merging