unittests: Register missing UT modules
OISF/suricata pull request #6089
Opened 2021-04-27 12:09 UTC by jlucovsky

This commit adds three UT registrations that were discovered missing
during code coverage.

Describe changes:
- Register UT functions for ENIP, template-buffer and rust-template-buffer.
-
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2021-04-29 09:28 UTC, catenacyber approved these changes
How did you find about `DetectEngineInspectENIPRegisterTests` ?

2021-04-29 09:29 UTC, catenacyber requested changes
But some unit tests fail. Did you investigate which ones ?

2021-07-10 08:00 UTC, suricata-qa commented
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.spare | 6722209 | 5890991 | 88.0% |
| .app_layer.flow.ftp-data | 157 | 500 | 31.0% |

2021-07-12 08:00 UTC, suricata-qa commented
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.spare | 6722209 | 5890991 | 88.0% |
| .app_layer.flow.ftp-data | 157 | 500 | 31.0% |

2021-09-05 06:05 UTC, suricata-qa commented
ERROR: ASAN TEST FAIL in tlpr1_asan_suri QA test

Pipeline 3478

2021-09-08 11:59 UTC, catenacyber commented
ping @jlucovsky

2021-09-26 03:50 UTC, suricata-qa commented
ERROR: ASAN TEST FAIL in tlpr1_asan_suri QA test

Pipeline 3478

2021-09-29 02:00 UTC, suricata-qa commented
Information: QA ran without warnings.

Pipeline 4378

2021-09-29 16:52 UTC, jlucovsky commented
Continued in #6422

2021-09-29 16:52 UTC, closed without merging