defrag: remove unnecessary copy operations
OISF/suricata pull request #6246
Opened 2021-07-02 06:32 UTC by shizishizi2012

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: No

Describe changes:
- When reassembling the IPv6 fragment, there is no need to copy the last fragment data to the new packet. Fixing that.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2021-07-02 14:44 UTC, jasonish commented
Thanks @shizishizi2012. Can you please elaborate in the git commit why they copy is not needed? Thanks!

2021-07-03 07:54 UTC, shizishizi2012 commented
> Thanks @shizishizi2012. Can you please elaborate in the git commit why they copy is not needed? Thanks!

The content of they copy will be covered by the IP fragment of the subsequent circular copy.

2022-01-06 12:41 UTC, catenacyber requested changes
Thanks for spotting this.
I guess it would be better to change `PacketDefragPktSetup` prototype to have only `Packet *PacketDefragPktSetup(Packet *parent)`
What do you think ?

2022-07-06 13:24 UTC, catenacyber commented
@shizishizi2012 are you planning further work on this ?

2022-12-26 16:19 UTC, closed without merging