lua: use pushinteger for int in flow/packet tuples
OISF/suricata pull request #6254
Opened 2021-07-05 12:49 UTC by jufajardini

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/4182

Describe changes:
- replace `lua_pushnumber` with `lua_pushinteger` for the `int` types in `SCFlowTuple()` and `SCPacketTuple()`

Question:
Should we also use `lua_pushinteger` in `LuaCallbackStatsPushToStackFromFlow` and `LuaCallbackRuleIdsPushToStackFromPacketAlert`, for packet counts and `id`, `rev` and `gid`?

suricata-verify-pr: 516
https://github.com/OISF/suricata-verify/pull/516

2021-07-06 08:00 UTC, suricata-qa commented
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

2021-07-11 08:00 UTC, suricata-qa commented
| field | test | baseline | % diff |
|--|--|--|--|
| | tlpr1_stats_chk |
| .tcp.insert_list_fail | 219 | 255 | 86.0% |

2021-07-14 08:00 UTC, suricata-qa commented
WARNING:\r\n| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |
| .flow.spare | 6919992 | 5890991 | 85.0% |
| .flow.memuse | 1273244608 | 1130221888 | 89.0% |

2021-07-22 15:49 UTC, jasonish commented
> Should we also use `lua_pushinteger` in `LuaCallbackStatsPushToStackFromFlow` and `LuaCallbackRuleIdsPushToStackFromPacketAlert`, for packet counts and `id`, `rev` and `gid`?

Yes, I think so.

2021-07-22 15:50 UTC, jasonish commented
Looks good.

While I haven't tested, is this what happens?
- With Lua 5.1 the integers will still be printed as floats
- With Lua 5.3 the integers will be printed as integers

2021-07-22 16:07 UTC, jasonish requested changes
Ok, so it tests ok on 5.1, 5.4 and Luajit.  I thought 5.1 might print the numbers like `4.0` no  matter what.

Anyways, I'd try to convert a few more as you ask in the pull-request body.

Thanks!

2021-07-22 17:28 UTC, jufajardini commented
> Looks good.
> 
> While I haven't tested, is this what happens?
> 
>     * With Lua 5.1 the integers will still be printed as floats
> 
>     * With Lua 5.3 the integers will be printed as integers

On my end, without lua_pushinteger, it was actually the opposite. 

> Ok, so it tests ok on 5.1, 5.4 and Luajit. I thought 5.1 might print the numbers like `4.0` no matter what.
> 
> Anyways, I'd try to convert a few more as you ask in the pull-request body.
> 
> Thanks!

Thanks for the review, I'll submit the new changes asap.

2021-07-26 14:43 UTC, jufajardini commented
Replaced by: https://github.com/OISF/suricata/pull/6279

2021-07-26 14:43 UTC, closed without merging