devguide/transactions: refine some explanations. - Tx documentation v11
OISF/suricata pull request #6268
Opened 2021-07-15 10:38 UTC by jufajardini

Describe changes: 
- replace frontend/backend with client/server
- refine wording in Progress Tracking section
- explain better the DoS by quadratic complexity

Link to Redmine issue: https://redmine.openinfosecfoundation.org/issues/4396

Previous PR: https://github.com/OISF/suricata/pull/6265

Current state with images looks like this: https://devguide-transactions.surge.sh/extending/app-layer/transactions.html

2021-07-16 06:37 UTC, catenacyber approved these changes
Looks like a welcome documentation improvement to me

2021-07-17 08:00 UTC, suricata-qa commented
Information:
| field | test | baseline | % |
|--|--|--|--|
| | tlpr1_stats_chk |

2021-07-23 16:32 UTC, jasonish commented on doc/devguide/Makefile.sphinx
> +BUILD_IMG = ./extending/app-layer/img/generate-images.sh
I think a better location for the script might be `devguide/tools`

2021-07-23 16:33 UTC, jasonish commented on doc/devguide/extending/app-layer/img/DnsRequestUnidirectionalTransaction.msc
> +}
I'd go one more step and add the DNS Response, transaction complete.  Just to complete the life cycle of a DNS request for an end-user.

2021-07-23 16:35 UTC, jasonish commented on doc/devguide/extending/app-layer/transactions.rst
> +For Suricata, transactions are abstractions that help with detecting and logging. An example of complete transaction is
transactions are an abstraction

2021-07-23 16:37 UTC, jasonish commented on doc/devguide/extending/app-layer/transactions.rst
> +a pair of messages Request (from client to server) and Response (from server to client) in HTTP.
a pair of messages in the form of a request (from client to server) and a response (from server to client) in HTTP.

2021-07-23 16:42 UTC, jasonish commented on doc/devguide/extending/app-layer/transactions.rst
> +is, when is it complete, or when does it reach a key intermediary stage. They aid during the detection phase,
> or when does it reach a key intermediary stage

or when it reaches a key intermediate state

2021-07-23 16:43 UTC, jasonish commented on doc/devguide/extending/app-layer/transactions.rst
> +when dealing with protocols that can have large PDUs, like TCP, in controlling state for partial rule matching -- in case of rules that mention more than one field.
Might be worth expanding PDU on first use in this chapter:
```
can have large PDUs (protocol data units)
```

2021-07-23 16:50 UTC, jasonish requested changes
Some grammar changes requested.  But otherwise this is looking real good.  I think some squashing of the commits will be required before merge to master since this section is all new.  But otherwise the sooner we can get this in the better.

2021-07-26 13:39 UTC, jufajardini commented
replaced by: https://github.com/OISF/suricata/pull/6278

2021-07-26 13:39 UTC, closed without merging