fix: closing bracket was at wrong place
OISF/suricata pull request #6291
Opened 2021-08-11 08:25 UTC by Shchelk

This bug was found by svace static code analyzer

warn: OP_PRECEDENCE_ASSIGN_CMP
msg: Logic operator precedence in assignment can produce an unexpected result

2021-08-23 07:38 UTC, catenacyber commented on src/tm-threads.c
> +                    if ((r = TmThreadsSlotProcessPkt(tv, fw_slot, p)) != TM_ECODE_OK) {
Thanks for this.
Could we have a separation of the assignment and the condition over two different lines ?

2021-09-27 10:38 UTC, catenacyber commented on src/tm-threads.c
> +                    r = TmThreadsSlotProcessPkt(tv, fw_slot, p)
missing ;

2021-09-27 15:48 UTC, catenacyber approved these changes
Looks good to me.

We can even make it simpler with keeping only one check `r == TM_ECODE_FAILED`

2021-11-08 14:19 UTC, catenacyber commented
Could you check the CI failures ?

2021-11-13 07:56 UTC, victorjulien commented
Can you also make sure to sign the CLA? https://suricata.io/contribution-agreements/ Thanks!

2022-01-06 12:30 UTC, catenacyber requested changes
Please fix the formatting with `./scripts/clang-format.sh`

2022-07-06 13:30 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/7614

2022-07-06 13:30 UTC, closed without merging