bittorrent-dht: add bittorrent-dht app layer v4
OISF/suricata pull request #6483
Opened 2021-10-18 05:26 UTC by abungay

Parses and logs the bittorrent-dht protocol. 

Feature: #3086

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3086

Describe changes:
- Ensures BitTorrent DHT traffic does not get marked as app_proto: failed
- Parses BitTorrent DHT packets and logs data to eve.json

Changes since last PR:
- rebase to master, fix merge conflicts

Reference BitTorrent DHT specification:
https://www.bittorrent.org/beps/bep_0005.html

TODO after merging PR:
- Update wiki for SID ranges at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/AppLayer for the newly introduced bittorrent-dht SID range (start=2271000, end=2271999)

[PRScript](https://redmine.openinfosecfoundation.org/projects/suricata/wiki/PRscript) output (if applicable):

Previous PR: https://github.com/OISF/suricata/pull/5942

suricata-verify-pr: 560

2021-10-18 05:31 UTC, abungay commented
Question for reviewers: It was noticed that the port range "[1024:65535]" being used in rust/src/bittorrent_dht/bittorrent_dht.rs:rs_bittorrent_dht_udp_register_parser() is causing the Suricata startup time to take over 3 minutes on my computer compared to under 1 second on the master Suricata branch. Is there a better way I could listen on ports 1024:65535 without causing such a long startup time? This startup time was causing CI failures for fuzzing on the previous version of this PR v3.

2022-01-28 11:09 UTC, victorjulien requested changes
Some smaller comments. Another thing that will come up soonish is the nom7 transition.

2022-01-28 11:09 UTC, victorjulien commented on rust/src/bittorrent_dht/bittorrent_dht.rs
> +        flags: 0,
transactions look unidirectional, so `APP_LAYER_PARSER_OPT_UNIDIR_TXS` should be set here

2022-05-11 14:57 UTC, closed without merging

2022-08-12 19:13 UTC, jasonish commented
> Some smaller comments. Another thing that will come up soonish is the nom7 transition.

Actually nom isn't used in this parser.