ips: Add stats for additional capture methods
OISF/suricata pull request #6531
Opened 2021-10-28 12:55 UTC by jlucovsky

This PR adds IPS stats (blocked/accepted/dropped/rejected) to:
- Netmap
- AF-PACKET
- IPFW
- 
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [4756](https://redmine.openinfosecfoundation.org/issues/4756)

Describe changes:
-  Adds a `CaptureStats` struct to each capture source's per-thread variable
- Invokes `CaptureStatsUpdate` with each packet to record status
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2021-11-11 15:32 UTC, jlucovsky commented on src/source-af-packet.c
> +        AFPThreadVars *aftv = p->afp_v.aftv;
Given that you're removing `autofp` support from af-packet, i'll investigate whether netmap has a similar issue

2021-11-11 16:02 UTC, victorjulien commented on src/source-af-packet.c
> +        AFPThreadVars *aftv = p->afp_v.aftv;
The removal is not set in stone yet. @norg pointed out some potential valid use cases.

2022-01-25 12:06 UTC, victorjulien requested changes
CI failures, needs rebase

2022-04-26 15:22 UTC, victorjulien commented on src/source-af-packet.c
> +        AFPThreadVars *aftv = p->afp_v.aftv;
I think for now we're not removing `autofp` just yet.

2022-05-17 02:00 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on tlpw2_single_alerts_cmp.
  

Pipeline 4652

2022-05-30 02:00 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on tlpw2_single_alerts_cmp.
  

Pipeline 4652

2022-05-31 12:05 UTC, suricata-qa commented
ERROR:
 

ERROR: QA failed on tlpw2_single_alerts_cmp.
  

Pipeline 4652

2022-07-06 13:31 UTC, closed without merging

2022-07-29 11:46 UTC, victorjulien commented
I think this needs a new approach, where each thread just sets up its own version of the counters. The API takes care of merging them.