detect-id: convert unittests to FAIL/PASS APIs
OISF/suricata pull request #6621
Opened 2021-11-19 13:42 UTC by TheKharleeci

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ ] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to redmine ticket:
https://redmine.openinfosecfoundation.org/issues/4046

Ticket: #4046

Previous PR: #6619 

Describe changes:

- Update detect-id unit tests to use FAIL/PASS APIs
- Update Copyright Year

2021-11-19 16:22 UTC, jufajardini requested changes
Looking good, except for `DetectIdTestMatch01` which needs some adjustment :)

2021-11-19 16:22 UTC, jufajardini commented on src/detect-id.c
> -
If we deleted these, we would be deleting the core of this test ;)

2021-11-19 16:22 UTC, jufajardini commented on src/detect-id.c
> -    result = UTHGenericTest(p, 3, sigs, sid, (uint32_t *) results, 3);
I think a check like 
```c
FAIL_IF_NOT(UTHGenericTest(p, 3, sigs, sid, (uint32_t *) results, 3));
```
here would work :)

2021-11-21 01:36 UTC, TheKharleeci commented
Followed by: #6626

2021-11-21 01:36 UTC, closed without merging