eve/alert: correctly log if file has been stored
OISF/suricata pull request #6695
Opened 2021-12-09 14:41 UTC by regit

At the time of logging the alert, the files that will be stored
are in FILE_STORE stage and not FILE_STORED.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/4881

Describe changes:
- correctly log when file has been stored

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2021-12-09 18:15 UTC, victorjulien commented on src/output-json-alert.c
> +                EveFileInfo(jb, file, file->flags & FILE_STORE);
this is not correct. FILE_STORE is set if the file should be stored, but only the file store module sets FILE_STORED if the file has actually been stored.

2021-12-15 08:50 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 5304

2022-01-25 12:05 UTC, victorjulien requested changes
See inline comment

2022-04-26 15:08 UTC, suricata-qa commented
Warning: no commits in this PR have specified the following ticket(s):
- 4881 - https://redmine.openinfosecfoundation.org/issues/4881

Please update the commit(s) and submit a new PR.

2022-05-20 17:19 UTC, closed without merging