Fix app-layer protocol detect patterns for SSLv2
OISF/suricata pull request #6770
Opened 2022-01-11 23:26 UTC by giannitedesco

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

The SSLv2 record format starts with 2 byte length, then it has a 1 byte
message-type field set to |01| for the client handshake, then a 2 byte
protocol version.

The SSLv3 record format (in use with modern TLS) starts with the
message-type of |16| and then the protocol, followed by the length.

This means that several of the patterns in the SSL app-layer detection
code are incorrect because they're looking in the wrong place in the
packet.

#suricata-verify-pr: OISF/suricata-verify#555
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2022-01-11 23:27 UTC, giannitedesco commented
@catenacyber created new repo, actually I got my remotes mixed up so I was rebasing on origin/master not upstream/master, woops :)

2022-01-12 08:59 UTC, catenacyber commented
Thanks CI looks better.
The failures are not related to the PR

2022-01-13 16:40 UTC, catenacyber approved these changes

2022-04-15 09:11 UTC, victorjulien commented
I need to look at this again. I looked earlier w/o understanding the logic and not seeing any test cases pass/fail in relation to this PR.

SSL3/TLS records can certainly start with other values than `|16|`.

2022-04-15 09:11 UTC, victorjulien commented
@catenacyber can you dig a bit deeper into this?

2022-04-15 12:06 UTC, catenacyber commented
> not seeing any test cases pass/fail in relation to this PR.

The S-V tests fail without this PR and succeed with it...

For instance, sslv2-tls1_0-client-handshake.pcap tcp payload begins with bytes 80 80 01 03 01. First 2 bytes are SSLv2, Third byte is 1:client hello, Byte 4 and 5 are request version 03.01 being TLS 1.0

2022-04-15 12:07 UTC, catenacyber requested changes
@giannitedesco can you rebase both this PR and the S-V one ?
It looks like sslv2-handshake is now failing with this PR

Flow has 
```
  "app_proto": "tls",
  "app_proto_tc": "failed",
```
as in master

2022-04-26 00:57 UTC, giannitedesco commented
> @giannitedesco can you rebase both this PR and the S-V one ? It looks like sslv2-handshake is now failing with this PR
> 
> Flow has
> 
> ```
>   "app_proto": "tls",
>   "app_proto_tc": "failed",
> ```
> 
> as in master

Those are supposed to fail, there is no SSLv2 decoder. The tests are included so that they will verify the SSLv2 decoder when it is added.

Is there a way to mark tests as "ignore failures" or should I redo them to just verify the protocol detection works?

2022-04-26 01:07 UTC, giannitedesco commented
@catenacyber So I just commented out the SSLv2 protocol decode stuff, so they can be uncommented if/when that gets implemented. At least the test can verify the detection of protocol part then.

2022-04-27 08:25 UTC, catenacyber commented
> So I just commented out the SSLv2 protocol decode stuff, so they can be uncommented if/when that gets implemented. At least the test can verify the detection of protocol part then.

@inashivb is there a `skip` keyword for Suricata-verify ?

2022-04-27 08:29 UTC, catenacyber commented
> Those are supposed to fail, there is no SSLv2 decoder. The tests are included so that they will verify the SSLv2 decoder when it is added.

The commit message in this PR seems to say otherwise.
Is it fixing SSLv2 or SSLv3 detect patterns ?

2022-04-27 09:25 UTC, giannitedesco commented
> The commit message in this PR seems to say otherwise. Is it fixing SSLv2 or SSLv3 detect patterns ?

This is fixing SSLv2 detect patterns.

There are two distinct things, whether we detect an off-port flow as SSLv2 (which current code does not, and this patch fixes). But then there is decoding the SSLv2 frames, after you have identified SSL/TLS and associated he decoder to that flow.

There are actually numerous things that the SSL/TLS decoder does not support and one of them is SSLv2, which has an incompatible frame format and totally different handshake message structure. SSLv3 and TLS use the same frame formats and are broadly compatible with each other.

2022-04-27 09:27 UTC, giannitedesco commented
Anyway, adding support for decoding SSLv2 (and fragmented handshakes for that matter) is another question, and they are much bigger jobs.

2022-04-27 13:06 UTC, catenacyber commented
I see that 01 03 01 is indeed used for sslv2-tls1_0-client-handshake.pcap

But I do not see which pattern is used for sslv2-handshake.pcap
Is something missing ?

> Anyway, adding support for decoding SSLv2 (and fragmented handshakes for that matter) is another question, and they are much bigger jobs.

Ok, understood

2022-04-27 13:07 UTC, catenacyber commented
> > Flow has
> > ```
> >   "app_proto": "tls",
> >   "app_proto_tc": "failed",
> > ```
> > 

If we want to fix SSLv2 detect patterns, we should also detect the patterns to client (from server)
Here, there are only to server (from client), right ?

2022-04-28 06:34 UTC, inashivb commented
> 

There is one but seems like it is
1. bound to features (See example text.yaml in https://github.com/oiSF/suricata-verify)
 or 
 2. skipping an entire test (e.g. https://github.com/OISF/suricata-verify/blob/master/tests/dhcp-request-flood/test.yaml#L3)
 
 I tried it on specific filters and it does not seem to work that way as of now.

2022-05-17 02:02 UTC, giannitedesco commented
> > > Flow has
> > > ```
> > >   "app_proto": "tls",
> > >   "app_proto_tc": "failed",
> > > ```
> 
> If we want to fix SSLv2 detect patterns, we should also detect the patterns to client (from server) Here, there are only to server (from client), right ?

That's right, I can investigate adding the reverse direction filter, too, thanks.

2022-05-17 02:03 UTC, giannitedesco commented
> > @inashivb is there a `skip` keyword for Suricata-verify ?
> 
> There is one but seems like it is
> 
>     1. bound to features (e.g. https://github.com/OISF/suricata-verify/blob/master/tests/filestore-v2.3-fserror/test.yaml#L7)
>        or
> 
>     2. skipping an entire test (e.g. https://github.com/OISF/suricata-verify/blob/master/tests/dhcp-request-flood/test.yaml#L3)
> 
> 
> I tried it on specific filters and it does not seem to work that way as of now.

Aha, thanks, okay, for now I will forget about decoder events in the test cases and we can add tests for the decoder if and when the decoder is added in future.

2023-03-29 11:48 UTC, catenacyber commented
Thanks @giannitedesco I am closing this, waiting for a new version then

2023-03-29 11:48 UTC, closed without merging