detect/proto/v2: remove unittest
OISF/suricata pull request #6828
Opened 2022-01-20 17:33 UTC by TheKharleeci

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ ] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

Previous PR:  #6827 

Describe changes:
- remove unittest that has been converted to Suricata-Verify

suricata-verify-pr: 670

2022-01-20 17:45 UTC, jufajardini approved these changes
It looks good to me, thanks! :)

2022-01-21 09:16 UTC, victorjulien approved these changes

2022-01-24 07:42 UTC, victorjulien requested changes
Git ID issue

2022-01-24 22:22 UTC, TheKharleeci commented
Followed By: #6857

2022-01-24 22:22 UTC, closed without merging