log/diag: Support diagnostic stacktraces on SIGSEGV/SIGABRT
OISF/suricata pull request #6849
Opened 2022-01-23 14:11 UTC by jlucovsky

This PR adds stack trace logging when Suricata stops due to SIGABRT or SIGSEGV.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [4973](https://redmine.openinfosecfoundation.org/issues/4973)

Describe changes:
- Cherry-pick commits for issue [4526](https://redmine.openinfosecfoundation.org/issues/4526)

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2022-01-24 05:10 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 5886

2022-01-27 06:59 UTC, victorjulien requested changes

2022-01-27 06:59 UTC, victorjulien commented on configure.ac
> +    AC_CHECK_LIB(unwind,unw_backtrace,,LIBUNW="no")
for this backport I would not want it to use this by default, but instead only compile it in if `--enable-...` is specified.

2022-01-27 14:06 UTC, jlucovsky commented
Continued in #6872

2022-01-27 14:06 UTC, closed without merging