log-pcap: fix segfault on lz4 compressed pcaps
OISF/suricata pull request #6875
Opened 2022-01-27 16:16 UTC by oxagast

Moved a file existence check to fix segfault if Suricata tries to write to an lz4 compressed .pcap file if you don't have permission to write to it.  Also removed the previous code that would log this elsewhere, so you don't get double log entries.

https://redmine.openinfosecfoundation.org/issues/5022

2022-01-27 18:59 UTC, oxagast reviewed
Fixed the formatting so checks don't fail.

2022-01-27 20:17 UTC, jufajardini requested changes
Thanks for your interest in contributing to Suricata!

We would appreciate if you followed our [code submission criteria](https://github.com/OISF/suricata/blob/master/doc/devguide/codebase/contributing/code-submission-process.rst) :)
Especially:
- commit message formatting
- commit message and naming convention (so something like: `log-pcap: fix segfault on lz4 compressed pcaps` and then detail more in the commit body? )
- don't add unnecessary commits (if the formatting fix covers your code changes only, please squash them ;) )

Also, have you signed the [Suricata Contribution Agreement](https://suricata.io/our-story/contribution-agreement/)?

2022-01-28 05:00 UTC, oxagast commented
Hi,
Thanks for the tips.  I've signed the contribution agreement, yes.  I've also edited the title of the PR to reflect naming conventions.  As for the second commit that was only an edit to the formatting, I didn't think that it would allow a merge if the automated checks didn't pass.  Now I'm not sure what you mean by squash the latest change with only formatting edits though, I didn't know there was a way to remove edits from the version tracker once they were committed and pushed.  Is there a way to do that?  Or do you just mean marge the two commits?

2022-01-28 07:01 UTC, victorjulien requested changes
See inline comments

2022-01-28 07:01 UTC, victorjulien commented on src/log-pcap.c
> +        comp->file = fopen(pl->filename, "w");
If `comp->file` is null here, I think it means we didn't properly error check something during setup. I think the issue should be handled during setup/initialization (or file rotation)

2022-01-28 08:58 UTC, jufajardini commented
> Hi, Thanks for the tips. I've signed the contribution agreement, yes. I've also edited the title of the PR to reflect naming conventions. As for the second commit that was only edited formatting, I didn't think that it would allow a merge if the automated checks didn't pass. Now I'm not sure what you mean by squash the latest change with only formatting edits though, I didn't know there was a way to remove edits from the version tracker once they were committed and pushed. Is there a way to do that? Or do you just mean marge the two commits?
> 
> Edit: I think I figured out how to squash them with `git merge master --squash`.

Kudos! Now you can follow those with the next PR submission :) Can you also create a ticket on our redmine project, to go with that iteration?

2022-01-30 01:22 UTC, oxagast commented
Probably correct to check if this directory is writeable on startup.  I didn't happen to look, is everything else (that's working properly) also checked this way?  I'm guessing that if the perms somhow got changed incorrectly while Suricata is running it would also fail that way, but the risk is much lower and the performance implications may not be worth doing it in the packet thread.
I have created a ticket on redmine with a backtrace.

2022-01-31 07:25 UTC, inashivb commented
> Probably correct to check if this directory is writeable on startup. I didn't happen to look, is everything else (that's working properly) also checked this way?

Sounds about right to me. Directory should exist and be writable if we are willing to write something in there.

2022-07-06 13:35 UTC, oxagast commented
Sorry, I completely forgot about this. I'll have to take another look into it. Thanks for reminding me.

2022-07-06 16:31 UTC, oxagast commented
So I just recompiled the latest version out of OSIF:master and it seems it is _already fixed_.  Before Suricata would try to log the .lz4 compressed logs to a separate directory under the default logging dir.  If that dir was not writable it would fault.  However now it seem Suricata has **changed where it is dropping the .lz4 logs**, and is now putting them in the default (or user specified) logging directory, not in a sub-directory.  So it seems to be fixed, either intentionally or unintentionally.  I'll now close this issue.

Thanks!

2022-07-06 16:31 UTC, closed without merging