detect-pcre/v1: remove unittests
OISF/suricata pull request #6942
Opened 2022-02-07 17:17 UTC by TheKharleeci

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ ] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [ ] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

Describe changes:
-remove unittests that have been converted to Suricata-Verify

suricata-verify-pr: 717

2022-02-08 05:30 UTC, inashivb reviewed
LGTM on the first sight. But, the diff here is not making things easy and given that this is a big PR, I'll request an extra pair of eyes
^^ @jufajardini 

Also, @TheKharleeci we should probably also mention in this commit that the tests were converted to s-v tests just like all other commits you've made ;)

2022-02-08 05:30 UTC, inashivb commented on src/detect-pcre.c
> +                 "lalala\\\\/\"; sid:1;)";
Was this clang-format?

2022-02-08 16:02 UTC, jufajardini requested changes
So many lines removed :D 🎉 

One nit comment (about renaming tests, see inline)

And two considerations that relate to how some of the tests are being covered (or not) by the corresponding S-V tests proposed, so we make sure to check that, before we remove them.

2022-02-08 16:02 UTC, jufajardini commented on src/detect-pcre.c
>                     DetectPcreTestSig08);
Can these be renamed to reflect the removal of the previous related tests?

2022-03-04 13:16 UTC, TheKharleeci commented
Followed By: #7109

2022-03-04 13:16 UTC, closed without merging