detect/config: Raise errors if test mode discovers invalid classification.config
OISF/suricata pull request #7071
Opened 2022-02-25 15:11 UTC by jlucovsky

Continuation of #6878 

This PR adds logic to raise an error in test mode (only) if classification.config won't parse properly.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [4554](https://redmine.openinfosecfoundation.org/issues/4554)

Describe changes:
- Propagate classification.config parse errors
- Raise error if in test mode and classification.config won't load

Updates:
- Rebase
- 
suricata-verify-pr: 712
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2022-02-26 02:05 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 6395

2022-03-04 15:01 UTC, victorjulien requested changes

2022-03-04 15:01 UTC, victorjulien commented on src/util-classification-config.c
> +                "Invalid Classtype in "
would expect `Invalid Classtype '%s' in classification.config file`. I first read the error as "we found an error in file X".

Maybe even better would be `Invalid Classtype '%s' in classification.config file %s`

2022-03-04 18:03 UTC, jlucovsky commented on src/util-classification-config.c
> +        SCLogWarning(SC_WARN_CLASSIFICATION_CONFIG,
Warning since execution continues (except in test mode).

2022-03-05 14:36 UTC, jlucovsky commented
Continued in #7114

2022-03-05 14:36 UTC, closed without merging