smb: fix flag parsing; set event when records in wrong direction - v3
OISF/suricata pull request #7084
Opened 2022-02-28 22:05 UTC by jasonish

Previous PR: https://github.com/OISF/suricata/pull/7053

Changes from last PR:
- Methods `.is_request()` and `.is_reply()` instead of using 0 and 1 for direction.
- Some debug logging.
- Rules for wrong direction

Ticket: https://redmine.openinfosecfoundation.org/issues/4945

2022-02-28 22:08 UTC, jasonish commented
Possible tests for this: https://github.com/OISF/suricata-verify/pull/768, but still require support for alerting on frames.

2022-03-01 06:20 UTC, victorjulien requested changes
Overall approach looks good. A few inline comments.

2022-03-01 06:20 UTC, victorjulien commented on rust/src/smb/smb.rs
> +                                                if smb_record.direction == 0 {
`.is_request()`?

2022-03-01 06:20 UTC, victorjulien commented on rust/src/smb/smb.rs
> +                                                if smb_record.direction == 1 {
`.is_reply()`?

2022-03-01 06:20 UTC, victorjulien commented on rust/src/smb/smb1_records.rs
> +    pub fn is_reply(&self) -> bool {
would `is_response` be a better fit with `is_request`?

2022-03-01 06:20 UTC, victorjulien commented on rust/src/smb/smb1_records.rs
> +    pub fn is_reply(&self) -> bool {
wireshark also talks about requests and responses

2022-03-01 06:20 UTC, victorjulien commented on rust/src/smb/smb1_records.rs
> +pub const SMB1_FLAGS_REPLY: u8 = 0x80;
`SMB1_FLAGS_RESPONSE`

2022-03-02 05:05 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 6439

2022-03-02 17:07 UTC, jasonish commented
Comments addressed in https://github.com/OISF/suricata/pull/7093.

2022-03-02 17:07 UTC, closed without merging