Mime url prefix
OISF/suricata pull request #7103
Opened 2022-03-03 22:56 UTC by regit

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5174

Describe changes:
- Add scheme to URL now that Suricata supports multiple scheme
- Add some extensions to exe list
- Add link type in email

2022-03-04 04:40 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 6462

2022-03-04 05:13 UTC, victorjulien requested changes

2022-03-04 05:13 UTC, victorjulien commented on src/output-json-email-common.c
> +#include <stdbool.h>
should already be in suricata-common.h

2022-03-04 05:13 UTC, victorjulien commented on src/output-json-email-common.c
> +                    if (url->url_flags) {
formatting is off

Also, can it just be 3 lines like
`has_exe_url = ((url->url_flags & URL_IS_EXE) != 0);`

2022-03-04 05:13 UTC, victorjulien commented on src/util-decode-mime.c
> +                    memcpy(tempUrl, schemeStr, schemeStrLen);
prefer switching to `SCCalloc` instead

2022-04-26 15:07 UTC, suricata-qa commented
Warning: no commits in this PR have specified the following ticket(s):
- 5174 - https://redmine.openinfosecfoundation.org/issues/5174

Please update the commit(s) and submit a new PR.

2022-06-03 09:32 UTC, victorjulien commented
Shivani can you pick this one up and add some SV tests as well?

2022-06-14 06:21 UTC, inashivb commented
> Shivani can you pick this one up and add some SV tests as well?

On it today.

2022-06-14 08:16 UTC, victorjulien commented on src/util-decode-mime.c
> +                    memcpy(tempUrl, schemeStr, schemeStrLen);
looks like I misread this for a memset to 0

2022-06-14 09:15 UTC, inashivb commented
Upon testing, this seems to be breaking the existing logging.
e.g. s-v test `smtp-extract-url-schemes` currently logs:
```
  "email": {
    "status": "PARSE_DONE",
    "from": "kKOEWPYxSvc@ajMvlQs1O4UA.com",
    "to": [
      "q7mp@Ku6FXfnLmo.com"
    ],
    "url": [
      "ftp://172.42.48.124",
      "https://facebook.com",
      "http://test-site.org/blah/123/",
      "http://google.com"
    ],
    "subject": "70meCK6P2y KvF 30cBys82YG OIrkmaK",
    "subject_md5": "0f99ded315de23e87d720f4c5c8fb7d4"
```

but with this patch, we see
```
  "email": {
    "status": "PARSE_DONE",
    "from": "kKOEWPYxSvc@ajMvlQs1O4UA.com",
    "to": [
      "q7mp@Ku6FXfnLmo.com"
    ],
    "has_ipv6_url": false,
    "has_ipv4_url": false,
    "has_exe_url": false,
    "url": [
      "ftp://ftp://172.42.48.124",
      "https://https://facebook.com",
      "http://http://test-site.org/blah/123/",
      "http://http://google.com"
    ],
    "subject": "70meCK6P2y KvF 30cBys82YG OIrkmaK",
    "subject_md5": "0f99ded315de23e87d720f4c5c8fb7d4"
  }
```
Notice the extra prefix in all urls..

2022-06-14 09:58 UTC, victorjulien commented
Interesting, I think I've seen the issue somewhere as well, but can't remember where

2022-06-14 10:06 UTC, inashivb commented
To me it seems like the url is getting copied w its prefix as prefix already seems to be a part of the `tok` https://github.com/OISF/suricata/blob/master/src/util-decode-mime.c#L1069
I cannot seem to reproduce the bug mentioned on the redmine ticket..
Is it for certain specific cases @regit ? Could you please share the pcap where this fails?

2022-06-18 08:24 UTC, regit commented
272786908cf130b7d84324af141dbad6b7695a58 has been merged so the patch [500dcb1](https://github.com/OISF/suricata/pull/7103/commits/500dcb109381166824d99945645fc50430278149) is useless. I saw the MR when starting to work on it but wanted to have a simpler approach.

2022-06-18 10:50 UTC, regit commented
It was global. I'm going to check with my pcap samples and suricata-verify ones.

2022-06-18 13:11 UTC, regit commented
OK, got it: the patch introducing the scheme support breaks the logging if ever the configuration is not updated. Using master code and non updated configuration I got this output with the pcap from test from suricata-verify:
```
  "email": {
    "status": "PARSE_DONE",
    "from": "kKOEWPYxSvc@ajMvlQs1O4UA.com",
    "to": [
      "q7mp@Ku6FXfnLmo.com"
    ],
    "url": [
      "s://facebook.com",
      "://test-site.org/blah/123/",
      "://google.com"
    ]
  }
}
```

2022-06-18 13:39 UTC, closed without merging