template: convert to SCLogDebug
OISF/suricata pull request #7218
Opened 2022-04-08 08:28 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44427

Describe changes:
- template: convert to SCLogDebug

Is there a reason it was `SCLogNotice`

2022-04-10 02:00 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 6856

2022-04-11 21:41 UTC, jasonish commented
> Is there a reason it was `SCLogNotice` ?

Mostly to aid in development, it helps to be a little more verbose during initial development. I think this partly comes from the last dev training as well, it helps trace the execution while getting started.

2022-04-11 21:42 UTC, jasonish commented on src/app-layer-template.c
> +        SCLogDebug("Registering Template protocol parser.");
I think this one should at least stay.

2022-04-11 21:43 UTC, jasonish requested changes
I think its help to at least leave the registration one during development, so you know all is good.  And in that case we should probably keep the related TODO around.

2022-04-14 11:56 UTC, catenacyber commented
Thanks Jason, continued in https://github.com/OISF/suricata/pull/7237

2022-04-14 11:56 UTC, closed without merging