doc: intro doc updates
OISF/suricata pull request #7492
Opened 2022-06-06 20:25 UTC by jmtaylor90

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

https://redmine.openinfosecfoundation.org/issues/5182

Describe changes:
- This work towards the goals stated in 5182.
-
-

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2022-06-08 19:43 UTC, jufajardini requested changes
Overall it's looking good to me, thanks for your work!

I've left minor comments inline.

Only thing I'm not sure about is the example rule change. I've asked the team for input, and will try to give feedback on that asap :)

2022-06-08 19:43 UTC, jufajardini commented on doc/userguide/rules/intro.rst
> +The availability of these protocols depends on whether the protocol is enabled in the configuration file, suricata.yaml.
We are trying to enforce the <80 character limit for new changes, to comply with Sphinx recommendations. Can you make sure that the lines where you add changes are compliant?

 (this isn't a hard rule, I sometimes and up with 80 or 81)

2022-06-08 19:43 UTC, jufajardini commented on doc/userguide/rules/intro.rst
> +this section, highlighting the different parts of the signature.
Thoughts:

Even if we change the example rule, I think it's still useful/ valid to mention that ET has an open dataset that folks can use with Suricata (and/or learn from, when starting to write Suricata rules. Maybe even mention SV as a source of more rule examples).

2022-06-08 19:43 UTC, jufajardini commented on doc/userguide/rules/intro.rst
> +    :example-rule-action:`alert` :example-rule-header:`http $HOME_NET any -> $EXTERNAL_NET any`  :example-rule-options:`(msg:"HTTP GET Request Containing Rule in URI"; flow:established,to_server; htt
Shouldn't `classtype` be updated here, now?

2022-06-08 22:30 UTC, jufajardini commented
> Overall it's looking good to me, thanks for your work!
> 
> I've left minor comments inline.
> 
> Only thing I'm not sure about is the example rule change. I've asked the team for input, and will try to give feedback on that asap :)

Folks think the new rule has some advantages over the old one, so thanks for that, as well! =]

Could you leave somehow a comment about the ET open ruleset and SV tests as good places for more rule examples, for folks who are learning how to write their rules?

2022-06-15 23:06 UTC, jmtaylor90 commented
Thank you very much @jufajardini ! updated PR is https://github.com/OISF/suricata/pull/7548

2022-06-15 23:06 UTC, closed without merging