Document rules internals - v1
OISF/suricata pull request #7635
Opened 2022-07-21 23:49 UTC by jufajardini

While advancing on the task of better understanding and describing how Suricata inspects packets and trying to explain to Jason what I did understand, we thought that adding this documentation could be a good intermediary step...

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5449

Describe changes:
Added a page that explains how rules are prioritized by Suri, as well
as what main different types of inspection happen and what elements are
involved when ordering rules.

2022-07-27 20:50 UTC, jmtaylor90 commented on doc/userguide/rules/rules-internals.rst
> +   Contect (``DetectEngineCtx``) structure, taking into consideration several
Is this Detect Engine Context?

2022-07-27 21:21 UTC, jmtaylor90 commented
This is great, thank you!

2022-07-28 06:01 UTC, victorjulien requested changes
Nice work. Some inline comments.

2022-07-28 06:01 UTC, victorjulien commented on doc/userguide/rules/rules-internals.rst
> +#. Application layer protocol transactions.
This deserves a bit more explanation, as it has its own logic. Each parser has its own state machine, where it uses a per direction parsing state "progress". For each progress value keywords can be registered. E.g. http has a value "request line available" for which we registered keywords like http.uri, http.method, etc. If in the traffic we reach this state, the sigs with those keywords may be already evaluated, even if they have a lower prio than say a body inspecting sig.

2022-07-28 13:35 UTC, jufajardini commented on doc/userguide/rules/rules-internals.rst
> +   Contect (``DetectEngineCtx``) structure, taking into consideration several
Yes, that. Thanks!

2022-07-28 19:28 UTC, jufajardini commented
Replaced by: https://github.com/OISF/suricata/pull/7655

2022-07-28 19:28 UTC, closed without merging