detect/alert: ensure reject action is applied to packet/flow - v2
OISF/suricata pull request #7682
Opened 2022-08-02 22:23 UTC by jufajardini

Previous PR: #7661 

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5458

Changes from last PR:
- Added two unittests to check for correct packet-action flags after signature matching

Thoughts:
- should more unittests be added?
- Many places call PacketDrop in contexts where we don't have a rule nor is it clear what action resulted in the drop. I passed ACTION_DROP in all those cases. Wondering if we should have something more specific/descriptive?

2022-08-03 02:45 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 8465

2022-08-03 05:43 UTC, victorjulien requested changes
See inline comments

2022-08-03 05:43 UTC, victorjulien commented on src/detect-engine-alert.c
> +    if (s->action & (ACTION_DROP | ACTION_REJECT_ANY)) {
looking at how `s->action` is set up, this is a bit redundant. For reject we always also set `ACTION_DROP`. There is no harm in showing the reject here, but I would like 2 additions:
1. a comment stating this
2. a `DEBUG_VALIDATE_BUG_ON` that makes sure `ACTION_DROP` is always set in this branch

2022-08-03 05:43 UTC, victorjulien commented on src/detect-engine-alert.c
> +#ifdef UNITTESTS
can these be moved into (a new) `src/tests/detect-engine-alert.c`

2022-08-03 05:43 UTC, victorjulien commented on src/detect-engine-threshold.c
> +            PacketDrop(p, new_action, PKT_DROP_REASON_RULES_THRESHOLD);
new_action seems to have a different set of flags. It has `TH_ACTION_DROP`, but is treated here as if it has `ACTION_DROP`. Even if these would be the same a safer approach would be to just pass `ACTION_DROP` here explicitly.

2022-08-03 05:43 UTC, victorjulien commented on src/detect-engine-threshold.c
> +            PacketDrop(p, new_action, PKT_DROP_REASON_RULES_THRESHOLD);
Btw the reject case below should also act like reject+drop, can you review that it does?

2022-08-15 17:50 UTC, jufajardini commented
Replaced by: https://github.com/OISF/suricata/pull/7723

2022-08-15 17:50 UTC, closed without merging