decode/vlan: Extend VLAN encapsulation support to 3 levels
OISF/suricata pull request #7786
Opened 2022-08-28 12:34 UTC by jlucovsky

Continuation of #7785

This PR extends Suricata's support for VLANs from 2 to 3 levels. There is no standard for 3 levels of VLANs but 3 levels are not uncommon in some environments.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [2816](https://redmine.openinfosecfoundation.org/issues/2816)

Describe changes:
- Increase VLAN level support to 3 levels
- List all VLAN levels in output.
- Add "Q-in-Q-in-Q" unittest.

Updates
- Update zero-initializer to address Centos-7 failure.

suricata-verify-pr: 902
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2022-08-28 15:05 UTC, suricata-qa commented
WARNING:
 
 | field | test | baseline | % |
|--|--|--|--| 
| | tlpw2_single_stats_chk | | |
| .flow.spare | 1950386 | 1835514 | 106.26% |
| | tlpw2_autofp_stats_chk | | |
| .flow.spare | 1953265 | 1812994 | 107.74% |
| | tlpw1_stats_chk | | |
| .tcp.rst | 132135 | 105279 | 125.51% |
| | tlpr1_stats_chk | | |
| .flow.memuse | 577282424 | 845888448 | 68.25% |
| .http.memuse | 0 | 49320 | 0.0% |
| | ips_afp_stats_chk | | |
| .flow.end.state.new | 57391 | 10800 | 531.4% |
| .flow.end.tcp_liberal | 260066 | 108000 | 240.8% |
| .flow.memuse | 888980496 | 1081197888 | 82.22% |
| .tcp.reassembly_gap | 698405 | 108000 | 646.67% |
| .app_layer.tx.dcerpc_tcp | 1024416 | 1101600 | 92.99% |
| | generic_stats_chk | | |
| .capture.kernel_drops | 95500 | 5654519 | 1.69% |
| .flow.end.state.new | 6850 | 14867 | 46.08% |
| .flow.end.tcp_state.syn_recv | 4 | 52 | 7.69% |
| .flow.end.tcp_state.established | 54394 | 61527 | 88.41% |
| .flow.memuse | 777095104 | 709384128 | 109.55% |
| .tcp.segment_memcap_drop | 0 | 11729 | 0.0% |
| .tcp.reassembly_gap | 97856 | 114099 | 85.76% |
| .tcp.insert_data_normal_fail | 0 | 11358 | 0.0% |
| .app_layer.error.http.parser | 32 | 55 | 58.18% |
| .app_layer.error.smtp.gap | 41 | 61 | 67.21% | 

Pipeline 8841
WARNING: THERE IS A KNOWN BAD BASELINE WITH PACKET DROPS. bE MINDFUL OF ANY RESULTS.

2022-09-30 08:56 UTC, victorjulien requested changes

2022-09-30 08:56 UTC, victorjulien commented on src/defrag.c
> +    p1 = BuildTestPacket(IPPROTO_ICMP, 1, 0, 1, 'A', 8);
declare p1 here

2022-09-30 08:56 UTC, victorjulien commented on src/defrag.c
> +    p2 = BuildTestPacket(IPPROTO_ICMP, 1, 1, 0, 'B', 8);
declare p2 here

2022-09-30 08:56 UTC, victorjulien commented on src/defrag.c
> +    SCFree(r);
PacketFree?

2022-09-30 08:56 UTC, victorjulien commented on src/defrag.c
> +    SCFree(p1);
PacketFree?

2022-09-30 08:56 UTC, victorjulien commented on src/decode-erspan.c
> -        if (p->vlan_idx >= 2) {
think it would be good to have a `VLAN_MAX_LAYERS` or something?

2022-09-30 14:16 UTC, jlucovsky commented
Continued in #7951

2022-09-30 14:16 UTC, closed without merging