Minor copyright/v2
OISF/suricata pull request #7797
Opened 2022-08-30 16:13 UTC by inashivb

Previous PR: https://github.com/OISF/suricata/pull/7795

Changes since last PR:
- Fix copyrights for non range years
- Make updates to the entire codebase
- clang fmt changes done separately as they seemed intrusive

2022-08-30 16:15 UTC, inashivb commented on rust/cbindgen.toml
> +header = """/* Copyright (C) 2019-2022 Open Information Security Foundation
Should probably be 2022?

2022-08-30 16:16 UTC, inashivb commented
@jufajardini could you please help review this?

2022-08-30 17:15 UTC, jufajardini commented on rust/cbindgen.toml
> +header = """/* Copyright (C) 2019-2022 Open Information Security Foundation
Makes sense to me!

2022-08-30 17:32 UTC, jufajardini requested changes
Found some files that were created on 2022 and which won't need the copyright update either, commented on one of them :)

2022-08-30 17:32 UTC, jufajardini commented on rust/src/detect.rs
> +/* Copyright (C) 2022-2022 Open Information Security Foundation
Another exception case! :P

2022-08-30 19:37 UTC, catenacyber commented
Did you use a script to create this and modify > 1k files ?
Can it be run in CI ?

2022-08-31 04:28 UTC, inashivb commented
> Did you use a script to create this and modify > 1k files ? 

Yeah. Kind of. I used a grep + sed oneliner.

> Can it be run in CI ?

I was thinking that maybe we could do this the start of every year. Now that all the files are current, what should we add in the CI?
Or do you mean using CI as an indicator to do this kind of an update. That's actually much more reliable than remembering to do this every year indeed.
Did I get you right?

2022-08-31 04:31 UTC, inashivb commented on rust/src/detect.rs
> +/* Copyright (C) 2022-2022 Open Information Security Foundation
Thanks. :)
Fixed in the new rev.

2022-08-31 04:32 UTC, closed without merging

2022-08-31 12:02 UTC, catenacyber commented
> > Did you use a script to create this and modify > 1k files ?
> 
> Yeah. Kind of. I used a grep + sed oneliner. But, there are some corner cases.
> 

Can you put this one-liner in the commit description ?

> > Can it be run in CI ?
> 
> I was thinking that maybe we could do this the start of every year. Now that all the files are current, what should we add in the CI? Or do you mean using CI as an indicator to do this kind of an update. That's actually much more reliable than remembering to do this every year indeed. Did I get you right?

Should every file have an updated copyright to 2022 ? Or just until the last year it was modified ?

2022-09-01 08:16 UTC, inashivb commented
> Can you put this one-liner in the commit description ?

Yes. I'll write down a script for the series of commands. 
 
> Should every file have an updated copyright to 2022 ? Or just until the last year it was modified ?

hmmm i thought it was always supposed to be current. i am not very sure. No one seemed to mention this either.

2022-09-01 15:23 UTC, jufajardini commented
> > Can you put this one-liner in the commit description ?
> 
> Yes. I'll write down a script for the series of commands.
> 
> > Should every file have an updated copyright to 2022 ? Or just until the last year it was modified ?
> 
> hmmm i thought it was always supposed to be current. i am not very sure. No one seemed to mention this either.

I had a feeling that we did the "update-when-change" thing because it was more practical, only...

2022-09-01 16:23 UTC, inashivb commented
> I had a feeling that we did the "update-when-change" thing because it was more practical, only...

In that case, let's take other folks' opinion in. Maybe this is not needed at all then.