security: prevents process creation
OISF/suricata pull request #7862
Opened 2022-09-14 18:51 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5373

Describe changes:
- optionally calls `setrlimit(RLIMIT_NPROC, 0)` to prevent process creation by Suricata process

Modifies #7858 with better doc

libhtp-pr: 366

2022-09-15 01:20 UTC, suricata-qa commented
Information:
 

ERROR: QA failed on tlpw1_files_sha256.
 | field | baseline | test | % |
|--|--|--|--| 
| | tlpw1_stats_chk | | |
| .app_layer.error.http.parser | 64 | 47 | 73.44% |
| | tlpr1_stats_chk | | |
| .app_layer.error.http.parser | 1548 | 1103 | 71.25% |
| | generic_stats_chk | | |
| .capture.kernel_drops | 0 | 75424 | - |
| .flow.end.tcp_state.syn_sent | 0 | 161 | - |
| .flow.end.tcp_state.fin_wait1 | 0 | 36 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 8 | - |
| .flow.end.tcp_state.time_wait | 0 | 7 | - |
| .flow.end.tcp_state.last_ack | 0 | 5 | - |
| .flow.end.tcp_state.close_wait | 0 | 37 | - |
| .tcp.reassembly_gap | 80952 | 90337 | 111.59% |
| .app_layer.error.http.parser | 0 | 10 | - |
| .app_layer.error.ftp.gap | 0 | 1 | - |
| .app_layer.error.smtp.gap | 0 | 20 | - |
| .app_layer.error.dcerpc_tcp.parser | 0 | 10 | - | 

Pipeline 9204

2022-09-15 15:16 UTC, jufajardini approved these changes
Doc changes look good to me! :)

2022-09-16 13:50 UTC, catenacyber commented
Waits for CI fix cf https://github.com/OISF/suricata/pull/7871

2022-09-20 08:05 UTC, victorjulien commented on suricata.yaml.in
> +security:
after merging landlock a security config already exists that this should hook into

2022-09-20 08:06 UTC, victorjulien requested changes
see inline comment

2022-09-23 11:52 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/7914

2022-09-23 11:52 UTC, closed without merging