rust: fix lint warnings about if same then else -v7
OISF/suricata pull request #8025
Opened 2022-10-18 01:14 UTC by Rai0Catodic0

Ticket: [4609](https://redmine.openinfosecfoundation.org/issues/4609)

Make sure these boxes are signed before submitting your Pull Request -- thank you.

[ :white_check_mark: ]  I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
    [  :white_check_mark: ] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
 - [ ]  I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Previous PR: #8021 

Describe changes:
- Refactor range.rs to a more readable version

2022-10-18 03:37 UTC, inashivb requested changes
Hi @Rai0Catodic0 !
We're almost there. Just some formatting changes need to be made. Good job incorporating the feedbacks! :)

2022-10-18 03:37 UTC, inashivb commented on rust/src/http2/range.rs
> +    if v.end <= 0 || v.size <= 0{
nit: there should be a space between the condition and the brace

2022-10-18 03:37 UTC, inashivb commented on rust/src/http2/range.rs
> +        // skipped for incomplete range information
nit: unnecessary space added at the end

2022-10-18 03:37 UTC, inashivb commented on rust/src/http2/range.rs
> +
nit: unnecessary newline

2022-10-18 03:37 UTC, inashivb commented on rust/src/http2/range.rs
> +
nit: unnecessary newline

2022-10-18 03:39 UTC, inashivb commented
@Rai0Catodic0 could you please make sure to close your previous revs of a PR when you create a new one? That helps keep only the latest PRs in view. :octocat:

2022-10-19 01:02 UTC, Rai0Catodic0 commented
Closing this in favour of newer PR #8035

2022-10-19 01:03 UTC, closed without merging