dns/eve: add 'HTTPS' type logging
OISF/suricata pull request #8031
Opened 2022-10-18 18:31 UTC by hsadia538

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/4751) ticket.

Draft PR to gather feedback.

Previous PR: #8011

Describe changes:
- Added logic to parse rrtype: HTTPS

2022-10-18 18:33 UTC, hsadia538 commented
- Wrote a Suricata-Verify Test to check the rrtype.
- The test seems to fail and the error log is empty so my guess is the code to parse rrtype:HTTPS is not actually working. Is there any way to actually track the code changes and see what more needs to be done?
- Based on Shivani's comments on the last PR, I made a bunch of code updates, but as it's still not working, I think more work needs to be done.

2022-10-18 19:00 UTC, jufajardini commented
> * Wrote a Suricata-Verify Test to check the rrtype.

Hello! Could you share the Suricata-verify test that you've created?

2022-10-18 19:12 UTC, hsadia538 commented
> > * Wrote a Suricata-Verify Test to check the rrtype.
> 
> Hello! Could you share the Suricata-verify test that you've created?

Its a very basic test with `test.yaml` as follows:

```
# *** Add configuration here ***

checks:
  # Check that we only have requests and responses for A records.
- filter:
    count: 1
    match:
      event_type: "dns"
      dns.rrtype: "HTTPS"
```

2022-10-19 10:02 UTC, inashivb requested changes
Hi @hsadia538!
I think you were moving in the right direction. It seems there's some extra code that may not be needed for logging.
I'd suggest you build on your last rev of this PR. Make the changes on the C side that you made here and it seems you're missing an update to `dns_rrtype_string` on the rust side.

I think the logging should work then.

2022-10-19 20:05 UTC, hsadia538 commented on rust/src/dns/parser.rs
> +
I added it here based on how I saw other rrtypes being parsed. I will take a look again .

2022-10-20 03:05 UTC, inashivb commented on rust/src/dns/parser.rs
> +
Yes, but we don't have to parse this rrtype. We have to make sure to log it's name instead of the rrtype code. At least for this task. 😉

2022-10-21 00:13 UTC, hsadia538 commented
Followed by : #8053

2022-10-21 00:13 UTC, closed without merging