detect-itype.c: Convert unittests to new FAIL/PASS API
OISF/suricata pull request #8060
Opened 2022-10-21 19:30 UTC by hsadia538

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Previous PR #8055
Link to [redmine](https://redmine.openinfosecfoundation.org/issues/4049) ticket:

Describe changes:

- Update  `DetectITypeParseTest08` in detect-itype unit tests

2022-10-21 22:00 UTC, jufajardini requested changes
All tests looking good! :)

One small thing went through: could you fix the commit message? The file extension isn't required in it.

2022-10-23 00:37 UTC, hsadia538 commented
Should I remove the unit test for `DetectITypeMatchTest01` as I opened a suricata-verify PR for the same in the same PR with another commit or 
Should I open a separate PR with one commit for unit test removal?

2022-10-24 18:09 UTC, jufajardini commented
> Should I remove the unit test for `DetectITypeMatchTest01` as I opened a suricata-verify PR for the same in the same PR with another commit or Should I open a separate PR with one commit for unit test removal?

Let's keep that work for a separate PR, as it may take longer to merge the SV test, and this would prevent the merge of this commit, even though it may be ready to go ;)

2022-10-24 18:10 UTC, jufajardini approved these changes
Since the commit message has been updated, the PR LGTM :)

2022-10-24 19:17 UTC, hsadia538 commented
> > Should I remove the unit test for `DetectITypeMatchTest01` as I opened a suricata-verify PR for the same in the same PR with another commit or Should I open a separate PR with one commit for unit test removal?
> 
> Let's keep that work for a separate PR, as it may take longer to merge the SV test, and this would prevent the merge of this commit, even though it may be ready to go ;)

got it now! Thanks

2022-10-25 15:24 UTC, victorjulien commented on src/detect-itype.c
>      itd = DetectITypeParse(NULL, "8");
no need to update this PR, but in future PRs can you update such tests to declare `itd` on the line where it is set? So:
```c
DetectU8Data *itd = DetectITypeParse(...
```

2022-10-27 20:00 UTC, jasonish approved these changes
Looks good to me.

2022-10-28 14:52 UTC, victorjulien commented
Merged in #8113, thanks!

2022-10-28 14:52 UTC, closed without merging