detect-filesize: Convert unittests to new FAIL/PASS API
OISF/suricata pull request #8091
Opened 2022-10-25 21:55 UTC by hsadia538

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Previous PR: https://github.com/OISF/suricata/pull/8087
Link to [redmine](https://redmine.openinfosecfoundation.org/issues/4039) ticket:

Describe changes:

-Update detect-filesize unit tests to FAIL/PASS APIs

2022-10-26 06:34 UTC, victorjulien commented on src/detect-filesize.c
> +    FAIL_IF_NULL(DetectEngineAppendSig(de_ctx, fullstr);
this line looks suspicious in 2 ways: `de_ctx` is used `*de_ctx` elsewhere in the test, but not here. 2nd: brackets mismatch :)

2022-10-26 06:37 UTC, victorjulien requested changes

2022-10-26 06:37 UTC, victorjulien commented on src/detect-filesize.c
>      (*de_ctx)->sig_list = SigInit(*de_ctx, fullstr);
replace with `DetectEngineAppendSig` as well

2022-10-26 06:37 UTC, victorjulien commented on src/detect-filesize.c
>      *de_ctx = DetectEngineCtxInit();
needs a check as well

2022-10-26 06:37 UTC, victorjulien commented on src/detect-filesize.c
>      (*de_ctx)->flags |= DE_QUIET;
this should directly follow the `DetectEngineCtxInit`+its check

2022-10-27 22:11 UTC, hsadia538 commented
Followed by #8104

2022-10-27 22:11 UTC, closed without merging