rust: explicitly convert from Direct to u8 , otherwise when add serde_…
OISF/suricata pull request #8156
Opened 2022-11-06 05:42 UTC by jiamo

We are writing custom app protocol in rust. When we need add serde_json package. It always got error such like 
>note: multiple `impl`s satisfying `u8: PartialEq<_>` found in the following crates: `core`, `serde_json`:
And we think it is good do the conversion explicitly. Follow the suggestion from https://github.com/rust-lang/rust/issues/103968. 

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Describe changes:
- explicitly comvert Direction to u8

2022-11-06 07:00 UTC, victorjulien commented
Minor request: please update the commit message to have a short subject line followed by a new line, then the body with the explanation. See further https://github.com/OISF/suricata/blob/6d3140bc012b093a361506b5c4f21cc9ae8878e8/doc/userguide/devguide/codebase/contributing/code-submission-process.rst#commits

@jasonish can you check the code?

2022-11-06 07:45 UTC, jiamo commented
> Minor request: please update the commit message to have a short subject line followed by a new line, then the body with the explanation. See further https://github.com/OISF/suricata/blob/6d3140bc012b093a361506b5c4f21cc9ae8878e8/doc/userguide/devguide/codebase/contributing/code-submission-process.rst#commits
> 
> @jasonish can you check the code?

Thanks. I rewrite the message. By the way `cargo clippy --all-features --fix` in the work flow failed. I think it is not caused by my commit.

2022-11-06 20:55 UTC, catenacyber commented
> Thanks. I rewrite the message. By the way `cargo clippy --all-features --fix` in the work flow failed. I think it is not caused by my commit.

Indeed, cf https://github.com/OISF/suricata/pull/8147 for the Rust check failure

2022-11-07 04:18 UTC, alexsunrise commented
> Minor request: please update the commit message to have a short subject line followed by a new line, then the body with the explanation. See further https://github.com/OISF/suricata/blob/6d3140bc012b093a361506b5c4f21cc9ae8878e8/doc/userguide/devguide/codebase/contributing/code-submission-process.rst#commits
> 
> @jasonish can you check the code?

better to avoid to use `.into()` when your members to CR, personal suggestion.

2022-11-07 07:54 UTC, catenacyber commented
> when your members to CR

What does this mean ?

2022-11-07 13:57 UTC, alexsunrise commented
> > when your members to CR
> 
> What does this mean ?

I mean when your guys to code review, it should be avoid using some code like `.into()`, like `if direction == Direction::ToServer.into()` change to `if direction == Direction::ToServer as u8` or `if direction == u8::from(Direction::ToServe)`. I think it will be better.

2022-11-07 15:05 UTC, victorjulien commented
> > > when your members to CR
> > 
> > 
> > What does this mean ?
> 
> I mean when your guys to code review, it should be avoid using some code like `.into()`, like `if direction == Direction::ToServer.into()` change to `if direction == Direction::ToServer as u8` or `if direction == u8::from(Direction::ToServe)`. I think it will be better.

The `as u8` is a pattern I believe clippy warns against.

Can you explain why you believe one is better than the other?

2022-11-07 15:14 UTC, jiamo commented
This pull request come from I am implementing some custom protocol in rust and need json functions. 
I add serde_json for the purpose. see https://github.com/serde-rs/json/issues/948
I got error because serde_json add `PartialEq` implement for `u8` which cause the error.
So I think we can just explicitly do convert process. The benefit only exists the suricata rust code don't want to conflict another package.   

> Can you explain why you believe one is better than the other?

2022-11-08 12:03 UTC, jasonish commented
The code seems find, but I'm not happy with the "look".  I've replicated the issues by adding serde and a simple serializable struct.  So I still want to look further into this, but it is something we need to resolve. I see serde entering our code at some point or another.

2022-11-08 13:29 UTC, jasonish requested changes
Rebase, and use as u8.  That should be clippy clean and look nicer as well.

2022-11-08 14:05 UTC, catenacyber commented
> Rebase, and use as u8. That should be clippy clean and look nicer as well.

I think the downside of `as u8` is that this is an explicit cast that is losing precision.
So if by mistake we do a u16 as u8 when we should not, there will be no warning, and it can get nasty to debug...

2022-11-08 14:29 UTC, jiamo commented
Happy to see you will go deeper into it.  While @catenacyber said  `as u8` will be `nasty to debug` . Looking forward a more elegant way to do it. 


> The code seems find, but I'm not happy with the "look". I've replicated the issues by adding serde and a simple serializable struct. So I still want to look further into this, but it is something we need to resolve. I see serde entering our code at some point or another.

2022-11-08 15:05 UTC, jasonish commented
> > Happy to see you will go deeper into it. While @catenacyber said `as u8` will be `nasty to debug` . Looking forward a more elegant way to do it.
> > > The code seems find, but I'm not happy with the "look". I've replicated the issues by adding serde and a simple serializable struct. So I still want to look further into this, but it is something we need to resolve. I see serde entering our code at some point or another.
> 
> I wonder if `#[repr(u8)]` would cause any issues with the ffi. It'll catch those cast errors.

`#[repr(u8)]` does seem to do the right thing with respect to FFI and cbindgen.

2022-11-08 15:05 UTC, jiamo commented
Do you mean 
```
#[repr(u8)]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum Direction {
    ToServer = 0x04,
    ToClient = 0x08,
}
```
The problem is still here after change like that.

> I wonder if `#[repr(u8)]` would cause any issues with the ffi. It'll catch those cast errors.

2022-11-08 15:16 UTC, jasonish commented
> Do you mean
> 
> ```
> #[repr(u8)]
> #[derive(Debug, PartialEq, Eq, Clone, Copy)]
> pub enum Direction {
>     ToServer = 0x04,
>     ToClient = 0x08,
> }
> ```
> 
> The problem is still here after change like that.
> 
> > I wonder if `#[repr(u8)]` would cause any issues with the ffi. It'll catch those cast errors.

You still need to use `as u8`, but at least you can't accidentally stick a non-u8 value in the enum.

2022-11-08 16:03 UTC, jiamo commented
> Rebase, and use as u8. That should be clippy clean and look nicer as well.

Done. and change to `#[repr(u8)]`.

2023-05-17 03:50 UTC, jiamo commented
> @jiamo would you rebase and submit a new version of this PR ?

rebase done.

2023-06-09 11:34 UTC, catenacyber commented on rust/src/dcerpc/dcerpc.rs
> +    if direction == Direction::ToServer as u8 && tx.req_done {
These changes do not seem needed

Could you just change `[repr(C)]` to `[repr(u8)]` ?

2023-11-08 10:34 UTC, catenacyber commented
Closing as stale, you can open a new rebased PR with comments taken into account.

2023-11-08 10:34 UTC, closed without merging