Use uniform type for tenant_id
OISF/suricata pull request #8164
Opened 2022-11-12 11:16 UTC by benignbala

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5186

Describe changes:
The tenant_id property is defined as an int in some structures and as uint32_t in some structures.
In some edge case values of tenant_id (For eg. 2^32), this can cause problems.

To address the issue, the following changes have been made:
tenant_id's type has been updated to uint32_t in several files

Please note that this is the same as #7542 . I messed that one up with an incorrect rebase and hence submitting it again. Apologies for the mixup and trouble.

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2022-11-14 07:59 UTC, victorjulien commented
Please check the CI failures, thanks!

2022-11-14 09:30 UTC, benignbala commented
Thanks @victorjulien, Updated the PR with the fix for the CI failure.

2022-11-16 13:56 UTC, inashivb requested changes
Hi @benignbala !
Thank you for your first contribution to our project! :)
I have a few changes to ask w.r.t. commits:
1. Please squash all the extra commits together.
2. Please use a prefix in the commit message defining what part of code you're changing. e.g. here the changes are all over the codebase, so, you'd write `src: use uniform...`

2022-11-30 14:20 UTC, benignbala commented
@inashivb - Apologies for the bother, do the changes look ok?

2022-12-13 18:05 UTC, jufajardini commented
> @inashivb - Apologies for the bother, do the changes look ok?

Hello there! We very much prefer that new changes are incorporated into new PRs, also to help with ensuring that the CI checks are all passing, as required. Sorry for the late answer!

2022-12-19 09:42 UTC, inashivb commented
> @inashivb - Apologies for the bother, do the changes look ok?

Hello!
Apologies for the delay. I was off on a long vacation. I think the commit changes do look ok. Could you please check the CI failures though and see if they're related to your work.
Also, please address @jufajardini 's comments.
Thank you very much for all your effort! :)

2023-05-05 09:14 UTC, victorjulien commented
Closing due to inactivity. If you're interested in picking this back up, please open a new PR addressing the comments. Thanks!

2023-05-05 09:14 UTC, closed without merging

2023-05-05 18:46 UTC, benignbala commented
Apologies @victorjulien. I lost track due to a busy schedule at work. I'll resume work on this bug with a new PR in the next week or so. Also, apologies to those who helped me in this effort for not being able to bring it to completion.