Include less v16
OISF/suricata pull request #8167
Opened 2022-11-14 08:53 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/945

Describe changes:
- Remove unused includes in c files
- adds some options in CI : hyperscan, luajit

Follows #8142 with 
- completing removal of double inclusion, like src/runmode-netmap.c was now including twice "util-time.h"
- Rebase (especially after app-layer-dcerpc-common.h was removed by another PR)

Still TODO after that : run script mininc.py

2022-11-14 15:55 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 10609

2022-11-15 08:43 UTC, victorjulien requested changes
minor changes requested, ready to go after that I think

2022-11-16 15:47 UTC, catenacyber commented on src/alert-syslog.c
> +// ACTION_DROP
Ok

2022-11-16 15:47 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/8174

2022-11-16 15:47 UTC, closed without merging