file/swf: Use lzma-rs decompression instead of libhtp.
OISF/suricata pull request #8171
Opened 2022-11-14 19:14 UTC by cccs-rtmorti

Use the lzma-rs crate for decompressing swf/lzma files instead of the lzma decompressor in libhtp. This decouples suricata from libhtp except for actual http parsing, and means libhtp no longer has to export a lzma decompression interface.

Ticket: #5638

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/5638) ticket: 5638

Describe changes:
- Create a lzma.rs file which exports a lzma decompression function interface.
- In util-file-swf-decompression.c, use this interface instead of the lzma decompression interface presented by libhtp.
- Update error types / constants to reflect lzma-rs error conditions / results.

Update to  #8154

2022-11-15 08:40 UTC, victorjulien requested changes
minor feedback

2022-11-15 08:40 UTC, victorjulien commented on rust/src/lzma.rs
> +use lzma_rs::decompress::{Options, Stream};
can you add a copyright header here?

2022-11-16 15:53 UTC, catenacyber commented on rust/src/lzma.rs
> +                    LzmaStatus::LzmaMemoryError
Thanks for this

2022-11-16 15:53 UTC, catenacyber approved these changes
Thanks for this nice work.

CI : ✅
Code : looks good to me, comments were taken into account
Commits segmentation : ok
Commit messages : nice
Git ID set : looks fine for me
CLA : should be fine
Redmine ticket : ok
Rustfmt : fine for new file
Tests : good enough for me with current ones
Dependencies added: MIT License is good

2022-11-16 19:45 UTC, cccs-rtmorti commented on rust/src/lzma.rs
> +use lzma_rs::decompress::{Options, Stream};
Yup! Sorry I forgot it.

2022-11-16 19:45 UTC, cccs-rtmorti commented
Updated in #8176

2022-11-16 19:45 UTC, closed without merging