http: logs custom headers in a subobject
OISF/suricata pull request #8241
Opened 2022-12-05 09:34 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5320

Describe changes:
- http: logs custom headers in a subobject

To avoid collisions, for instance for `content_range`

With this PR, the output will be
```
    "content_range": {
      "raw": "bytes 10-20/69",
      "start": 10,
      "end": 20,
      "size": 69
    },
    "response_headers": [
      {
        "name": "Content-Range",
        "value": "bytes 10-20/69"
      }
    ]
```

instead of 
```
    "content_range": {
      "raw": "bytes 10-20/69",
      "start": 10,
      "end": 20,
      "size": 69
    },
   "content_range": "bytes 10-20/69"
```

`response_headers` is already used with the config option `dump-all-headers`

suricata-verify-pr: 1026

Replaces #8229  with making `dump-all-headers` win

2022-12-05 09:40 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | build_asan | | |
 

Pipeline 11058

2022-12-05 19:29 UTC, jufajardini approved these changes
Doc changes look good to me :)

2022-12-05 21:25 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 547 | - |
| .flow.end.tcp_state.fin_wait2 | 0 | 1 | - |
| .flow.end.tcp_state.time_wait | 0 | 1 | - |
| .flow.end.tcp_state.close_wait | 0 | 1 | - |
| .tcp.segment_from_pool | 15728353 | 16572389 | 105.37% |
| .app_layer.error.http.parser | 0 | 1 | - |
| .app_layer.error.smtp.gap | 0 | 1 | - | 

Pipeline 11064

2022-12-08 17:39 UTC, jasonish commented
This fixes the `dump-all-headers` taking precedence.  However, there is a breaking with `custom`.  Using:
```
            custom: [last-modified, Accept, "X-Test-Header"]
```
with `master` logs both `accept` and `last_modified` as expected. But with this PR only `last-modified` is logged. Order doesn't seem to matter, I can't get `Accept` logged.

But using:
```
            custom: [Accept, "X-Test-Header"]
```
will log the `accept` header.

In both the above cases, `X-Test-Header` is not being logged, but does exist in my test request headers.

`X-Test-Header` is still not logged with just:
```
            custom: ["X-Test-Header"]
```

The `custom` logging of `X-Test-Header` is broken in master as well though. So perhaps a different issue.

2022-12-08 17:40 UTC, jasonish requested changes
Oddities in custom...

2022-12-08 19:28 UTC, catenacyber commented
> The custom logging of X-Test-Header is broken in master as well though. So perhaps a different issue.

It is not broken, it is the feature.
Only a subset of headers can be logged with custom...

2022-12-08 19:32 UTC, catenacyber commented
Thanks for testing.
Should be fixed in https://github.com/OISF/suricata/pull/8264

2022-12-08 19:32 UTC, closed without merging