Rfb frames v3
OISF/suricata pull request #8322
Opened 2022-12-26 14:31 UTC by hsadia538

- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5717
 
Previous PR: #8313 

Describe changes:
- Fix `frame_len`

suricata-verify-pr: 1045

2022-12-26 20:22 UTC, catenacyber commented
Are you able to investigate the CI failure ?

2022-12-26 21:57 UTC, hsadia538 commented
> Are you able to investigate the CI failure ?

Yes I think so. It's because of the suricata verify pr issue. I have made a new pr for suricata verify tests. Is there a way to trigger the CI checks again without making a new PR?

2022-12-27 03:27 UTC, inashivb commented
> > Are you able to investigate the CI failure ?
> 
> Yes I think so. It's because of the suricata verify pr issue. I have made a new pr for suricata verify tests. Is there a way to trigger the CI checks again without making a new PR?

You need special permissions for that. For now, I have triggered the checks again. Let's see if the right branch gets picked up now.

2022-12-30 12:02 UTC, inashivb requested changes
Nice work, Haleema! :)
Some comments from me inline.

2022-12-30 12:33 UTC, hsadia538 commented on rust/src/rfb/rfb.rs
> +            -1_i64,
From your comments, what I understand is that we don't know the length of the pdu at this point so `-1_i64` won't work either.
Should I skip the length here altogether?

2022-12-30 12:33 UTC, hsadia538 commented on rust/src/rfb/rfb.rs
> +            -1_i64,
Should we have a checker here and then create frames based on the check?

2023-01-02 08:04 UTC, inashivb commented on rust/src/rfb/rfb.rs
> +            -1_i64,
> Should I skip the length here altogether?

Don't know how can we do that.

But, apologies for being unclear, I did not mean that `-1` won't work. I meant that this is fine but should not be final thing. The length of the frame should be updated when we know about it. e.g. in telnet we do this once we know the length: https://github.com/OISF/suricata/blob/master/rust/src/telnet/telnet.rs#L306

2023-01-02 14:12 UTC, hsadia538 commented on rust/src/rfb/rfb.rs
> +            -1_i64,
Ok, so as I understand, I have to update the length of the frame. In the `rfb.rs` we are matching different `RFBGlobalState` so the `set_len` will go in each match statement within the `parse_request` and `parse_response` I have to use `set_len` in each matching block.

2023-01-02 19:43 UTC, hsadia538 commented
Followed by #8337

2023-01-02 19:43 UTC, closed without merging