rfb: add RFB frames
OISF/suricata pull request #8338
Opened 2023-01-02 20:34 UTC by hsadia538

- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5717
 
Previous PR: #8337 

Describe changes:
- Update`frame_len` in the parsing functions
- Fix `commit check` issue

suricata-verify-pr: 1050

2023-01-02 21:02 UTC, hsadia538 commented
I am not able to figure out the issue behind commit check. Looking at the logs I was able to find the steps and error raised but when I see in the file I am able to see the fix in my commit.
I don't see any errors when I do `/autogen.sh` `./configure` and `make`

As per the error log:
```
`error[E0412]: cannot find type Flow in this scope
   --> src/rfb/rfb.rs:577:18
    |
577 |     flow: *const Flow,
    |                  ^^^^ not found in this scope
    |
help: consider importing this enum
    |
20  | use crate::core::Flow;
    |

error[E04[25](https://github.com/OISF/suricata/actions/runs/3825002976/jobs/6507633863#step:12:26)]: cannot find value `IPPROTO_TCP` in this scope
   --> src/rfb/rfb.rs:634:18
    |
634 |         ipproto: IPPROTO_TCP,
    |                  ^^^^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
20  | use crate::core::IPPROTO_TCP;
    |
20  | use libc::IPPROTO_TCP;
    |

error[E04[33](https://github.com/OISF/suricata/actions/runs/3825002976/jobs/6507633863#step:12:34)]: failed to resolve: use of undeclared type `CString`
   --> src/rfb/rfb.rs:664:24
    |
664 |       let ip_proto_str = CString::new("tcp").unwrap();
    |                          ^^^^^^^
    |
help: a struct with a similar name exists
    |
664 |     let ip_proto_str = String::new("tcp").unwrap();
    |                        ~~~~~~
help: consider importing one of these items
    |
20  | use crate::rfb::rfb::std::ffi::CString;
    |
20  | use std::ffi::CString;`
```

But as per [Line 25 ](https://github.com/OISF/suricata/blob/cea5a7367a57d5bcf0d27c91942cf0e8f30741e3/rust/src/rfb/rfb.rs#L25)this exists in the file.

2023-01-03 05:18 UTC, inashivb requested changes

2023-01-03 05:18 UTC, inashivb commented on rust/src/rfb/rfb.rs
> -use crate::core::{ALPROTO_UNKNOWN, AppProto, Flow, IPPROTO_TCP};
It's because you removed this import in this commit and added it back in the next commit. So, the commit should ideally fail to build.

2023-01-03 05:19 UTC, inashivb commented on rust/src/rfb/rfb.rs
> -use crate::core::{ALPROTO_UNKNOWN, AppProto, Flow, IPPROTO_TCP};
Please make sure that the fmt commit only does the formatting and nothing else.

2023-01-03 11:48 UTC, hsadia538 commented
Followed By #8338

2023-01-03 11:48 UTC, closed without merging