decode/vlan: Extend VLAN encapsulation support to 3 levels; flowhash livedev
OISF/suricata pull request #8344
Opened 2023-01-04 15:12 UTC by jlucovsky

Continuation of #7997

This PR extends Suricata's support for VLANs from 2 to 3 levels. There is no standard for 3 levels of VLANs but 3 levels are not uncommon in some environments.

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
- [2816](https://redmine.openinfosecfoundation.org/issues/2816)
- [5270](https://redmine.openinfosecfoundation.org/issues/5270)

Describe changes:
- Increase VLAN level support to 3 levels
- List all VLAN levels in output.
- Add "Q-in-Q-in-Q" unittest.
- flow: optionally use livedev for hash
- Add defines for VLAN max layer and max index
- Unit test updates per review

Updates
- Rebase

suricata-verify-pr: 902

2023-04-07 12:22 UTC, catenacyber commented
@jlucovsky would you rebase this PR ?

2023-04-13 22:35 UTC, suricata-qa commented
Information:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | TREX_GENERIC_stats_chk | | |
| .capture.kernel_drops | 0 | 42775 | 0.01 | 

Pipeline 11375

2023-05-11 12:45 UTC, victorjulien commented
Can you resubmit a PR after rebase, would like to see a new QAlab run as well.

2023-05-11 12:46 UTC, victorjulien requested changes
Needs rebase

2023-05-16 14:45 UTC, closed without merging