smb: fix wrong endian conversion when parse NTLM Negotiate Flags - V2
OISF/suricata pull request #8373
Opened 2023-01-13 03:20 UTC by b1tg

Ticket: https://redmine.openinfosecfoundation.org/issues/5783

Previous PR: https://github.com/OISF/suricata/pull/8372

Changes from last PR:
    - fix invalid json schema error 
    - keep the formatting changes in a separate commit
    - fix email in commit message
  
Signed-off-by: b1tg [b1tg@protonmail.ch](mailto:b1tg@protonmail.ch)

2023-01-13 15:11 UTC, b1tg commented
@victorjulien Hi, CI was failed due to network issue, how can i re-run this.

2023-01-13 15:21 UTC, jufajardini commented
> @victorjulien Hi, CI was failed due to network issue, how can i re-run this.

I have triggered a re-run, but this might be a github actions issue for the moment. If that is the case, we may need to wait a bit ;)

2023-01-14 02:18 UTC, b1tg commented
Seems no re-run triggered anymore🥲

2023-01-16 14:16 UTC, jufajardini commented
> Seems no re-run triggered anymoresmiling_face_with_tear

Triggered another re-run. Let's see how it goes now, I see that the actions that were failing seem to be working with master, now...

2023-01-16 15:29 UTC, b1tg commented
Only `CIFuzz / Fuzzing (address) (pull_request)` is in failed status now, it seems not be re-runed

2023-01-24 17:51 UTC, b1tg commented
Any update? @jufajardini

2023-01-24 21:37 UTC, jufajardini requested changes
Hi, thanks for your bug report and your interest in working on this issue!

Apologies for us not giving any feedback earlier, some periods are a bit busier...

I've left two minor inline comments, and I have some more notes:
- could you please submit a PR with a Suricata-verify test to showcase this? Ideally, the test should fail now, to indicate the issue
- Can you please adjust your commit messages to follow our contribution guidelines? This includes commit message length and style; follow the author name guidelines (we need this info for licensing purposes :) )

Once these aspects are set, please submit a new PR, if it is good, then Victor or Jason will approve and then it could be merged.

I have already updated the redmine ticket and assigned it to you, to reflect the work you've already done here :)

2023-01-24 21:37 UTC, jufajardini commented on rust/src/smb/auth.rs
> +        let blob = hex::decode("a18202313082022da0030a0101a28202100482020c4e544c4d5353500003000000180018009c00000048014801b40000001e001e005800000008000800760000001e001e007e00000010001000fc01000015828
Can you add a comment indicating what's the content of this blob buffer? :)

2023-01-24 21:37 UTC, jufajardini commented on rust/src/smb/ntlmssp_records.rs
> +        let blob = [0x15, 0x82, 0x88, 0xe2];
Ideally, here, too, we'd like to see a comment indicating what info is here

2023-01-25 14:58 UTC, b1tg commented
checkout https://github.com/OISF/suricata/pull/8446

2023-01-25 17:59 UTC, jufajardini commented
Closing this in favour of new version https://github.com/OISF/suricata/pull/8449

2023-01-25 17:59 UTC, closed without merging