output: fix logic error
OISF/suricata pull request #8530
Opened 2023-02-09 18:57 UTC by ProjectMutilation

The logical error may have been made here. Comparison with the upper
 bound of the variable type does not make sense. It may be worth adding
 the cast of one of the multiplication operands to the 64-bit type for
 avoiding overflow

Found by Security Code with Svace static analyzer
Bug: #5789

Signed-off-by: Maxim Korotkov <m.korotkov@securitycode.ru>

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/5789

Describe changes:
- Added cast to ULL one of operand of multiplication for avoiding overflow

#suricata-verify-pr:
#suricata-verify-repo:
#suricata-verify-branch:
#suricata-update-pr:
#suricata-update-repo:
#suricata-update-branch:
#libhtp-pr:
#libhtp-repo:
#libhtp-branch:

2023-02-11 07:23 UTC, ProjectMutilation commented
@victorjulien hi, can you explain why tests were failing please? I don't have idea

2023-02-11 09:57 UTC, victorjulien commented
Probably needs a rebase to master. The failing test was merged yesterday following a fix in master.

2023-02-15 12:12 UTC, jufajardini commented
Tests pass now :)
Could you please square these commits? That rebase commit isn't something we keep in our commit history, like that.

2023-02-16 13:39 UTC, jufajardini requested changes
Please see my inline comment :)

2023-02-16 13:53 UTC, ProjectMutilation commented
> Please see my inline comment :)

yep, i saw it, I'll do it a little later

2023-02-16 17:07 UTC, closed without merging

2023-02-16 17:09 UTC, ProjectMutilation commented
i'll create new pr with clean history :)

2023-10-04 17:32 UTC, jufajardini commented
Followed by: https://github.com/OISF/suricata/pull/8547