smb: add unit tests
OISF/suricata pull request #8679
Opened 2023-04-04 15:52 UTC by b1tg

- [X] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [X] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to redmine ticket: [4865](https://redmine.openinfosecfoundation.org/issues/4865)

I have begun adding unit tests into the SMB parsers, several of these tests have been completed, and I would like hearing your feedback on the code so far.

Signed-off-by: Lancer Cheng b1tg@protonmail.ch

2023-04-11 06:27 UTC, inashivb requested changes
Hello @b1tg !
Thank you for your contribution to our project. I have requested some minor changes. Your work is looking good to me. :)

Could you please add the source of test data to every test?

2023-04-17 11:55 UTC, b1tg commented on rust/src/smb/smb2_records.rs
> +        }
I borrow this function from here, do I need change it too? https://github.com/OISF/suricata/blob/a94ca4462093c0b41f87a7d8433801a0abbb4390/rust/src/smb/log.rs#L55

2023-04-18 05:00 UTC, inashivb commented on rust/src/smb/smb2_records.rs
> +        }
Sure. In fact, is it possible to only change it in this `log.rs` fn and `use` that here? Haven't tested myself but if it is possible we could avoid duplication of the fn here.

2023-04-18 05:01 UTC, inashivb commented
> > Could you please add the source of test data to every test?
> 
> Is this style suitable? @inashivb
> 
> https://github.com/OISF/suricata/blob/af55721842d20f1d3ae70aef6144428cf7cda709/rust/src/smb/smb2_records.rs#L686-L689

This looks fine to me as it is informative enough. But, you'll hear from others if they have a different opinion.
Thank you for your continued interest and work! :)

2023-05-05 15:10 UTC, victorjulien commented
Merged in #8815, thanks!

Did some clippy fixes and reformatting on top of this.

2023-05-05 15:10 UTC, closed without merging