smb: fix SMB_COM_WRITE_ANDX record parser - v2
OISF/suricata pull request #8845
Opened 2023-05-09 14:20 UTC by b1tg

Bug:  https://redmine.openinfosecfoundation.org/issues/6008

Previous PR: https://github.com/OISF/suricata/pull/8839

Changes from last PR:
- remove TODO & add comments

SV_BRANCH=pr/1195

2023-05-09 14:26 UTC, b1tg commented
If packet has a invalid data_pad_offset, should we return an error or just let it be zero?

2023-05-10 03:38 UTC, b1tg commented
> If packet has a invalid data_pad_offset, should we return an error or just let it be zero?

"return an error" version look like below:
```rust
    let mut data_pad_offset = data_offset.checked_sub(ax+28).ok_or(Err::Error(make_error(i, ErrorKind::LengthValue)))?;
    if high_offset.is_some() {
        data_pad_offset = data_pad_offset.checked_sub(4).ok_or(Err::Error(make_error(i, ErrorKind::LengthValue)))?;
    }
```

2023-05-12 07:36 UTC, catenacyber commented
Do you know why there is one CI failure ?

> If packet has a invalid data_pad_offset, should we return an error or just let it be zero?

What would Windows do ?

2023-05-13 13:31 UTC, b1tg commented
> Do you know why there is one CI failure ?

I could not reproduce this failure, and only Fedora 36 failed is strange.

> What would Windows do ?

I create a packet by use smbclient.py send a file from Linux to Win10 which have a shared folder

write_andx_request in origin packet have data_offset=0x3f

As a Rust test it looks like :

```rust
    let mut data = hex::decode("0eff000000054000000000ff00000008001400000014003f00000000001400414141414141414141414141414141414141410a").unwrap();
    let result = parse_smb1_write_andx_request_record(&data, SMB1_HEADER_SIZE);
    assert!(result.is_ok());
    let record = result.unwrap().1;
    assert_eq!(record.offset, 0);
    assert_eq!(record.len, 20);
    assert_eq!(record.fid, &[0x05, 0x40]);
    assert_eq!(record.data.len(), 20);
    assert_eq!(record.data, b"AAAAAAAAAAAAAAAAAAA\n");
```

then I use a proxy to modify data_offset  in write_andx_request before send to server:

1. change data_offset to 0x3e, 0x3d, 0x3c: Windows 10 write 20 bytes (include metadata before real data in packet)
2. change data_offset to <= 0x3b: Windows 10 return Server Error(Non specific error code)
3. change data_offset to [0x40, 0x53]: Windows 10 write [19, 0] bytes
4. change data_offset to 0x54: Windows 10 return Server Error(Non specific error code)


and there is no one byte padding in the origin packet which is a little surprise as spec [MS-CIFS].pdf says always take one byte padding

2023-05-13 13:36 UTC, victorjulien commented
Restarted the CI job to make sure it's not a random failure.

2023-05-14 14:01 UTC, catenacyber commented
Nice @b1tg do you have a pcap of this ?

So, I think you should return an error, but make sure that this does not prevent further parsing of SMB PDUs

Why is this PR a draft ? What are you expecting from us ?

2023-05-15 11:33 UTC, b1tg commented
> Why is this PR a draft ? What are you expecting from us ?

victorjulien marked this pull request as draft

> do you have a pcap of this ?

Added to https://redmine.openinfosecfoundation.org/issues/6008

2023-05-15 16:04 UTC, catenacyber requested changes
Here is my feedback :
CI : green :-)
Code : reviewing it right now
Commits segmentation : I think the 2 commits should be squashed together
Commit messages : ok
Git ID set : looks fine for me
CLA : did you sign it ?
Doc update : not needed
Redmine ticket : ok
Rustfmt : ok, file not yet formatted
Tests : Would you be able to address the remarks in the suricata-verify PR ? (avoid the shell checks and have just json checks)
Dependencies added: none

2023-05-15 16:06 UTC, catenacyber commented on rust/src/smb/smb1_records.rs
> +        data_pad_offset = data_pad_offset.saturating_sub(4);
I wonder if we can be more direct by using `wct` as was done before (`ax+4+2*(wct as u16)`)

2023-05-15 16:08 UTC, catenacyber commented on rust/src/smb/smb1_records.rs
> +fn test_parse_smb1_write_andx_request_record() {
Maybe the S-V test is enough...
This blob looks too big

2023-05-16 12:16 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/8889

2023-05-16 12:16 UTC, closed without merging