doc: GitHub PRs workflow
OISF/suricata pull request #8926
Opened 2023-05-25 15:07 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
None

Describe changes:
- adds a documentation about GitHub PRs workflow

Draft : to be discussed, and to see if the approved filter with `gh` command is good enough ?

Modifies https://github.com/OISF/suricata/pull/8925 by taking review into account

2023-05-25 16:39 UTC, jufajardini requested changes
Ok, I ran one last picky review, and submitted everything as suggestions, so, if you want, we can try to commit these and see if this version can be merged (IMO).

2023-05-25 16:39 UTC, jufajardini commented on doc/userguide/devguide/codebase/contributing/github-pr-workflow.rst
> +   (and eventually request changes if CI finds anything)
```suggestion
    (and eventually request changes if CI finds anything)
```

2023-05-25 16:39 UTC, jufajardini commented on doc/userguide/devguide/codebase/contributing/github-pr-workflow.rst
> +   (and eventually request changes if CI finds anything)
sorry about that :x

2023-05-25 16:39 UTC, jufajardini commented on doc/userguide/devguide/codebase/contributing/github-pr-workflow.rst
> +The author of the PR should explicit what kind of feedback is expected (CI/QA run, discussion on the code, etc...)
```suggestion
The author of the PR should explicit what kind of feedback is expected (CI/QA
run, discussion on the code, etc...)
```

2023-05-25 16:39 UTC, jufajardini commented on doc/userguide/devguide/codebase/contributing/github-pr-workflow.rst
> +It is expected that the author creates a new PR with a new version of the patch as described in :ref:`Pull Requests Criteria <pull-requests-criteria>`.
```suggestion
It is expected that the author creates a new PR with a new version of the patch
as described in :ref:`Pull Requests Criteria <pull-requests-criteria>`.
```

2023-05-25 16:39 UTC, jufajardini commented on doc/userguide/devguide/codebase/contributing/github-pr-workflow.rst
> +Once in approved state, the PRs are in the responsibility of the merger, along with the next branches/PRs.
```suggestion
Once in approved state, the PRs are in the responsibility of the merger, along
with the next branches/PRs.
```

2023-05-25 16:39 UTC, jufajardini commented on doc/userguide/devguide/codebase/contributing/github-pr-workflow.rst
> +GitHub filter for changes-requested PRs is ``is:pr is:open draft:false sort:updated-asc review:changes-requested``
```suggestion
GitHub filter for changes-requested PRs is ``is:pr is:open draft:false sort:
updated-asc review:changes-requested``
```

2023-05-25 16:39 UTC, jufajardini commented on doc/userguide/devguide/codebase/contributing/github-pr-workflow.rst
> +either changes requested, approved, or assigned to someone else if more expertise is needed.
```suggestion
either changes requested, approved, or assigned to someone else if more
expertise is needed.
```

2023-05-25 16:39 UTC, jufajardini commented on doc/userguide/devguide/codebase/contributing/github-pr-workflow.rst
> +GitHub filter for approved PRs that should go in a next branch is ``is:pr is:open draft:false sort:updated-asc review:approved``
```suggestion
GitHub filter for approved PRs that should go in a next branch is ``is:pr is:open
draft:false sort:updated-asc review:approved``
```

2023-05-31 15:44 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/8946

2023-05-31 15:44 UTC, closed without merging