userguide: add quick eve doc; eve reference - v2
OISF/suricata pull request #8971
Opened 2023-06-05 20:06 UTC by jasonish

Previous PR: https://github.com/OISF/suricata/pull/8933

Changes from last PR:
- a RST section for each object
- "array of" instead of programatic like notation for arrays

Examples:
- QUIC: https://jasonish-suricata.readthedocs.io/en/evedoc-v2/output/eve/eve-json-format.html?highlight=quic#output-reference
- Pgsql: https://jasonish-suricata.readthedocs.io/en/evedoc-v2/output/eve/eve-json-format.html?highlight=quic#field-reference
- EVE Reference: https://jasonish-suricata.readthedocs.io/en/evedoc-v2/appendix/eve-index.html

2023-06-06 17:02 UTC, jufajardini approved these changes

2023-06-26 10:36 UTC, victorjulien commented
Setting to draft due to messy PR history.

2023-06-28 13:31 UTC, victorjulien commented
@catenacyber can you do a (new) PR with just the schema update? I'd like to discuss that separately.

2023-06-28 13:32 UTC, victorjulien requested changes
Needs a clean PR. Also, I think the included schema doc for tls needs discussion.

2023-06-28 15:16 UTC, catenacyber commented
> catenacyber can you do a (new) PR with just the schema update? I'd like to discuss that separately.

https://github.com/OISF/suricata/pull/9091

2023-07-06 17:54 UTC, jasonish commented
Cleaned up here: https://github.com/OISF/suricata/pull/9165

2023-07-06 17:54 UTC, closed without merging