fixed: flow keyword established and not_established
OISF/suricata pull request #9068
Opened 2023-06-23 08:34 UTC by open-cmi

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ ] I have read the contributing guide lines at https://suricata.readthedocs.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [ ] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
-
-
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the pull request number.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-06-23 08:43 UTC, inashivb requested changes
Hi! Thanks for your first contribution to our project. :)
1. Could you please fix your commit message to something like
`detect/flow: fix DETECT_FLOW_FLAG_ESTABLISHED check`
or whatever you feel makes sense but the prefix should indicate the part of code being changed.
2. Also, please make sure to sign the contribution agreement for your work to be accepted.

2023-06-23 22:23 UTC, open-cmi commented
> Hi! Thanks for your first contribution to our project. :)
> 
> 1. Could you please fix your commit message to something like
>    `detect/flow: fix DETECT_FLOW_FLAG_ESTABLISHED check`
>    or whatever you feel makes sense but the prefix should indicate the part of code being changed.
> 2. Also, please make sure to sign the contribution agreement for your work to be accepted.
> 3. Your name in commit sign should be `First-name Last-name`

OK, I had modified the commit message

2023-06-26 18:03 UTC, victorjulien commented
It would be great if you'd also create some Suricata-Verify tests to show the issue, so that we can continue to test for it in the future.

2023-06-27 07:42 UTC, open-cmi commented
> It would be great if you'd also create some Suricata-Verify tests to show the issue, so that we can continue to test for it in the future.

OK, I add a unit test for test setting establish and not_establish both.

2023-06-27 11:11 UTC, victorjulien commented
> > It would be great if you'd also create some Suricata-Verify tests to show the issue, so that we can continue to test for it in the future.
> 
> I added an unit test for test setting establish and not_establish both. This is my first time to write an unit test, is it what you want?

I think the UT is useful, and can stay as part of the PR, but I meant Suricata-Verify: https://github.com/OISF/suricata-verify
The benefit of SV is that they are tested against 6.0.x as well and additionally act as "seed" to the fuzzing effort.

2023-06-27 18:34 UTC, victorjulien commented
Additionally, please make sure the formatting check passes.

2023-06-27 22:33 UTC, open-cmi commented
> Additionally, please make sure the formatting check passes.

OK

2023-06-27 22:36 UTC, open-cmi commented
> > > It would be great if you'd also create some Suricata-Verify tests to show the issue, so that we can continue to test for it in the future.
> > 
> > 
> > I added an unit test for test setting establish and not_establish both. This is my first time to write an unit test, is it what you want?
> 
> I think the UT is useful, and can stay as part of the PR, but I meant Suricata-Verify: https://github.com/OISF/suricata-verify The benefit of SV is that they are tested against 6.0.x as well and additionally act as "seed" to the fuzzing effort.

OK, I will learn how to write a SV test. Thanks.

2023-08-30 15:37 UTC, catenacyber commented on src/detect-flow.c
> +    fd = DetectFlowParse(NULL, "established,not_established");
Also `not_established ,established` should have the same error message

2023-11-08 10:51 UTC, closed without merging