af-packet: Remove support for rollover
OISF/suricata pull request #9123
Opened 2023-07-01 13:52 UTC by jlucovsky

Continuation of #9069 
This MR removes support for AF-Packet rollover.

Rollover support is defined [here](https://www.man7.org/linux/man-pages/man7/packet.7.html).

If `cluster-type: cluster_rollover` is configured, a warning message will be displayed and the clustering used will be `cluster_flow`.

The warning message:
```
Warning: af-packet: enp6s0f0: cluster_rollover deprecated; using "cluster_flow" instead. See https://redmine.openinfosecfoundation.org/issues/6128
```
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6128](https://redmine.openinfosecfoundation.org/issues/6128)

Describe changes:
- Document deprecation in upgrade notes
- Detect when rollover is used (`cluster-type: cluster_rollover`) and use `cluster_flow` instead

Updates
- Removed `rollover` handling per review feedback.
- 
### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the pull request number.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-07-01 22:35 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPR1_stats_chk | | |
| .flow.memuse | 592373632 | 520052840 | 87.79% | 

Pipeline 14954

2023-07-04 07:49 UTC, victorjulien requested changes
This still leaves the regular `rollover` option. I think that should just turn into a no-op with a warning.

2023-07-04 07:50 UTC, victorjulien commented on src/runmode-af-packet.c
> +                         "https://redmine.openinfosecfoundation.org/issues/6128",
I think I prefer: "See ticket #6128."

I think we use this ticket notation elsewhere too.

2023-07-04 07:51 UTC, victorjulien commented on suricata.yaml.in
> +    # cluster_rollover has been deprecated; if used, it'll be replaced with cluster_flow.
I read this as "in the future, it will be replaced by ...". Maybe reword a bit... "this now acts as cluster_flow" or something like this?

2023-07-05 13:36 UTC, jlucovsky commented
Continued in #9148

2023-07-05 13:36 UTC, closed without merging