doc: add support status page - v4
OISF/suricata pull request #9177
Opened 2023-07-07 17:51 UTC by jasonish

Previous PR: #9163 

Changes from last PR:
- Incorporate feedback.

Generated at https://jasonish-suricata.readthedocs.io/en/doc-support-status-v4/support-status.html.

2023-07-07 23:28 UTC, jufajardini requested changes
Some final nits :P

2023-07-07 23:28 UTC, jufajardini commented on doc/userguide/support-status.rst
> +Tier 2 supported items are developed and support by the Suricata core
```suggestion
Tier 2 supported items are developed and supported by the Suricata core
```

2023-07-07 23:28 UTC, jufajardini commented on doc/userguide/support-status.rst
> +documented as "known issues" and may go into a release. Tier 1
```suggestion
documented as "known issues" and may go into a release. Tier 2
```

2023-07-07 23:28 UTC, jufajardini commented on doc/userguide/support-status.rst
> +team, sometimes with help from community. Major functional failures
```suggestion
team, sometimes with help from the community. Major functional failures
```

2023-07-07 23:28 UTC, jufajardini commented on doc/userguide/support-status.rst
> +  - support users when they encounter problems on the mailinglists and
```suggestion
  - support users when they encounter problems on the forum and
```

2023-07-07 23:28 UTC, jufajardini commented on doc/userguide/support-status.rst
> +  - support users when they encounter problems on the mailinglists and
Should we add Discord? Sounds too much, considering how volatile messages there can be.

2023-07-07 23:28 UTC, jufajardini commented on doc/userguide/support-status.rst
> +    redmine tickets
nit:
```suggestion
    redmine tickets.
```

2023-07-07 23:28 UTC, jufajardini commented on doc/userguide/support-status.rst
> +* the code may not have CI coverage by the OISF infrastructure
nit:
```suggestion
* the code may not have CI coverage by the OISF infrastructure.
```

2023-07-11 12:47 UTC, victorjulien commented
included in #9209

2023-07-11 12:47 UTC, closed without merging