Doc/severity/v6
OISF/suricata pull request #9209
Opened 2023-07-11 11:41 UTC by victorjulien

2023-07-11 12:46 UTC, victorjulien commented
Includes #9177

2023-07-11 19:10 UTC, catenacyber commented on SECURITY.md
> +These are documented in https://docs.suricata.io/en/latest/support-status.html
This is currently 404

2023-07-11 19:11 UTC, catenacyber commented on SECURITY.md
> +loss of visibility and/or availability. RCE, remotely triggerable traffic
Should we remove RCE if we describe more precisely remotely triggerable traffic based crashes ?

2023-07-11 19:13 UTC, catenacyber commented on SECURITY.md
> +update the vulnerabilities page and note the issue CVE in the changelog
What is the vulnerabilities page ?

2023-07-11 19:19 UTC, catenacyber commented on SECURITY.md
> +Community features, or which are less likely to be exploitable. These issues
For examples, trigger able through rules instead of network traffic.

Other question : What about memory leaks ? 
I understand that every impact is equal : evasion, crash from NULL Deref or use after free, memory leak, quadratic complexity. What matters is the feature where the bug resides. Do,I get it right ?

2023-07-12 13:56 UTC, jufajardini commented on SECURITY.md
> +These are documented in https://docs.suricata.io/en/latest/support-status.html
I think that that's because it's added with this PR.

2023-07-12 16:43 UTC, jufajardini requested changes
To complement Philippe's review, some inline comments.

2023-07-12 16:43 UTC, jufajardini commented on SECURITY.md
> +We assign a severity and will share our assessment with you.
nit:
```suggestion
We will assign a severity and will share our assessment with you.
```

2023-07-12 16:43 UTC, jufajardini commented on SECURITY.md
> +general be fixed immediately in latest development versions, and may be
Could we:
```suggestion
general be fixed as soon as possible in latest development versions, and may be
```

2023-07-12 16:43 UTC, jufajardini commented on SECURITY.md
> +update the vulnerabilities page and note the issue CVE in the changelog
Will there always be a CVE?

2023-07-12 17:37 UTC, victorjulien commented on SECURITY.md
> +loss of visibility and/or availability. RCE, remotely triggerable traffic
I feel it's a separate class of issues that we can mention separately here.

2023-07-12 17:38 UTC, victorjulien commented on SECURITY.md
> +update the vulnerabilities page and note the issue CVE in the changelog
removed this language

2023-07-12 17:41 UTC, victorjulien commented on SECURITY.md
> +Community features, or which are less likely to be exploitable. These issues
Mem leaks eventually would affect availability or visibility (if we don't free up memcap for example).

I think indeed the location of the issue is often the most important, but probably also things like: single packet issue? Complex interaction between evil client and evil server? Etc.

2023-07-12 17:43 UTC, victorjulien commented on SECURITY.md
> +update the vulnerabilities page and note the issue CVE in the changelog
no, update the language a bit

2023-07-12 18:53 UTC, catenacyber commented on SECURITY.md
> +Community features, or which are less likely to be exploitable. These issues
Ok, so risk = impact * probability

Impact is equivalent for most classes of bugs.

And probability = tier of bug's location * complexity for the attacker

2023-07-12 19:23 UTC, victorjulien commented on SECURITY.md
> +loss of visibility and/or availability. RCE, remotely triggerable traffic
not sure, seems more specific than we need to be?

2023-07-12 19:46 UTC, catenacyber commented on SECURITY.md
> +loss of visibility and/or availability. RCE, remotely triggerable traffic
So, I do not understand what is meant here by "RCE".

Is arbitrary file write with datasets rule RCE to you ?

Anyways, I think this deserves something more precise than an acronym (and one that is notoriously vague)

2023-07-13 08:05 UTC, victorjulien commented
replaced by #9225

2023-07-13 08:05 UTC, closed without merging