doc: update file keywords v1
OISF/suricata pull request #9245
Opened 2023-07-17 18:30 UTC by jmtaylor90

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- Update file.magic and file.name keyword information to reflect recent updates
- Update libmagic dependency information and reference
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-07-18 00:51 UTC, jufajardini commented
Related to: https://redmine.openinfosecfoundation.org/issues/6194
but not sure if we need a new ticket for the doc update in this case.

2023-07-18 00:54 UTC, jufajardini reviewed
Looks good to me, but as this may be the solution requested by @catenacyber in https://redmine.openinfosecfoundation.org/issues/437, let's wait for his feedback, too :)

2023-07-18 04:50 UTC, victorjulien commented on doc/userguide/rules/file-keywords.rst
> +**Note** The ``filename`` keyword is still supported but the
this is no longer true:

`filename:"secret";` is now equivalent to `file.name; content:"secret"; nocase;`

Similarly, fileext:
`fileext:pdf;` is equivalent to `file.name; content:".pdf"; nocase; endswith;`. Note the dot that is prepended to `pdf`.

This is handled at parsing, so at runtime this is identical in behavior and performance.

btw we're looking at backporting this optimization to 6: https://redmine.openinfosecfoundation.org/issues/6203

2023-07-18 04:52 UTC, victorjulien commented on doc/userguide/rules/file-keywords.rst
> +  file.magic:<string>;
This incorrect. `filemagic` is the legacy notation, that uses:
`filemagic:"Windows"`;
`file.magic` is the new implementation:
`file.magic; content:"Windows"; nocase;`

Note that like with `filename` above, the difference exists only during parsing in 7.

2023-07-18 04:53 UTC, victorjulien commented on doc/userguide/rules/file-keywords.rst
> +**Note** The ``filemagic`` keyword is still supported but the
perf should now be identical

2023-07-18 04:53 UTC, victorjulien requested changes
see inline comments

2023-08-01 15:51 UTC, jmtaylor90 commented
continued in #9316

2023-08-01 15:51 UTC, closed without merging