rust/sip: register parser for tcp v5
OISF/suricata pull request #9321
Opened 2023-08-01 20:01 UTC by glongo

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3351

Previous PR: #8897 

Describe changes:
- Commit splitted and comments in previous pr addressed.

suricata-verify-pr: 1341

2023-08-08 19:08 UTC, jufajardini commented
editted PR description to use new SV PR picking style, as I wasn't sure the old style still works. Re-triggered build tests, too.

2023-08-08 19:18 UTC, jasonish commented
> suricata-verify-pr: 1341

Yeah, that style doesn't work anymore.

2023-08-14 17:38 UTC, jasonish commented on suricata.yaml.in
> +    SIP_PORTS: "[5060, 5061]"
Empty line is lost here, can you please add back.

2023-08-14 17:43 UTC, jasonish commented on rust/src/sip/sip.rs
> +) -> AppProto {
This isn't our formatting for new rust code.  Would you be willing to `rustfmt` the whole SIP module, commit, then apply your changes letting rustfmt do its thing?  I think the module is small enough to do a one-shot rustfmt on it, then apply your changes.

2023-08-14 17:45 UTC, jasonish requested changes
Thanks for the pull request @glongo. Could you please address a few minor things:
- rebase
- formatting

The S-V test appears to be a crafted pcap right?  Once rebased, I can test on some live TCP SIP traffic.

2023-08-14 18:32 UTC, glongo commented on rust/src/sip/sip.rs
> +        }
If `sip_parse_request` is succeeded, `sip_take_line` shouldn't fail because the whole request is parsed before.

2023-08-15 07:35 UTC, glongo commented
Replaced by https://github.com/OISF/suricata/pull/9386

2023-08-15 07:35 UTC, closed without merging