rule-reload: Release excess memory freed during engine reload
OISF/suricata pull request #9356
Opened 2023-08-08 04:00 UTC by thomasjwinter

The hot reload results in large chunks of memory being freed as the as the old signature tables are discarded. Help the memory management system along by telling to release as much memory as it can at this point.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Describe changes:
- We had issue on an embedded device of low memory on rule-reload.
- We found that while the memory has been freed, the kernel needs a kick to properly report this.
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-08-08 07:54 UTC, victorjulien commented
Looks like the last push to the Suricata-Verify repo causes some issues here. Can you rebase this PR?

2023-08-09 05:26 UTC, victorjulien requested changes
Would also like to see some discussion of this mechanic: are there draw backs? Does it cause some performance impact?

2023-08-09 05:26 UTC, victorjulien commented on src/detect-engine.c
> +#include <malloc.h>
this will need to be included in suricata-common.h, with a check in configure.ac to see if it is available

2023-08-09 05:26 UTC, victorjulien commented on src/detect-engine.c
> +    malloc_trim(0);
we need a macro wrapper based on availability, it should live in util-mem.h

Man page says "This function is a GNU extension.", so we can't just assume that it is available as CI failures show.

2023-08-10 03:46 UTC, thomasjwinter commented
> Would also like to see some discussion of this mechanic: are there draw backs? Does it cause some performance impact?

I found this page which discusses malloc_trim and what it does which is a general Linux/glibc memory issue https://github.com/mruby/mruby/pull/5069
That page links to the following stackoverflow pages which also discuss it https://stackoverflow.com/questions/27945855/force-free-to-return-malloc-memory-back-to-os/47061458#47061458 and https://stackoverflow.com/questions/2215259/will-malloc-implementations-return-free-ed-memory-back-to-the-system/3860495#3860495

For our case, we were running on a system that produces a debug snapshots when memory is low and may reboot recover. We found that suricata appeared to use more memory than expected on rule reload but the memory was actually freed but needed the malloc_trim call to tell the kernel actually re-use it.

As for performance impact, my understanding is the kernel will do a little extra work to free the pages on the malloc_trim call then a little extra work to give a free page to suricata on the next malloc if needed. It shouldn't be a noticeable impact at all especially since rule reload doesn't happen very often compared to malloc/free calls.

2023-11-08 10:36 UTC, catenacyber commented
@thomasjwinter are you planning to work on this again ?

2023-11-08 23:36 UTC, closed without merging

2023-11-08 23:36 UTC, thomasjwinter commented
I created redmine ticket https://redmine.openinfosecfoundation.org/issues/6454 and created new pull request https://github.com/OISF/suricata/pull/9756