Fix parsing ip-reputation data with carriage return
OISF/suricata pull request #9357
Opened 2023-08-08 04:23 UTC by thomasjwinter

Commit e7c0f0ad91fd removed uses of atoi with a new number parsing functions. This broke parsing ip-reputation data files that contained trailing carriage returns as it was being included in the number string to convert.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [X] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [X] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6243

Describe changes:
-
-
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-08-08 19:00 UTC, jufajardini requested changes
Hi Thomas, thanks for your fix to this! I see that the SV test created to showcase the issue passes with this PR, so I just want to point out some nit-adjustments :P

- Could you add the ticket number to your commit message? https://github.com/OISF/suricata/commit/2786ccb086d7f8c42f39d0ef048631c9c8ce66c7 exemplifies how.
- similarly, to comply with our commit styles, can you adjust the commit title to be something like:

`iprep: fix parsing ip-rep data with carriage return`

This adds the module you've worked on but still keeps message within characters limits :P

2023-08-10 00:47 UTC, thomasjwinter commented
The suricata-verifry failures look to be caused by the "tests: files update for nocase fix" commit and not related to these changes.

2023-08-14 22:16 UTC, jufajardini approved these changes

2023-08-30 08:10 UTC, catenacyber commented
Thank you Thomas for your contribution.
Could you open a new PR that is rebased so that CI looks green ?

2023-08-30 08:29 UTC, catenacyber requested changes
Looks good, but needs to be rebased in a new PR to get CI green

2023-08-31 23:29 UTC, thomasjwinter commented
replaced by https://github.com/OISF/suricata/pull/9426

2023-08-31 23:29 UTC, closed without merging