flow: optionally use pkt recursion for hash
OISF/suricata pull request #9363
Opened 2023-08-08 22:04 UTC by coledishington

Optionally use pkt recursion level in flow hash. Excluding recursion level in flow hash allows matching of packet flows on a tunnel terminator and a packet pickup like netmap pipes.

Bug: #6260

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [✓] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [✓] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [✓] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6260

Describe changes:
Add config (recursion-level.use-for-tracking) to control the use of packet recursion level in flow matching. This is to support scenarios using packet pickup that get egress packets destined for a tunnel, terminated on the Suricata running device, before the kernel has added the tunnel headers.

https://github.com/OISF/suricata-verify/pull/1348
```
SV_BRANCH=pr/1348
```

2023-08-09 06:33 UTC, victorjulien commented
Can you explain the use case in a bit more detail? I'm not sure I understand it.

I'm not sold on the config option using `recursion-level` btw, it feels like it's spilling some internal naming out into a user visible option. Not sure where it would fit otherwise though, perhaps under the `decoder` namespace, as this is where some of the tunnel protocols have their configs.

Btw commit talks only about flow, but code is also about defrag. Please update that, or split the commit into a flow and a defrag specific patch.

2023-08-09 18:47 UTC, jufajardini commented
Clang failure must also be addressed :)
https://github.com/OISF/suricata/actions/runs/5802382519/job/15728665872?pr=9363#step:14:23

2023-08-23 13:56 UTC, jlucovsky commented on src/suricata.c
> +        /* Ignore livedev id when comparing flows. */
nit: should reference "recursion level" instead of "livedev id"

2023-08-30 11:34 UTC, catenacyber requested changes
There are some comments to take into account and formatting to fix

2023-08-31 03:28 UTC, coledishington commented
Thanks for all the comments. I have submitted a new PR with the requested changes and further description of the issue. The PR is https://github.com/OISF/suricata-verify/pull/1368

2023-08-31 07:58 UTC, catenacyber commented
Replaced by #9423 right ?

2023-08-31 07:58 UTC, closed without merging