rust/sip: register parser for tcp v6
OISF/suricata pull request #9387
Opened 2023-08-15 08:55 UTC by glongo

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3351

Describe changes:
- rebase
- formatting

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1341

2023-08-25 18:42 UTC, jasonish commented on rust/src/sip/sip.rs
>          SCLogDebug!("Protocol detecter and parser disabled for SIP/UDP.");
The only thing I'd change now I think is this line and the one further below.

```
Protocol detection and parsing disabled for UDP SIP
```
and likewise for the TCP.  Or just bring correct spelling to both. Easy to do with in a staging commit though.

2023-08-25 18:44 UTC, jasonish approved these changes
I think this is OK.  I'm not sure if its suitable for 7.0.x as it is much like adding a new parser, but it is a reasonable enhancement to 7.0 as well.  Will need to be discussed.

2023-08-30 08:23 UTC, catenacyber commented
Why is the CI red ?

2023-08-30 08:40 UTC, catenacyber commented
> Why is the CI red ?

Maybe you need to rebase the S-V PR ?..

2023-08-30 08:48 UTC, catenacyber commented on rust/src/sip/sip.rs
> +            return AppLayerResult::err();
How can we end up here ?

2023-08-30 08:51 UTC, catenacyber commented
Commit `rust/sip: register parser for sip` should reference the redmine ticket number in its message

2023-08-30 08:52 UTC, catenacyber commented
I think commit `[eve/schema: add sip_tcp](https://github.com/OISF/suricata/pull/9387/commits/50b5d79a8a933f8ae7c800b241caeac4275d85bf)` should be squashed into `[rust/sip: register parser for sip](https://github.com/OISF/suricata/pull/9387/commits/5e1622835bd9c856fd7eee456f9ba68eb1913361)`

2023-08-30 08:54 UTC, catenacyber commented on suricata.yaml.in
> +    SIP_PORTS: "[5060, 5061]"
This is meant to be used in signatures, right ?

2023-08-30 08:59 UTC, catenacyber requested changes
Thanks again, looking good.

Here is my quick feedback :
CI : can you make it green  ? (rebasing the S-V PR I guess)
Code : looks good
Commits segmentation : I think some commits can be squashed together
Commit messages :Could you put the redmine ticket reference in the main commit ?
Git ID set : looks fine for me
CLA : I do not have access, but you have already contributed
Doc update : Where should we document this change @jufajardini ? upgrade section ?
Redmine ticket : ok
Rustfmt : thanks 🙇 
Tests : Looks noce, will comment on it
Dependencies added: none

2023-09-13 14:55 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/9483 right ?

2023-09-13 14:55 UTC, closed without merging