community-id: Fix IPv6 address sorting not respecting byte order
OISF/suricata pull request #9399
Opened 2023-08-20 15:57 UTC by awelzel

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ ] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [ ] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6276

Describe changes:
When comparing IPv6 addresses based on uint32_t chunks, one needs to apply ntohl() conversion to the individual parts, otherwise on little endian systems individual bytes are compared in the wrong order. Avoid this all and leverage memcmp(), it'll short circuit on the first differing byte and its return values tells us which address sorts lower.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-08-23 22:02 UTC, jasonish commented
Suricata-Verify tests added here: https://github.com/OISF/suricata-verify/pull/1360

Re-running CI to pick up SV PR.

2023-08-30 11:13 UTC, catenacyber requested changes
Thanks for this fix

Could you just reword the commit to include the redmine ticket reference ?
cf https://docs.suricata.io/en/latest/devguide/codebase/contributing/code-submission-process.html#commits

Here is my feedback :
CI : green
Code : looks good (negative number of lines :-) )
Commits segmentation : ok
Commit messages : Could you put the redmine ticket reference in the commit ?
Git ID set : looks fine for me
CLA : I do not have access, but you say to have signed it
Doc update : not needed
Redmine ticket : ok
Rustfmt : no rust
Tests : S-V looks ok
Dependencies added: none

2023-08-30 18:24 UTC, jasonish commented
> Commit messages : Could you put the redmine ticket reference in the commit ?

Already did in a staging branch.

2023-09-06 09:41 UTC, catenacyber commented
Done in https://github.com/OISF/suricata/pull/9442

2023-09-06 09:41 UTC, closed without merging