Batch backports to 6.0.x
OISF/suricata pull request #9445
Opened 2023-09-06 13:43 UTC by jlucovsky

Continuation of #9413 

Batch backports to 6.0.x

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) tickets:
- [6045](https://redmine.openinfosecfoundation.org/issues/6045)
- [6248](https://redmine.openinfosecfoundation.org/issues/6248)
- [6213](https://redmine.openinfosecfoundation.org/issues/6213)
- [6227](https://redmine.openinfosecfoundation.org/issues/6227)

Describe changes:
-
-
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-09-06 16:50 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 15847

2023-09-07 07:25 UTC, victorjulien approved these changes

2023-09-07 12:37 UTC, victorjulien requested changes
fixes needed, doing them myself

2023-09-07 12:37 UTC, victorjulien commented on src/suricata.c
> +    fp = fopen(filename, "r");
bad merge, as fopen is already done below. Have a fix

2023-09-07 12:41 UTC, victorjulien commented
replaced by #9457

2023-09-07 12:41 UTC, closed without merging