backport: doc: update install instructions
OISF/suricata pull request #9467
Opened 2023-09-08 11:06 UTC by lukashino

Follow-up of #9390 
Cherry-pick of: 5a3ecbde62c83c216caab52f53c1f7692091e045

Make sure these boxes are signed before submitting your Pull Request -- thank you.

 I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
 I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
 I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)
Link to [redmine](https://redmine.openinfosecfoundation.org/issues/5988) ticket:

Describe changes:
- update dependencies so they are more up-to-date

2023-09-11 09:02 UTC, victorjulien requested changes

2023-09-11 09:02 UTC, victorjulien commented on doc/userguide/install.rst
> +  libjansson, libpcap, libpcre(libpcre3), libyaml, zlib
libpcre3 has not meaning outside of debian/ubuntu, so should not be mentioned here

2023-09-11 09:02 UTC, victorjulien commented on doc/userguide/install.rst
> +                    gosu jq libbpf-dev libcap-ng0 libcap-ng-dev libelf-dev \
why is `gosu` here?

2023-09-15 16:03 UTC, lukashino reviewed
Follow-up in #9491

2023-09-15 16:03 UTC, closed without merging