napatech: emit HBA deprecation only once
OISF/suricata pull request #9478
Opened 2023-09-12 19:07 UTC by perkinjo

Issue: 6313
This commit removes duplicate HBA deprecation messages from being emitted.

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6313

Describe changes:
- This commit removes duplicate HBA deprecation messages from being emitted.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-09-13 11:57 UTC, jlucovsky commented
@ralpheastwood Is the HBA setting going to be deprecated?

2023-09-13 12:32 UTC, ralpheastwood commented
It looks like we have a typo in the warning message, it should be "Host Buffer Allowance", instead of "Host Buffer Allocation".   But yes, we will be deprecating this setting.

2023-09-14 16:40 UTC, jlucovsky commented
> It looks like we have a typo in the warning message, it should be "Host Buffer Allowance", instead of "Host Buffer Allocation". But yes, we will be deprecating this setting.

When do you anticipate the deprecation will occur and with what API version of the NT software will that be in?

2023-09-18 12:49 UTC, ralpheastwood commented
I'll send in a pull request to remove the setting (in the next few days).  The API won't be removed from our software for compatibility with our older hardware (and for other software that uses our hardware) but we don't support its use for current hardware through Suricata.

2023-09-18 18:03 UTC, jlucovsky commented
> I'll send in a pull request to remove the setting (in the next few days). The API won't be removed from our software for compatibility with our older hardware (and for other software that uses our hardware) but we don't support its use for current hardware through Suricata.

This means the HBA is already removed? Is there a follow-on mechanism that provides similar or extended functionality?

2023-09-19 07:57 UTC, ralpheastwood commented
It hasn't been removed, and the functionality will remain for some extant customer-specific applications.  We do not have a timeline for the exact removal (or if it will be removed) but it is a feature that is not actively developed currently, and we no longer support its use with Suricata.  There is no new feature with similar or replacement functionality currently.

2023-09-28 17:26 UTC, ralpheastwood commented
I haven't had a chance yet, but I'll submit one next week with the changes.

2023-10-13 17:55 UTC, jlucovsky commented
This PR can be closed as #9559 removes HBA related code, including the deprecation message.

2023-10-30 18:12 UTC, jlucovsky commented
> This PR can be closed as #9559 removes HBA related code, including the deprecation message.

Reverse on that -- #9559 is appropriate for Suri 8; this PR addresses the immediate issue (multiple log messages).

2023-10-31 11:40 UTC, victorjulien commented
Is the message itself still accurate? It states that something "will be deprecated" in 7.0. We're already in 7, so should it be 8?

2023-10-31 11:45 UTC, ralpheastwood commented
I don't think the message itself is accurate because the window for 7 was missed.

2023-10-31 12:39 UTC, jlucovsky commented
> I don't think the message itself is accurate because the window for 7 was missed.

So we
- Change the message to "Host Buffer Allowance"
- Change the deprecated version from `v7.0` to `v8.0`

Thoughts?

2023-10-31 12:42 UTC, ralpheastwood commented
That sounds good -  and then the removal PR will be merged for v8.0 after this?

2023-12-21 20:09 UTC, catenacyber requested changes
Needs a rebase (and what Jeff said)

2024-03-13 19:49 UTC, perkinjo commented
Sorry that I missed the request back in December.   I'm working on the rebase now.  However it looks like the relevant code was already removed from master.

Is it correct that this PR should now target main-7.0.x instead of master?

2024-03-14 13:02 UTC, jlucovsky commented
Continued in #10644

2024-03-14 13:02 UTC, closed without merging