output/alert: rewrite code for app-layer properties
OISF/suricata pull request #9511
Opened 2023-09-22 07:37 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3827
preliminary work for https://redmine.openinfosecfoundation.org/issues/5053 and app-layer plugins
preliminary work for https://redmine.openinfosecfoundation.org/issues/5977 as well
Part of https://github.com/OISF/suricata/pull/8961

Describe changes:
- Fix setup-app-layer script so that it adds app-layer metadata to alerts

After that, there is still from https://github.com/OISF/suricata/pull/8961
- addition of protocols missing alert metadata (like krb5) + behavioral change for dns alert metadata 
- reusing these `SimpleTxLogFunc` from a JsonGenericLogger to remove many C files

#9252 with some renaming as per code review + reusing code for output-json-file.c

Same as #9499 but without the force-push on github

2023-10-20 08:05 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16262

2023-10-26 19:32 UTC, jasonish requested changes
I want to see this land as soon as possible, but I also want the commit message to explain a little bit more about whats going on.  The ticket referenced may be related, but this is more about the actual logging, then the initialization of logging.

2023-10-28 06:00 UTC, victorjulien commented
Still not really a fan of introducing a new global hard coded table. But I guess if this is a step towards making things more dynamic I can live with it.

2023-10-28 21:56 UTC, jasonish commented
> Still not really a fan of introducing a new global hard coded table. But I guess if this is a step towards making things more dynamic I can live with it.

Yeah, me to.  I think without this step, future steps will just take longer to complete tho.

2023-11-10 08:17 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/9768

2023-11-10 08:17 UTC, closed without merging