rust: update broti decompressor crate
OISF/suricata pull request #9540
Opened 2023-10-03 09:20 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59687

Describe changes:
- rust: update broti decompressor crate patch version

@jasonish did I get it right ?
I ran `cargo update -p brotli-decompressor` and moved the changes to Cargo.lock.in

2023-10-03 11:40 UTC, catenacyber commented
Part of https://redmine.openinfosecfoundation.org/issues/5994

2023-10-03 18:27 UTC, jasonish commented
Looks right for a transitive dependency.

2023-10-04 07:16 UTC, victorjulien commented
> Looks right for a transitive dependency.

Please hit approve if you, well, approve :)

2023-10-04 19:40 UTC, jasonish approved these changes

2023-10-05 04:27 UTC, victorjulien approved these changes

2023-10-06 15:16 UTC, victorjulien requested changes
Typo in commit title broti should be brotli

2023-10-06 15:44 UTC, catenacyber commented
> Typo in commit title broti should be brotli

Nice, I had to read twice your comment to see the diff

https://github.com/OISF/suricata/pull/9571

2023-10-06 15:44 UTC, closed without merging