Doc: Updating the installation guide in the user guide to include instructions for the 'install-full' and 'install-conf' options. issue #6342
OISF/suricata pull request #9581
Opened 2023-10-08 23:13 UTC by comfort619

- [x] I have read the contributing guide lines at https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata.io/about/contribution-agreement/
- [x] I have updated the user guide (in doc/userguide/install.rst) to reflect the changes made 

Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6342) ticket:

Describe changes:

- Added instructions for the 'install-full' option to the installation guide.
- Included guidance on using the 'install-conf' option for better configuration.
- Ensured that these instructions are presented clearly in the appropriate sections of the guide.
- Checked and maintained consistent formatting throughout the document.

**Testing Done:**

I've tested these changes locally to ensure that the installation guide is accurate and easy to follow.

**Related Issues:**

Closes #6342

**Additional Notes:**

- This PR includes updates to the user guide for improved clarity.
- It follows the project's coding and documentation standards.

I look forward to your feedback and appreciate your review of these changes.

2023-10-09 01:56 UTC, inashivb commented on doc/userguide/install.rst
> +Auto-Setup
I think this should go before the section where distro specific installations start.

2023-10-09 02:02 UTC, inashivb requested changes
Hi @comfort619 !
Kudos on making your first contribution! :)
We need several changes w.r.t. the commits. Please read the contribution guideline: https://docs.suricata.io/en/latest/devguide/codebase/contributing/code-submission-process.html#commits
1. Make commit messages small
2. Keep commit history clear (here 1 commit should suffice)
3. Make sure your author is `FirstName LastName <myemail.example.com>` and it matches your name on the contribution agreement.

2023-10-09 06:54 UTC, comfort619 commented
> Hi @comfort619 ! Kudos on making your first contribution! :) We need several changes w.r.t. the commits. Please read the contribution guideline: https://docs.suricata.io/en/latest/devguide/codebase/contributing/code-submission-process.html#commits
> 
> 1. Make commit messages small
> 2. Keep commit history clear (here 1 commit should suffice)
> 3. Make sure your author is `FirstName LastName <myemail.example.com>` and it matches your name on the contribution agreement.

okay, noted. thanks

2023-10-10 14:20 UTC, jufajardini commented
Hi there @comfort619, thanks for working on the feedback we've given.

We usually incorporate new changes into new PRs, in our contribution process: https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html#feedback

2023-10-10 14:34 UTC, comfort619 commented
> Hi there @comfort619, thanks for working on the feedback we've given.
> 
> We usually incorporate new changes into new PRs, in our contribution process: https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html#feedback
> 
> As the changes here are not code-related, I'm re-running the checks. The points indicated by Shivani seem to have been addressed 🎉 :)

ohh, I missed that of creating a new PR for changes, noted. Thank you for the feedback

2023-10-10 14:46 UTC, jufajardini requested changes
Comparing with the page on https://docs.suricata.io/en/latest/devguide/codebase/installation-from-git.html I've noticed that we were using italics to differentiate the commands we were explaining.
I've indicated two cases, can you double-check what is missing, and update accordingly? :)

2023-10-12 14:33 UTC, closed without merging