userguide: cover install-full and install-conf -v4
OISF/suricata pull request #9607
Opened 2023-10-12 21:32 UTC by comfort619

Ticket: 6342
Link to [redmine](https://redmine.openinfosecfoundation.org/issues/6342) ticket:

Describe changes:
-Incorporate feedback from last PR.
-Previous PR: #9602

2023-10-12 22:06 UTC, jasonish requested changes

2023-10-12 22:06 UTC, jasonish commented on doc/userguide/install.rst
> +    ./configure && make && make install-rules
Should use sudo here as well.

2023-10-12 22:06 UTC, jasonish commented on doc/userguide/install.rst
> +    ./configure && make && make install-full
And here.

2023-10-13 08:20 UTC, comfort619 commented on doc/userguide/install.rst
> +    ./configure && make && make install-full
Okay, noted

2023-10-14 12:30 UTC, closed without merging