detect: SigMatchAppendSMToList can fail
OISF/suricata pull request #9662
Opened 2023-10-19 19:32 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6104

Describe changes:
- fixes buffer overflow in rules parsing
- fixes memory leak in parsing `dcerpc.iface` on OOM condition (if `SigMatchAlloc` returns NULL)

Replaces #9588 with needed rebase

2023-10-20 00:15 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16257

2023-11-18 11:45 UTC, victorjulien approved these changes

2023-11-18 13:11 UTC, victorjulien requested changes
needs an update as it fails to build after rebase

2023-11-19 20:04 UTC, catenacyber commented
> needs an update as it fails to build after rebase

Indeed as new keywords got added, fixing them

2023-11-19 20:17 UTC, closed without merging

2023-11-19 20:17 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/9838