memory/alloc: Use SCCalloc instead of malloc/memset
OISF/suricata pull request #9665
Opened 2023-10-20 13:25 UTC by jlucovsky

Continuation of #9388 

Replace `SCMalloc/memset` with `SCCalloc`

There are many places that use the following pattern:
```
     mem = SCMalloc(sizeof(foo));
     if (mem) {
        memset(&mem, 0, sizeof(foo));
    }
```

These can all be replaced by using `SCCalloc` which returns 0-filled memory.

Describe changes:
- Changed `SCMalloc` followed by `memset` to `SCCalloc` 

Updates:
- Rebase

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-10-20 21:55 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16272

2023-10-23 10:44 UTC, inashivb reviewed
LGTM. :)

2023-11-19 06:03 UTC, victorjulien reviewed
needs a rebase, thanks

2023-11-19 06:04 UTC, victorjulien requested changes
rebase requested

2023-11-20 13:53 UTC, jlucovsky commented
Continued in #9845

2023-11-20 13:53 UTC, closed without merging