detect/analyzer: add more details for tcp_seq - v2
OISF/suricata pull request #9677
Opened 2023-10-22 22:33 UTC by 0xEniola

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/6353

Previous PR: https://github.com/OISF/suricata/pull/9676

Describe changes:
- Modify the commit message subject to comply with project's 50 character limit.

Output:
```
{
    "raw":"alert tcp any any -> any any (msg:\"Testing seq\"; seq:723833; sid:2;)",
    "id":2,
    "gid":1,
    "rev":0,
    "msg":"Testing seq",
    "app_proto":"unknown",
    "requirements":[],
    "type":"pkt",
    "flags": [
        "src_any",
        "dst_any",
        "sp_any",
        "dp_any",
        "need_packet",
        "toserver",
        "toclient"
    ],
    "pkt_engines": [
        {
            "name":"packet",
            "is_mpm":false
        }
    ],
    "frame_engines": [],
    "lists": {
        "packet": {
            "matches": [
                {
                    "name":"tcp.seq",
                    "seq": {
                        "number":723833
                    }
                }
            ]
        }
    }
}
```

```
SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1435
```

2023-10-23 10:55 UTC, inashivb approved these changes
LGTM. Thanks! :)

2023-10-25 17:23 UTC, jasonish approved these changes
An approval for me, but just wanted to drop a note that its a little odd that the name logged is "tcp.seq", but the new object is just "seq".  But we can't use "tcp.seq" as an object name as downstream tools will break.

So as we add more "tcp.XXX" fields, we may want to refactor to group them under another object, but that gets complicated quickly.

2023-10-25 17:28 UTC, 0xEniola commented
> An approval for me, but just wanted to drop a note that its a little odd that the name logged is "tcp.seq", but the new object is just "seq".  But we can't use "tcp.seq" as an object name as downstream tools will break.
> 
> So as we add more "tcp.XXX" fields, we may want to refactor to group them under another object, but that gets complicated quickly.

Actually, the name were met that way in their source file, so I couldn't do anything about that.

But I do understand what you mean.

2023-10-25 17:31 UTC, jasonish commented
> > An approval for me, but just wanted to drop a note that its a little odd that the name logged is "tcp.seq", but the new object is just "seq".  But we can't use "tcp.seq" as an object name as downstream tools will break.
> > So as we add more "tcp.XXX" fields, we may want to refactor to group them under another object, but that gets complicated quickly.
> 
> Actually, the name were met that way in their source file, so I couldn't do anything about that.
> 
> But I do understand what you mean.

Yeah, doing anything more about it becomes a larger refactoring I think outside the scope of this one ticket.

2023-12-05 13:31 UTC, jufajardini commented
Adding the `decision-required` label here so we consider what Jason has mention before deciding if ready to merge or not.

2024-01-18 10:28 UTC, catenacyber requested changes
Needs a rebase

2024-01-30 17:53 UTC, closed without merging