Be more user-friendly with non-existing user v3
OISF/suricata pull request #9690
Opened 2023-10-25 21:09 UTC by lukashino

Follow-up of https://github.com/OISF/suricata/pull/9657

Redmine ticket:

https://redmine.openinfosecfoundation.org/issues/6278

Describe changes:
- edit FatalError message

To use a pull request use a branch name like pr/N where N is the
pull request number.

Alternatively, SV_BRANCH may also be a link to an
OISF/suricata-verify pull-request.

SV_REPO=
SV_BRANCH=pr/1440
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=

2023-10-25 21:22 UTC, jasonish approved these changes

2023-10-26 01:45 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16313

2023-10-27 18:44 UTC, victorjulien commented on src/suricata.c
>          if (SCGetUserID(suri->user_name, suri->group_name,
it looks like SCGetUserID can't return anything else than 0?

2023-10-27 18:44 UTC, victorjulien commented on src/suricata.c
>          if (SCGetGroupID(suri->group_name, &suri->groupid) != 0) {
same here

2023-10-27 18:45 UTC, victorjulien requested changes
looks like we have some dead code

2023-10-31 14:13 UTC, lukashino commented
Dead code removed in https://github.com/OISF/suricata/pull/9722

2023-10-31 14:13 UTC, closed without merging