stats: Log packets/bytes per second in Suricata stats - v2
OISF/suricata pull request #9742
Opened 2023-11-04 16:19 UTC by I3run0

This commit aims to add packets/bytes per second to Suricata's statistics log. To achieve this, a new type of qualifier was created and two new fields were added to the Start Record structure.

Task OISF#6410

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6410](https://redmine.openinfosecfoundation.org/issues/6410)

Suricata-verify tests: https://github.com/OISF/suricata-verify/pull/1453

Describe changes:
- Fix StatsRegisterTmdCounter function description 
- Add tests to Suricata-verify

2023-11-13 11:13 UTC, jufajardini commented
Updated PR description to refer to SV PR in format recognized by our CI checks, and re-triggered CI build runs.

2023-11-13 11:38 UTC, jufajardini requested changes
Hi there, this is a nit review only, as I'll wait for Lukas to follow up on this previous review.

Focusing on the commit message only:
- nit: typo - `StatsRecord` struct, right?
- there's no need to mention "Suricata" in the commit title, as this repo is Suricata's repo. Can you reword it to reduce redundancy, taking that into account? Thanks!

2024-01-27 15:13 UTC, I3run0 commented on src/counters.c
> +                    r->value = (uint64_t)(r->value / stats_tts);
No! I haven't checked it!  

Thank you for the comment I will fix this error!

2024-04-12 12:43 UTC, catenacyber commented
Closing as stale and changes requested

2024-04-12 12:43 UTC, closed without merging