output/eve: reduce fflush call count
OISF/suricata pull request #9832
Opened 2023-11-19 15:26 UTC by jlucovsky

Continuation of #9802

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [3449](https://redmine.openinfosecfoundation.org/issues/3449)

Describe changes:
- Add EVE configuration parameter to control buffering: `buffer-size`. When 0, unbuffered I/O is used; other values are used to set the stdio buffer size. The value is `outputs.eve-log.buffer-size`
- Add Suricata configuration parameter -- `flush-interval` -- to set cadence for Suricata periodically directing detect threads to flush EVE output. To be used in conjunction with `buffer-size`. Set `logging.flush-interval` to the number of seconds Suricata should periodically cause the EVE output to be flushed. The default value is `0` which instructs Suricata to never cause the EVE output to be flushed.
- Add mechanism to periodically send pseudo packets to detect threads as a way to trigger flush. Controlled by `flush-interval`
- Add "log flusher" thread when flushing is configured (`logging.flush-interval` is between 1 and 69).

Updates:
- Added file missing from git
- Modified log-flush thread to sleep in a series of 500ms increments to respond better to shutdown scenarios
- Checked detection context pointers that could possibly become state in flush and packet injection functions.

## `hyperfine` results
## Suricata configurations
### Threaded output *off*
- suricata.yaml (default values)
- suricata-buffer-flush.yaml (flush every 2 seconds with 16kb buffer)
- suricata-buffering.yaml (16kb buffer)
### Threaded output
- suricata.yaml
- suricata-buffer-flush.yaml
- suricata-buffering.yaml

```
Benchmark 1: ./src/suricata -c suricata.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll
  Time (mean ± σ):     430.159 s ±  2.579 s    [User: 1389.172 s, System: 137.102 s]
  Range (min … max):   427.459 s … 432.596 s    3 runs

Benchmark 2: ./src/suricata -c suricata-buffer-flush.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll
  Time (mean ± σ):     414.604 s ±  3.778 s    [User: 1373.623 s, System: 139.130 s]
  Range (min … max):   410.241 s … 416.830 s    3 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Benchmark 3: ./src/suricata -c suricata-buffering.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll
  Time (mean ± σ):     424.695 s ±  2.462 s    [User: 1386.590 s, System: 137.927 s]
  Range (min … max):   423.107 s … 427.531 s    3 runs

Benchmark 4: ./src/suricata -c suricata-threaded.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll
  Time (mean ± σ):     420.957 s ± 10.320 s    [User: 1384.539 s, System: 132.638 s]
  Range (min … max):   409.044 s … 427.189 s    3 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Benchmark 5: ./src/suricata -c suricata-buffer-flush-threaded.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll
  Time (mean ± σ):     406.783 s ±  6.079 s    [User: 1364.763 s, System: 124.324 s]
  Range (min … max):   400.068 s … 411.913 s    3 runs

Benchmark 6: ./src/suricata -c suricata-buffering-threaded.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll
  Time (mean ± σ):     400.678 s ± 36.885 s    [User: 1356.854 s, System: 122.762 s]
  Range (min … max):   358.107 s … 423.124 s    3 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Summary
  './src/suricata -c suricata-buffering-threaded.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll' ran
    1.02 ± 0.09 times faster than './src/suricata -c suricata-buffer-flush-threaded.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll'
    1.03 ± 0.10 times faster than './src/suricata -c suricata-buffer-flush.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll'
    1.05 ± 0.10 times faster than './src/suricata -c suricata-threaded.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll'
    1.06 ± 0.10 times faster than './src/suricata -c suricata-buffering.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll'
    1.07 ± 0.10 times faster than './src/suricata -c suricata.yaml -S ~/suricata.rules -r ~/pcap -l /tmp/ll'
```
### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-11-19 18:00 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16634

2023-12-04 14:47 UTC, victorjulien commented on src/flow-worker.c
> +        OutputLoggerFlush(tv, p, fw->output_thread);
flush_ack could move here to only flag complete after the actual flush, not just after command received

2023-12-04 14:48 UTC, victorjulien commented on src/detect.c
> +    SC_ATOMIC_CAS(&det_ctx->flush_ack, notset, 1);
SC_ATOMIC_SET can be used I think

2023-12-04 14:50 UTC, victorjulien commented on src/log-flush.c
> +static void WorkerFlushLogs(void)
should be disconnected from the detect engine, as it should also work with `--disable-detection`

2023-12-04 14:50 UTC, victorjulien commented on src/log-flush.c
> +     * TODO: needed?
probably not

2024-01-25 12:43 UTC, catenacyber requested changes
Setting GH status to changes requested per Victor's comments and the needed rebase

2024-03-26 15:15 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16634

2024-05-13 14:02 UTC, jlucovsky commented
Continued in #11059

2024-05-13 14:02 UTC, closed without merging