memory/alloc: Use SCCalloc instead of malloc/memset
OISF/suricata pull request #9845
Opened 2023-11-20 13:53 UTC by jlucovsky

Continuation of #9665 

Replace `SCMalloc/memset` with `SCCalloc`

There are many places that use the following pattern:
```
     mem = SCMalloc(sizeof(foo));
     if (mem) {
        memset(&mem, 0, sizeof(foo));
    }
```

These can all be replaced by using `SCCalloc` which returns 0-filled memory.

Describe changes:
- Changed `SCMalloc` followed by `memset` to `SCCalloc` 

Updates:
- Rebase

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-11-20 16:21 UTC, victorjulien approved these changes
I think this looks good. I would like to see `SCCalloc`'s `nmemb` to be used when we alloc arrays. I'm fine with doing that in a follow up PR, but since I've pointed out most (all?) of them, it would be good to do it soonish.

2023-11-20 16:21 UTC, victorjulien commented on src/detect-engine-build.c
> +    de_ctx->sig_array = (Signature **)SCCalloc(1, de_ctx->sig_array_size);
should this be `SCCalloc(de_ctx->sig_array_len, sizeof(Signature *))`?

2023-11-20 16:21 UTC, victorjulien commented on src/util-bloomfilter-counting.c
> +    bf->array = SCCalloc(1, bf->array_size * bf->type);
`SCCalloc(bf->array_size, bf->type)`?

2023-11-20 16:21 UTC, victorjulien commented on src/util-mpm-ac.c
> +    ctx->pid_pat_list = SCCalloc(1, (mpm_ctx->max_pat_id + 1) * sizeof(SCACPatternList));
same

2023-11-20 16:21 UTC, victorjulien commented on src/util-mpm-ac.c
> +    mpm_ctx->init_hash = SCCalloc(1, sizeof(MpmPattern *) * MPM_INIT_HASH_SIZE);
again

2023-11-20 16:21 UTC, victorjulien commented on src/util-mpm-hs.c
> +    cd->ids = SCCalloc(1, pattern_cnt * sizeof(unsigned int));
same

2023-11-20 16:21 UTC, victorjulien commented on src/util-mpm-hs.c
> +    cd->flags = SCCalloc(1, pattern_cnt * sizeof(unsigned int));
and several more in this file

2023-11-20 16:21 UTC, victorjulien commented on src/util-mpm-hs.c
> +    pd->parray = (SCHSPattern **)SCCalloc(1, pd->pattern_cnt * sizeof(SCHSPattern *));
another

2023-11-20 16:21 UTC, victorjulien commented on src/util-profiling-keywords.c
> +    de_ctx->profile_keyword_ctx->data = SCCalloc(1, sizeof(SCProfileKeywordData) * DETECT_TBLSIZE);
more

2023-11-20 16:21 UTC, victorjulien commented on src/util-profiling-keywords.c
> +        de_ctx->profile_keyword_ctx_per_list[i]->data =
more

2023-11-20 16:21 UTC, victorjulien commented on src/util-profiling-rules.c
> +        de_ctx->profile_ctx->data = SCCalloc(1, sizeof(SCProfileData) * de_ctx->profile_ctx->size);
another

2023-11-21 08:25 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16665

2023-11-21 12:44 UTC, victorjulien requested changes
Needs another rebase following recent merges. Can you address the other comments in a new PR as well. Ideally keeping those in separate commit(s), thanks!

2023-11-21 14:20 UTC, closed without merging

2023-11-21 14:20 UTC, jlucovsky commented
Continued in #9857