general/cppcheck: Address cppcheck memory related errors
OISF/suricata pull request #9849
Opened 2023-11-20 14:37 UTC by jlucovsky

Address cppcheck reported memory leak/misuse errors. See the redmine issue for the cppcheck command that uncovered the issues.

Issue: 6527

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [6527](https://redmine.openinfosecfoundation.org/issues/6527)

Describe changes:
-
-
-

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-11-20 16:03 UTC, victorjulien requested changes

2023-11-20 20:15 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16659

2023-11-22 14:41 UTC, jlucovsky commented on src/detect-engine-address.c
> +        BUG_ON(true);
Will modify function signature to return a `bool` and ensure the caller checks the return value.

2023-11-22 14:42 UTC, jlucovsky commented
Continued in #9866

2023-11-22 14:42 UTC, closed without merging