general/cppcheck: Address cppcheck memory related errors
OISF/suricata pull request #9866
Opened 2023-11-22 14:42 UTC by jlucovsky

Continuation of #9849 

Address cppcheck reported memory leak/misuse errors. See the redmine issue for the cppcheck command that uncovered the issues.

Issue: 6527

Make sure these boxes are signed before submitting your Pull Request -- thank you.

- [ ] I have read the contributing guide lines at
   https://docs.suricata.io/en/latest/devguide/codebase/contributing/contribution-process.html
- [ ] I have signed the Open Information Security Foundation contribution agreement at
   https://suricata.io/about/contribution-agreement/ (note: this is only required once)
- [ ] I have updated the user guide (in doc/userguide/) to reflect the changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:

Updates:
- Address review comments; `DetectAddressMapAdd` now returns a `bool` which is checked by the caller.

### Provide values to any of the below to override the defaults.

To use a pull request use a branch name like `pr/N` where `N` is the
pull request number.

Alternatively, `SV_BRANCH` may also be a link to an
OISF/suricata-verify pull-request.

```
SV_REPO=
SV_BRANCH=
SU_REPO=
SU_BRANCH=
LIBHTP_REPO=
LIBHTP_BRANCH=
```

2023-11-22 17:15 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16690

2023-11-23 15:19 UTC, catenacyber commented
Would you split in two commits for the 2 files ?
They look quite independent fixes...

2023-11-25 08:17 UTC, victorjulien requested changes
Agree with Philippe on the commit separation

2023-11-25 08:17 UTC, victorjulien commented on src/detect-engine-address.c
> +        head = NULL;
prefer just `return NULL` here for readability

2023-11-25 08:17 UTC, victorjulien commented on src/util-streaming-buffer.c
> +            if (to_shift != &sb->region) {
could probably merge this check with the `if (to_shift) {` above.

2023-11-25 14:24 UTC, jlucovsky commented
> Agree with Philippe on the commit separation

I'll separate the commits and submit a followup PR.

2023-11-25 14:25 UTC, jlucovsky commented
Continued in #9891

2023-11-25 14:25 UTC, closed without merging