dns: new keywords: dns.answer.name, dns.query.name - v6
OISF/suricata pull request #9920
Opened 2023-11-29 22:15 UTC by jasonish

Previous PR: https://github.com/OISF/suricata/pull/9813
Changes from last PR:
- Remove prototypes that are not needed.

Introduce two new DNS keywords, dns.query.name and dns.answer.name.

Tickets:
- https://redmine.openinfosecfoundation.org/issues/6497
- https://redmine.openinfosecfoundation.org/issues/6496

SV_BRANCH=https://github.com/OISF/suricata-verify/pull/1464

While this introduces 2 new keywords, I'm also trying to create a good example
of a sticky buffer keyword, and then migrate that into the template, so please
consider the full structure of the files implementing the sticky buffers.

I probably should have left out the "cleanups", can do in a subsequent PR.

2023-11-30 02:55 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW2_autofp_stats_chk | | |
| .uptime | 181 | 198 | 109.39% |
| | SURI_TLPR1_stats_chk | | |
| .uptime | 955 | 1028 | 107.64% | 

Pipeline 16796

2023-12-05 15:07 UTC, jasonish commented
Ping @victorjulien, we need a good clean example/template for Outreachy.

2023-12-13 05:44 UTC, victorjulien approved these changes

2023-12-13 05:58 UTC, victorjulien commented
Doesn't compile after rebase.

2023-12-13 05:59 UTC, victorjulien requested changes
Needs to be updated to compile after rebase.

2023-12-13 15:20 UTC, jasonish commented
Fixed: https://github.com/OISF/suricata/pull/10045

2023-12-13 15:20 UTC, closed without merging