devguide: explain rule-container usage and benefits - v1
OISF/suricata pull request #9931
Opened 2023-11-30 16:47 UTC by jufajardini

Have these options documented, so that whoever writes rule-related documentation can easily know what they could use to make the doc look better.

When reviewing a PR from JT, realized that we could be using `container: example-rule`s more. Mentioned it to him, and he and his colleagues seemed to prefer that style (cf https://github.com/OISF/suricata/pull/9912#discussion_r1409900606). So figured its usage should be documented...

Preview: https://suri-rtd-test.readthedocs.io/en/rules-docs-guide-v1/devguide/codebase/contributing/contribution-process.html#rule-examples

cc @jmtaylor90 :)

2023-11-30 22:08 UTC, jmtaylor90 commented
This is great, thank you for putting this together!

2023-11-30 23:26 UTC, jufajardini commented
> This is great, thank you for putting this together!

🙇🏽 

I hope this helps us get better rule documentation for you all! :)

2023-11-30 23:27 UTC, jufajardini reviewed
Update commit message, as the container is called example-rule, not rule-container.

2023-12-01 20:26 UTC, jasonish commented on doc/userguide/devguide/codebase/contributing/contribution-process.rst
> +
Extraneous space?

2023-12-01 20:27 UTC, jasonish requested changes
This is great. Just a few nits I think.

2023-12-01 21:13 UTC, closed without merging