Detect dns opcode range 5446 v3
OISF/suricata pull request #9945
Opened 2023-12-01 21:22 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/5446

Describe changes:
- make keyword dns.opcode use helper for integers so that they can have all features such as range
- integer keywords now accept negated range

#9929 with doc updated a bit

2023-12-02 06:00 UTC, suricata-qa commented
Information: QA ran without warnings. 

Pipeline 16831

2023-12-15 04:40 UTC, victorjulien requested changes
Looks good to me. Needs a rebase though.

2023-12-19 08:09 UTC, catenacyber commented
Does the first commit deserve its own ticket ?

2023-12-19 08:13 UTC, closed without merging

2023-12-19 08:13 UTC, catenacyber commented
Rebased in https://github.com/OISF/suricata/pull/10073