detect: flush when setting no_inspection
OISF/suricata pull request #9961
Opened 2023-12-05 08:29 UTC by catenacyber

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/6578

Describe changes:
- detect: flush when setting no_inspection

So that we can run detection on the clear text of ssh new keys packet

```
SV_BRANCH=pr/1507
```
https://github.com/OISF/suricata-verify/pull/1507

#9903 rebased with newer S-V PR to get green CI

2023-12-05 10:19 UTC, victorjulien requested changes

2023-12-05 10:19 UTC, victorjulien commented on src/flow-worker.c
> +            p->flow->flags &= ~FLOW_NOPAYLOAD_INSPECTION;
this kind of hack should be avoided. Can we delay the setting of the flow flag until the end of the flow worker logic?

2023-12-05 14:35 UTC, suricata-qa commented
WARNING:
 
 | field | baseline | test | % |
|--|--|--|--| 
| | SURI_TLPW1_stats_chk | | |
| .tcp.pseudo | 7988 | 104960 | 1313.97% |
| | SURI_TLPR1_stats_chk | | |
| .tcp.pseudo | 2810 | 757028 | 26940.5% |
| | IPS_AFP_stats_chk | | |
| .tcp.pseudo | 0 | 974144 | - |
| | TREX_GENERIC_stats_chk | | |
| .tcp.pseudo | 0 | 2980620 | - | 

Pipeline 16870

2023-12-07 13:51 UTC, catenacyber commented
Replaced by https://github.com/OISF/suricata/pull/10004

2023-12-07 13:51 UTC, closed without merging